-- A recurring target is a template kashi fires automatically, creating a
-- real row in branch_targets for each period -- same shape as
-- recurring_expenses (see 000035_create_recurring_expenses.up.sql), but
-- generating a date-ranged row instead of a point-in-time one.
--
-- start_day is the day-of-month a period starts on (not always the 1st --
-- e.g. a billing cycle running the 4th of one month through the 3rd of the
-- next). A period spans [start_day of month M, start_day-1 of month M +
-- interval_count]. Months shorter than start_day clamp to that month's
-- last day (see clampDay in branch_target_series.go) rather than
-- overflowing into the next month the way naive date arithmetic would.
create table if not exists branch_target_series (
    id bigserial primary key,
    branch_id bigint not null references branches(id) on delete cascade,
    target_amount bigint not null,
    color text not null default '',

    start_day int not null check (start_day between 1 and 31),
    interval_count int not null default 1 check (interval_count > 0),

    active boolean not null default true,

    created_at timestamp(0) with time zone not null default now(),
    updated_at timestamp(0) with time zone not null default now()
);

create index on branch_target_series (branch_id);

-- Null means a plain one-off fixed target (today's behavior, unchanged).
-- Set on a branch_targets row generated by the scheduler for one period.
alter table branch_targets
    add column series_id bigint references branch_target_series(id) on delete set null;

create index on branch_targets (series_id);
