// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: asset_category.sql

package db

import (
	"context"
)

const createAssetCategory = `-- name: CreateAssetCategory :one
INSERT INTO asset_categories (
  name,
  is_active,
  icon,
  color
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, is_active, icon, color, created_at
`

type CreateAssetCategoryParams struct {
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
	Icon     string `json:"icon"`
	Color    string `json:"color"`
}

func (q *Queries) CreateAssetCategory(ctx context.Context, arg CreateAssetCategoryParams) (AssetCategory, error) {
	row := q.db.QueryRowContext(ctx, createAssetCategory,
		arg.Name,
		arg.IsActive,
		arg.Icon,
		arg.Color,
	)
	var i AssetCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAssetCategory = `-- name: DeleteAssetCategory :exec
DELETE FROM asset_categories
WHERE id = $1
`

func (q *Queries) DeleteAssetCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAssetCategory, id)
	return err
}

const getAssetCategory = `-- name: GetAssetCategory :one
SELECT id, name, is_active, icon, color, created_at FROM asset_categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAssetCategory(ctx context.Context, id int64) (AssetCategory, error) {
	row := q.db.QueryRowContext(ctx, getAssetCategory, id)
	var i AssetCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listAssetCategories = `-- name: ListAssetCategories :many
SELECT id, name, is_active, icon, color, created_at FROM asset_categories
ORDER BY id
`

func (q *Queries) ListAssetCategories(ctx context.Context) ([]AssetCategory, error) {
	rows, err := q.db.QueryContext(ctx, listAssetCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetCategory{}
	for rows.Next() {
		var i AssetCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.Icon,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetCategory = `-- name: UpdateAssetCategory :one
UPDATE asset_categories
SET name = $2,
    is_active = $3,
    icon = $4,
    color = $5
WHERE id = $1
RETURNING id, name, is_active, icon, color, created_at
`

type UpdateAssetCategoryParams struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
	Icon     string `json:"icon"`
	Color    string `json:"color"`
}

func (q *Queries) UpdateAssetCategory(ctx context.Context, arg UpdateAssetCategoryParams) (AssetCategory, error) {
	row := q.db.QueryRowContext(ctx, updateAssetCategory,
		arg.ID,
		arg.Name,
		arg.IsActive,
		arg.Icon,
		arg.Color,
	)
	var i AssetCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}
