// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: asset.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const countAssets = `-- name: CountAssets :one
SELECT COUNT(*) FROM assets
WHERE ($1::bigint IS NULL OR category_id = $1)
  AND (
    $2::text = ''
    OR name ILIKE '%' || $2::text || '%'
    OR code ILIKE '%' || $2::text || '%'
  )
`

type CountAssetsParams struct {
	CategoryID sql.NullInt64 `json:"category_id"`
	Search     string        `json:"search"`
}

func (q *Queries) CountAssets(ctx context.Context, arg CountAssetsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssets, arg.CategoryID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
  name,
  code,
  category_id,
  bought_at
) VALUES ( $1, $2, $3, $4 )
RETURNING id, name, code, category_id, version, bought_at, created_at
`

type CreateAssetParams struct {
	Name       string    `json:"name"`
	Code       string    `json:"code"`
	CategoryID int64     `json:"category_id"`
	BoughtAt   time.Time `json:"bought_at"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, createAsset,
		arg.Name,
		arg.Code,
		arg.CategoryID,
		arg.BoughtAt,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CategoryID,
		&i.Version,
		&i.BoughtAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets
WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAsset, id)
	return err
}

const deleteAssets = `-- name: DeleteAssets :execrows
DELETE FROM assets
WHERE id = ANY($1::bigint[])
`

func (q *Queries) DeleteAssets(ctx context.Context, ids []int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAssets, pq.Array(ids))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAsset = `-- name: GetAsset :one
SELECT id, name, code, category_id, version, bought_at, created_at FROM assets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAsset(ctx context.Context, id int64) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CategoryID,
		&i.Version,
		&i.BoughtAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAssetsPage = `-- name: ListAssetsPage :many
SELECT id, name, code, category_id, version, bought_at, created_at FROM assets
WHERE ($1::bigint IS NULL OR category_id = $1)
  AND (
    $2::text = ''
    OR name ILIKE '%' || $2::text || '%'
    OR code ILIKE '%' || $2::text || '%'
  )
ORDER BY
  CASE WHEN $3::text = 'name' AND $4::text = 'asc' THEN name END ASC,
  CASE WHEN $3::text = 'name' AND $4::text = 'desc' THEN name END DESC,
  CASE WHEN $3::text = 'code' AND $4::text = 'asc' THEN code END ASC,
  CASE WHEN $3::text = 'code' AND $4::text = 'desc' THEN code END DESC,
  CASE WHEN $3::text = 'bought_at' AND $4::text = 'asc' THEN bought_at END ASC,
  CASE WHEN $3::text = 'bought_at' AND $4::text = 'desc' THEN bought_at END DESC,
  CASE WHEN $3::text = 'id' AND $4::text = 'asc' THEN id END ASC,
  CASE WHEN $3::text = 'id' AND $4::text = 'desc' THEN id END DESC,
  CASE WHEN $3::text = 'created_at' AND $4::text = 'asc' THEN created_at END ASC,
  created_at DESC,
  id DESC
LIMIT $6
OFFSET $5
`

type ListAssetsPageParams struct {
	CategoryID sql.NullInt64 `json:"category_id"`
	Search     string        `json:"search"`
	SortBy     string        `json:"sort_by"`
	SortOrder  string        `json:"sort_order"`
	PageOffset int32         `json:"page_offset"`
	PageSize   int32         `json:"page_size"`
}

func (q *Queries) ListAssetsPage(ctx context.Context, arg ListAssetsPageParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsPage,
		arg.CategoryID,
		arg.Search,
		arg.SortBy,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CategoryID,
			&i.Version,
			&i.BoughtAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets
  SET name = $2,
  code = $3,
  category_id = $4,
  bought_at = $5,
  version = version + 1
WHERE id = $1
RETURNING id, name, code, category_id, version, bought_at, created_at
`

type UpdateAssetParams struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	Code       string    `json:"code"`
	CategoryID int64     `json:"category_id"`
	BoughtAt   time.Time `json:"bought_at"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, updateAsset,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.CategoryID,
		arg.BoughtAt,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CategoryID,
		&i.Version,
		&i.BoughtAt,
		&i.CreatedAt,
	)
	return i, err
}
