// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attributes.sql

package db

import (
	"context"
)

const getAttribute = `-- name: GetAttribute :one
Select id, name
from attributes
WHERe name = $1
`

func (q *Queries) GetAttribute(ctx context.Context, name string) (Attribute, error) {
	row := q.db.QueryRowContext(ctx, getAttribute, name)
	var i Attribute
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getAttributeValue = `-- name: GetAttributeValue :one

SELECT id, attribute_id, value FROM attributes_values
WHERE id = $1
`

// upserting instead of inserting makes product creation with attributes easier
func (q *Queries) GetAttributeValue(ctx context.Context, id int64) (AttributesValue, error) {
	row := q.db.QueryRowContext(ctx, getAttributeValue, id)
	var i AttributesValue
	err := row.Scan(&i.ID, &i.AttributeID, &i.Value)
	return i, err
}

const listAttributeValues = `-- name: ListAttributeValues :many
SELECT a.id, a.name, av.id, av.attribute_id, av.value
FROM attributes a
INNER JOIN attributes_values av
ON a.name = av.attribute
ORDER BY value
LIMIT $1
OFFSET $2
`

type ListAttributeValuesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAttributeValuesRow struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	ID_2        int64  `json:"id_2"`
	AttributeID int64  `json:"attribute_id"`
	Value       string `json:"value"`
}

func (q *Queries) ListAttributeValues(ctx context.Context, arg ListAttributeValuesParams) ([]ListAttributeValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttributeValues, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttributeValuesRow{}
	for rows.Next() {
		var i ListAttributeValuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ID_2,
			&i.AttributeID,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributes = `-- name: ListAttributes :many
SELECT id, name
FROM attributes
ORDER BY name
`

func (q *Queries) ListAttributes(ctx context.Context) ([]Attribute, error) {
	rows, err := q.db.QueryContext(ctx, listAttributes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attribute{}
	for rows.Next() {
		var i Attribute
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttributeValue = `-- name: UpdateAttributeValue :one
UPDATE attributes_values
SET value = $2
WHERE id = $1
RETURNING id, attribute_id, value
`

type UpdateAttributeValueParams struct {
	ID    int64  `json:"id"`
	Value string `json:"value"`
}

func (q *Queries) UpdateAttributeValue(ctx context.Context, arg UpdateAttributeValueParams) (AttributesValue, error) {
	row := q.db.QueryRowContext(ctx, updateAttributeValue, arg.ID, arg.Value)
	var i AttributesValue
	err := row.Scan(&i.ID, &i.AttributeID, &i.Value)
	return i, err
}

const upsertAttributeValue = `-- name: UpsertAttributeValue :one
INSERT INTO attributes_values (attribute_id, value)
VALUES ($1, $2)
ON CONFLICT (attribute_id, value) DO UPDATE SET value = $2
RETURNING id, attribute_id, value
`

type UpsertAttributeValueParams struct {
	AttributeID int64  `json:"attribute_id"`
	Value       string `json:"value"`
}

func (q *Queries) UpsertAttributeValue(ctx context.Context, arg UpsertAttributeValueParams) (AttributesValue, error) {
	row := q.db.QueryRowContext(ctx, upsertAttributeValue, arg.AttributeID, arg.Value)
	var i AttributesValue
	err := row.Scan(&i.ID, &i.AttributeID, &i.Value)
	return i, err
}
