// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: barcode.sql

package db

import (
	"context"
	"time"
)

const createBarcode = `-- name: CreateBarcode :one
INSERT INTO barcodes (
  barcode,
  product_id
  -- color_id,
  -- size_id
) VALUES (
    $1, $2 --, $3, $4
) RETURNING barcode, product_id, version, created_at
`

type CreateBarcodeParams struct {
	Barcode   int64 `json:"barcode"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) CreateBarcode(ctx context.Context, arg CreateBarcodeParams) (Barcode, error) {
	row := q.db.QueryRowContext(ctx, createBarcode, arg.Barcode, arg.ProductID)
	var i Barcode
	err := row.Scan(
		&i.Barcode,
		&i.ProductID,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBarcode = `-- name: DeleteBarcode :exec

DELETE FROM barcodes
WHERE product_id = $1
`

// WARN: beware of renaming the $2 above to $4 or sth
// AND color_id IS NOT DISTINCT FROM $2
// AND size_id IS NOT DISTINCT FROM $3;
func (q *Queries) DeleteBarcode(ctx context.Context, productID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBarcode, productID)
	return err
}

const getBarcode = `-- name: GetBarcode :one
SELECT barcode, product_id, version, created_at FROM barcodes
WHERE product_id = $1
LIMIT 1
`

// can't use = since color & size are nullable
// AND color_id IS NOT DISTINCT FROM $2
// AND size_id IS NOT DISTINCT FROM $3
func (q *Queries) GetBarcode(ctx context.Context, productID int64) (Barcode, error) {
	row := q.db.QueryRowContext(ctx, getBarcode, productID)
	var i Barcode
	err := row.Scan(
		&i.Barcode,
		&i.ProductID,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const getNextBarcodeItemValue = `-- name: GetNextBarcodeItemValue :one
SELECT nextval('barcode_item_seq')::bigint
`

func (q *Queries) GetNextBarcodeItemValue(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextBarcodeItemValue)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listBarcodes = `-- name: ListBarcodes :many
SELECT b.barcode, b.product_id, b.version, b.created_at, p.id, p.code, p.name, p.description, p.is_active, p.created_at FROM barcodes as b
INNER JOIN products as p
ON b.product_id = p.id
ORDER BY p.id
LIMIT $1
OFFSET $2
`

type ListBarcodesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListBarcodesRow struct {
	Barcode     int64     `json:"barcode"`
	ProductID   int64     `json:"product_id"`
	Version     int32     `json:"version"`
	CreatedAt   time.Time `json:"created_at"`
	ID          int64     `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsActive    bool      `json:"is_active"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

// we have color & sizes in both tables, so them only once instead of twice
// LEFT JOIN colors c ON c.id = b.color_id
// LEFT JOIN sizes s ON s.id = b.size_id
// TODO: fix created_at being 2
func (q *Queries) ListBarcodes(ctx context.Context, arg ListBarcodesParams) ([]ListBarcodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listBarcodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBarcodesRow{}
	for rows.Next() {
		var i ListBarcodesRow
		if err := rows.Scan(
			&i.Barcode,
			&i.ProductID,
			&i.Version,
			&i.CreatedAt,
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBarcode = `-- name: UpdateBarcode :exec
UPDATE barcodes
  SET barcode = $2
WHERE product_id = $1
`

type UpdateBarcodeParams struct {
	ProductID int64 `json:"product_id"`
	Barcode   int64 `json:"barcode"`
}

func (q *Queries) UpdateBarcode(ctx context.Context, arg UpdateBarcodeParams) error {
	_, err := q.db.ExecContext(ctx, updateBarcode, arg.ProductID, arg.Barcode)
	return err
}
