// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branch_reconcile.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const branchClientLinksPresent = `-- name: BranchClientLinksPresent :many
SELECT branch_client_id FROM client_links
WHERE branch_id = $1 AND branch_client_id = ANY($2::bigint[])
`

type BranchClientLinksPresentParams struct {
	BranchID int64   `json:"branch_id"`
	Column2  []int64 `json:"column_2"`
}

func (q *Queries) BranchClientLinksPresent(ctx context.Context, arg BranchClientLinksPresentParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, branchClientLinksPresent, arg.BranchID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var branch_client_id int64
		if err := rows.Scan(&branch_client_id); err != nil {
			return nil, err
		}
		items = append(items, branch_client_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const branchExpenseRefsPresent = `-- name: BranchExpenseRefsPresent :many
SELECT client_ref FROM branch_expenses
WHERE branch_id = $1 AND client_ref = ANY($2::text[])
`

type BranchExpenseRefsPresentParams struct {
	BranchID int64    `json:"branch_id"`
	Column2  []string `json:"column_2"`
}

func (q *Queries) BranchExpenseRefsPresent(ctx context.Context, arg BranchExpenseRefsPresentParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, branchExpenseRefsPresent, arg.BranchID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var client_ref string
		if err := rows.Scan(&client_ref); err != nil {
			return nil, err
		}
		items = append(items, client_ref)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const branchInvoiceRefsPresent = `-- name: BranchInvoiceRefsPresent :many

SELECT client_ref FROM branch_invoices
WHERE branch_id = $1 AND client_ref = ANY($2::text[])
`

type BranchInvoiceRefsPresentParams struct {
	BranchID int64    `json:"branch_id"`
	Column2  []string `json:"column_2"`
}

// Reconcile queries: given the refs a branch believes it has pushed, return
// the subset kashi actually holds. The branch diffs its own list against
// this to decide what still needs (re)queuing -- the basis of "sync
// everything to a (possibly new) central server". Each is a single indexed
// `= ANY` lookup; the handler caps the input array size.
func (q *Queries) BranchInvoiceRefsPresent(ctx context.Context, arg BranchInvoiceRefsPresentParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, branchInvoiceRefsPresent, arg.BranchID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var client_ref string
		if err := rows.Scan(&client_ref); err != nil {
			return nil, err
		}
		items = append(items, client_ref)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const branchLoanRefsPresent = `-- name: BranchLoanRefsPresent :many
SELECT client_ref FROM loans
WHERE branch_id = $1 AND client_ref = ANY($2::text[])
`

type BranchLoanRefsPresentParams struct {
	BranchID sql.NullInt64 `json:"branch_id"`
	Column2  []string      `json:"column_2"`
}

func (q *Queries) BranchLoanRefsPresent(ctx context.Context, arg BranchLoanRefsPresentParams) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, branchLoanRefsPresent, arg.BranchID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var client_ref sql.NullString
		if err := rows.Scan(&client_ref); err != nil {
			return nil, err
		}
		items = append(items, client_ref)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productBarcodesPresent = `-- name: ProductBarcodesPresent :many
SELECT barcode FROM product_variants
WHERE barcode = ANY($1::text[])
`

func (q *Queries) ProductBarcodesPresent(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, productBarcodesPresent, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var barcode string
		if err := rows.Scan(&barcode); err != nil {
			return nil, err
		}
		items = append(items, barcode)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
