// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branch_invoice_settlement.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const branchShiftIsClosed = `-- name: BranchShiftIsClosed :one
SELECT EXISTS (
  SELECT 1 FROM branch_shifts
  WHERE branch_id = $1 AND branch_shift_id = $2
) AS closed
`

type BranchShiftIsClosedParams struct {
	BranchID      int64 `json:"branch_id"`
	BranchShiftID int64 `json:"branch_shift_id"`
}

// A branch_shifts row exists only once kashi-pos has reported that shift's
// close, so its mere presence is the "this shift is closed" signal --
// closed_at itself can be NULL for an older till build that omitted it.
func (q *Queries) BranchShiftIsClosed(ctx context.Context, arg BranchShiftIsClosedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, branchShiftIsClosed, arg.BranchID, arg.BranchShiftID)
	var closed bool
	err := row.Scan(&closed)
	return closed, err
}

const countBranchInvoiceSettlements = `-- name: CountBranchInvoiceSettlements :one
SELECT COUNT(*) FROM branch_invoice_settlements
WHERE $1::bigint IS NULL OR branch_id = $1
`

func (q *Queries) CountBranchInvoiceSettlements(ctx context.Context, branchID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBranchInvoiceSettlements, branchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBranchInvoiceSettlement = `-- name: CreateBranchInvoiceSettlement :one
INSERT INTO branch_invoice_settlements (
  branch_id,
  client_ref,
  sale_client_ref,
  grand_total,
  occurred_at,
  status
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, branch_id, client_ref, sale_client_ref, grand_total, occurred_at, received_at, status
`

type CreateBranchInvoiceSettlementParams struct {
	BranchID      int64     `json:"branch_id"`
	ClientRef     string    `json:"client_ref"`
	SaleClientRef string    `json:"sale_client_ref"`
	GrandTotal    int64     `json:"grand_total"`
	OccurredAt    time.Time `json:"occurred_at"`
	Status        string    `json:"status"`
}

func (q *Queries) CreateBranchInvoiceSettlement(ctx context.Context, arg CreateBranchInvoiceSettlementParams) (BranchInvoiceSettlement, error) {
	row := q.db.QueryRowContext(ctx, createBranchInvoiceSettlement,
		arg.BranchID,
		arg.ClientRef,
		arg.SaleClientRef,
		arg.GrandTotal,
		arg.OccurredAt,
		arg.Status,
	)
	var i BranchInvoiceSettlement
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ClientRef,
		&i.SaleClientRef,
		&i.GrandTotal,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.Status,
	)
	return i, err
}

const createBranchInvoiceSettlementPayment = `-- name: CreateBranchInvoiceSettlementPayment :one
INSERT INTO branch_invoice_settlement_payments (
  branch_invoice_settlement_id,
  account_name,
  amount
) VALUES (
  $1, $2, $3
)
RETURNING id, branch_invoice_settlement_id, account_name, amount
`

type CreateBranchInvoiceSettlementPaymentParams struct {
	BranchInvoiceSettlementID int64  `json:"branch_invoice_settlement_id"`
	AccountName               string `json:"account_name"`
	Amount                    int64  `json:"amount"`
}

func (q *Queries) CreateBranchInvoiceSettlementPayment(ctx context.Context, arg CreateBranchInvoiceSettlementPaymentParams) (BranchInvoiceSettlementPayment, error) {
	row := q.db.QueryRowContext(ctx, createBranchInvoiceSettlementPayment, arg.BranchInvoiceSettlementID, arg.AccountName, arg.Amount)
	var i BranchInvoiceSettlementPayment
	err := row.Scan(
		&i.ID,
		&i.BranchInvoiceSettlementID,
		&i.AccountName,
		&i.Amount,
	)
	return i, err
}

const deleteBranchInvoicePaymentsForInvoice = `-- name: DeleteBranchInvoicePaymentsForInvoice :exec
DELETE FROM branch_invoice_payments
WHERE branch_invoice_id = $1
`

func (q *Queries) DeleteBranchInvoicePaymentsForInvoice(ctx context.Context, branchInvoiceID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBranchInvoicePaymentsForInvoice, branchInvoiceID)
	return err
}

const getBranchInvoiceSettlementByClientRef = `-- name: GetBranchInvoiceSettlementByClientRef :one
SELECT id, branch_id, client_ref, sale_client_ref, grand_total, occurred_at, received_at, status FROM branch_invoice_settlements
WHERE branch_id = $1 AND client_ref = $2
LIMIT 1
`

type GetBranchInvoiceSettlementByClientRefParams struct {
	BranchID  int64  `json:"branch_id"`
	ClientRef string `json:"client_ref"`
}

func (q *Queries) GetBranchInvoiceSettlementByClientRef(ctx context.Context, arg GetBranchInvoiceSettlementByClientRefParams) (BranchInvoiceSettlement, error) {
	row := q.db.QueryRowContext(ctx, getBranchInvoiceSettlementByClientRef, arg.BranchID, arg.ClientRef)
	var i BranchInvoiceSettlement
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ClientRef,
		&i.SaleClientRef,
		&i.GrandTotal,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.Status,
	)
	return i, err
}

const listBranchInvoiceSettlementPayments = `-- name: ListBranchInvoiceSettlementPayments :many
SELECT id, branch_invoice_settlement_id, account_name, amount FROM branch_invoice_settlement_payments
WHERE branch_invoice_settlement_id = $1
ORDER BY id
`

func (q *Queries) ListBranchInvoiceSettlementPayments(ctx context.Context, branchInvoiceSettlementID int64) ([]BranchInvoiceSettlementPayment, error) {
	rows, err := q.db.QueryContext(ctx, listBranchInvoiceSettlementPayments, branchInvoiceSettlementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchInvoiceSettlementPayment{}
	for rows.Next() {
		var i BranchInvoiceSettlementPayment
		if err := rows.Scan(
			&i.ID,
			&i.BranchInvoiceSettlementID,
			&i.AccountName,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranchInvoiceSettlements = `-- name: ListBranchInvoiceSettlements :many
SELECT id, branch_id, client_ref, sale_client_ref, grand_total, occurred_at, received_at, status FROM branch_invoice_settlements
WHERE $3::bigint IS NULL OR branch_id = $3
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListBranchInvoiceSettlementsParams struct {
	Limit    int32         `json:"limit"`
	Offset   int32         `json:"offset"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

func (q *Queries) ListBranchInvoiceSettlements(ctx context.Context, arg ListBranchInvoiceSettlementsParams) ([]BranchInvoiceSettlement, error) {
	rows, err := q.db.QueryContext(ctx, listBranchInvoiceSettlements, arg.Limit, arg.Offset, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchInvoiceSettlement{}
	for rows.Next() {
		var i BranchInvoiceSettlement
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.ClientRef,
			&i.SaleClientRef,
			&i.GrandTotal,
			&i.OccurredAt,
			&i.ReceivedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
