// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branch_command.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const completeBranchCommand = `-- name: CompleteBranchCommand :one
UPDATE branch_commands
SET status = $2, result = $3, error = $4, completed_at = now()
WHERE id = $1
RETURNING id, branch_id, type, payload, status, result, error, issued_by, created_at, completed_at
`

type CompleteBranchCommandParams struct {
	ID     int64                 `json:"id"`
	Status string                `json:"status"`
	Result pqtype.NullRawMessage `json:"result"`
	Error  sql.NullString        `json:"error"`
}

func (q *Queries) CompleteBranchCommand(ctx context.Context, arg CompleteBranchCommandParams) (BranchCommand, error) {
	row := q.db.QueryRowContext(ctx, completeBranchCommand,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.Error,
	)
	var i BranchCommand
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.IssuedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createBranchCommand = `-- name: CreateBranchCommand :one
INSERT INTO branch_commands (
  branch_id, type, payload, issued_by
) VALUES (
  $1, $2, $3, $4
) RETURNING id, branch_id, type, payload, status, result, error, issued_by, created_at, completed_at
`

type CreateBranchCommandParams struct {
	BranchID int64           `json:"branch_id"`
	Type     string          `json:"type"`
	Payload  json.RawMessage `json:"payload"`
	IssuedBy int64           `json:"issued_by"`
}

func (q *Queries) CreateBranchCommand(ctx context.Context, arg CreateBranchCommandParams) (BranchCommand, error) {
	row := q.db.QueryRowContext(ctx, createBranchCommand,
		arg.BranchID,
		arg.Type,
		arg.Payload,
		arg.IssuedBy,
	)
	var i BranchCommand
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.IssuedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getBranchCommand = `-- name: GetBranchCommand :one
SELECT id, branch_id, type, payload, status, result, error, issued_by, created_at, completed_at FROM branch_commands WHERE id = $1
`

func (q *Queries) GetBranchCommand(ctx context.Context, id int64) (BranchCommand, error) {
	row := q.db.QueryRowContext(ctx, getBranchCommand, id)
	var i BranchCommand
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.IssuedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listBranchCommands = `-- name: ListBranchCommands :many
SELECT id, branch_id, type, payload, status, result, error, issued_by, created_at, completed_at FROM branch_commands
WHERE branch_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListBranchCommandsParams struct {
	BranchID int64 `json:"branch_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListBranchCommands(ctx context.Context, arg ListBranchCommandsParams) ([]BranchCommand, error) {
	rows, err := q.db.QueryContext(ctx, listBranchCommands, arg.BranchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchCommand{}
	for rows.Next() {
		var i BranchCommand
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Type,
			&i.Payload,
			&i.Status,
			&i.Result,
			&i.Error,
			&i.IssuedBy,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingBranchCommands = `-- name: ListPendingBranchCommands :many
SELECT id, branch_id, type, payload, status, result, error, issued_by, created_at, completed_at FROM branch_commands
WHERE branch_id = $1 AND status = 'pending'
ORDER BY id
`

func (q *Queries) ListPendingBranchCommands(ctx context.Context, branchID int64) ([]BranchCommand, error) {
	rows, err := q.db.QueryContext(ctx, listPendingBranchCommands, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchCommand{}
	for rows.Next() {
		var i BranchCommand
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Type,
			&i.Payload,
			&i.Status,
			&i.Result,
			&i.Error,
			&i.IssuedBy,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
