// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branch_expense_image.sql

package db

import (
	"context"
	"time"
)

const countBranchExpenseImages = `-- name: CountBranchExpenseImages :one
SELECT COUNT(*) FROM branch_expense_images
`

func (q *Queries) CountBranchExpenseImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBranchExpenseImages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBranchExpenseImage = `-- name: CreateBranchExpenseImage :one
INSERT INTO branch_expense_images (
  branch_expense_id,
  file_path,
  content_type,
  size_bytes
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, branch_expense_id, file_path, content_type, size_bytes, created_at
`

type CreateBranchExpenseImageParams struct {
	BranchExpenseID int64  `json:"branch_expense_id"`
	FilePath        string `json:"file_path"`
	ContentType     string `json:"content_type"`
	SizeBytes       int64  `json:"size_bytes"`
}

func (q *Queries) CreateBranchExpenseImage(ctx context.Context, arg CreateBranchExpenseImageParams) (BranchExpenseImage, error) {
	row := q.db.QueryRowContext(ctx, createBranchExpenseImage,
		arg.BranchExpenseID,
		arg.FilePath,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i BranchExpenseImage
	err := row.Scan(
		&i.ID,
		&i.BranchExpenseID,
		&i.FilePath,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const createBranchExpenseUploadToken = `-- name: CreateBranchExpenseUploadToken :one
INSERT INTO branch_expense_upload_tokens (
  branch_expense_id,
  token,
  expires_at
) VALUES (
  $1, $2, $3
)
RETURNING id, branch_expense_id, token, expires_at, used_at, created_at
`

type CreateBranchExpenseUploadTokenParams struct {
	BranchExpenseID int64     `json:"branch_expense_id"`
	Token           string    `json:"token"`
	ExpiresAt       time.Time `json:"expires_at"`
}

func (q *Queries) CreateBranchExpenseUploadToken(ctx context.Context, arg CreateBranchExpenseUploadTokenParams) (BranchExpenseUploadToken, error) {
	row := q.db.QueryRowContext(ctx, createBranchExpenseUploadToken, arg.BranchExpenseID, arg.Token, arg.ExpiresAt)
	var i BranchExpenseUploadToken
	err := row.Scan(
		&i.ID,
		&i.BranchExpenseID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBranchExpenseImage = `-- name: GetBranchExpenseImage :one
SELECT id, branch_expense_id, file_path, content_type, size_bytes, created_at FROM branch_expense_images
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBranchExpenseImage(ctx context.Context, id int64) (BranchExpenseImage, error) {
	row := q.db.QueryRowContext(ctx, getBranchExpenseImage, id)
	var i BranchExpenseImage
	err := row.Scan(
		&i.ID,
		&i.BranchExpenseID,
		&i.FilePath,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getBranchExpenseUploadTokenByToken = `-- name: GetBranchExpenseUploadTokenByToken :one
SELECT id, branch_expense_id, token, expires_at, used_at, created_at FROM branch_expense_upload_tokens
WHERE token = $1
LIMIT 1
`

func (q *Queries) GetBranchExpenseUploadTokenByToken(ctx context.Context, token string) (BranchExpenseUploadToken, error) {
	row := q.db.QueryRowContext(ctx, getBranchExpenseUploadTokenByToken, token)
	var i BranchExpenseUploadToken
	err := row.Scan(
		&i.ID,
		&i.BranchExpenseID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listBranchExpenseImages = `-- name: ListBranchExpenseImages :many
SELECT
  branch_expense_images.id, branch_expense_images.branch_expense_id, branch_expense_images.file_path, branch_expense_images.content_type, branch_expense_images.size_bytes, branch_expense_images.created_at,
  branch_expenses.description AS expense_description,
  branch_expenses.branch_id AS expense_branch_id,
  branches.name AS branch_name
FROM branch_expense_images
JOIN branch_expenses ON branch_expenses.id = branch_expense_images.branch_expense_id
JOIN branches ON branches.id = branch_expenses.branch_id
ORDER BY branch_expense_images.id DESC
LIMIT $1 OFFSET $2
`

type ListBranchExpenseImagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListBranchExpenseImagesRow struct {
	ID                 int64     `json:"id"`
	BranchExpenseID    int64     `json:"branch_expense_id"`
	FilePath           string    `json:"file_path"`
	ContentType        string    `json:"content_type"`
	SizeBytes          int64     `json:"size_bytes"`
	CreatedAt          time.Time `json:"created_at"`
	ExpenseDescription string    `json:"expense_description"`
	ExpenseBranchID    int64     `json:"expense_branch_id"`
	BranchName         string    `json:"branch_name"`
}

// Storage-explorer feed: every uploaded image, newest first, joined with
// its expense and branch so the admin UI never needs a second round trip
// per row.
func (q *Queries) ListBranchExpenseImages(ctx context.Context, arg ListBranchExpenseImagesParams) ([]ListBranchExpenseImagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listBranchExpenseImages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBranchExpenseImagesRow{}
	for rows.Next() {
		var i ListBranchExpenseImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.BranchExpenseID,
			&i.FilePath,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ExpenseDescription,
			&i.ExpenseBranchID,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranchExpenseImagesForExpense = `-- name: ListBranchExpenseImagesForExpense :many
SELECT id, branch_expense_id, file_path, content_type, size_bytes, created_at FROM branch_expense_images
WHERE branch_expense_id = $1
ORDER BY id DESC
`

func (q *Queries) ListBranchExpenseImagesForExpense(ctx context.Context, branchExpenseID int64) ([]BranchExpenseImage, error) {
	rows, err := q.db.QueryContext(ctx, listBranchExpenseImagesForExpense, branchExpenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchExpenseImage{}
	for rows.Next() {
		var i BranchExpenseImage
		if err := rows.Scan(
			&i.ID,
			&i.BranchExpenseID,
			&i.FilePath,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBranchExpenseUploadTokenUsed = `-- name: MarkBranchExpenseUploadTokenUsed :exec
UPDATE branch_expense_upload_tokens
SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkBranchExpenseUploadTokenUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markBranchExpenseUploadTokenUsed, id)
	return err
}
