// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branch_expense.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countBranchExpenses = `-- name: CountBranchExpenses :one
SELECT COUNT(*) FROM branch_expenses
WHERE $1::bigint IS NULL OR branch_id = $1
`

func (q *Queries) CountBranchExpenses(ctx context.Context, branchID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBranchExpenses, branchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBranchExpense = `-- name: CreateBranchExpense :one
INSERT INTO branch_expenses (
  branch_id,
  client_ref,
  description,
  category_id,
  amount,
  currency_code,
  branch_cashbox_account_id,
  branch_shift_id,
  occurred_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, branch_id, client_ref, description, amount, currency_code, branch_cashbox_account_id, branch_shift_id, occurred_at, received_at, category_id
`

type CreateBranchExpenseParams struct {
	BranchID               int64         `json:"branch_id"`
	ClientRef              string        `json:"client_ref"`
	Description            string        `json:"description"`
	CategoryID             sql.NullInt64 `json:"category_id"`
	Amount                 int64         `json:"amount"`
	CurrencyCode           string        `json:"currency_code"`
	BranchCashboxAccountID int64         `json:"branch_cashbox_account_id"`
	BranchShiftID          sql.NullInt64 `json:"branch_shift_id"`
	OccurredAt             time.Time     `json:"occurred_at"`
}

func (q *Queries) CreateBranchExpense(ctx context.Context, arg CreateBranchExpenseParams) (BranchExpense, error) {
	row := q.db.QueryRowContext(ctx, createBranchExpense,
		arg.BranchID,
		arg.ClientRef,
		arg.Description,
		arg.CategoryID,
		arg.Amount,
		arg.CurrencyCode,
		arg.BranchCashboxAccountID,
		arg.BranchShiftID,
		arg.OccurredAt,
	)
	var i BranchExpense
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ClientRef,
		&i.Description,
		&i.Amount,
		&i.CurrencyCode,
		&i.BranchCashboxAccountID,
		&i.BranchShiftID,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.CategoryID,
	)
	return i, err
}

const getBranchExpenseByClientRef = `-- name: GetBranchExpenseByClientRef :one
SELECT id, branch_id, client_ref, description, amount, currency_code, branch_cashbox_account_id, branch_shift_id, occurred_at, received_at, category_id FROM branch_expenses
WHERE branch_id = $1 AND client_ref = $2
LIMIT 1
`

type GetBranchExpenseByClientRefParams struct {
	BranchID  int64  `json:"branch_id"`
	ClientRef string `json:"client_ref"`
}

func (q *Queries) GetBranchExpenseByClientRef(ctx context.Context, arg GetBranchExpenseByClientRefParams) (BranchExpense, error) {
	row := q.db.QueryRowContext(ctx, getBranchExpenseByClientRef, arg.BranchID, arg.ClientRef)
	var i BranchExpense
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ClientRef,
		&i.Description,
		&i.Amount,
		&i.CurrencyCode,
		&i.BranchCashboxAccountID,
		&i.BranchShiftID,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.CategoryID,
	)
	return i, err
}

const listBranchExpenses = `-- name: ListBranchExpenses :many
SELECT id, branch_id, client_ref, description, amount, currency_code, branch_cashbox_account_id, branch_shift_id, occurred_at, received_at, category_id FROM branch_expenses
WHERE $3::bigint IS NULL OR branch_id = $3
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListBranchExpensesParams struct {
	Limit    int32         `json:"limit"`
	Offset   int32         `json:"offset"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

// sqlc.narg(branch_id) is nullable: NULL means "all branches", matching
// ListBranchInvoices' admin-filter convention.
func (q *Queries) ListBranchExpenses(ctx context.Context, arg ListBranchExpensesParams) ([]BranchExpense, error) {
	rows, err := q.db.QueryContext(ctx, listBranchExpenses, arg.Limit, arg.Offset, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchExpense{}
	for rows.Next() {
		var i BranchExpense
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.ClientRef,
			&i.Description,
			&i.Amount,
			&i.CurrencyCode,
			&i.BranchCashboxAccountID,
			&i.BranchShiftID,
			&i.OccurredAt,
			&i.ReceivedAt,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
