// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branch_visitor_event.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countBranchVisitorDays = `-- name: CountBranchVisitorDays :one
SELECT COUNT(*) FROM (
  SELECT 1
  FROM branch_visitor_events
  WHERE $1::bigint IS NULL OR branch_id = $1
  GROUP BY branch_id, day
) t
`

func (q *Queries) CountBranchVisitorDays(ctx context.Context, branchID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBranchVisitorDays, branchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBranchVisitorEvent = `-- name: CreateBranchVisitorEvent :one
INSERT INTO branch_visitor_events (
  branch_id,
  client_ref,
  day,
  direction,
  occurred_at
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, branch_id, client_ref, day, direction, occurred_at, received_at
`

type CreateBranchVisitorEventParams struct {
	BranchID   int64     `json:"branch_id"`
	ClientRef  string    `json:"client_ref"`
	Day        string    `json:"day"`
	Direction  string    `json:"direction"`
	OccurredAt time.Time `json:"occurred_at"`
}

func (q *Queries) CreateBranchVisitorEvent(ctx context.Context, arg CreateBranchVisitorEventParams) (BranchVisitorEvent, error) {
	row := q.db.QueryRowContext(ctx, createBranchVisitorEvent,
		arg.BranchID,
		arg.ClientRef,
		arg.Day,
		arg.Direction,
		arg.OccurredAt,
	)
	var i BranchVisitorEvent
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ClientRef,
		&i.Day,
		&i.Direction,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}

const getBranchVisitorEventByClientRef = `-- name: GetBranchVisitorEventByClientRef :one
SELECT id, branch_id, client_ref, day, direction, occurred_at, received_at FROM branch_visitor_events
WHERE branch_id = $1 AND client_ref = $2
LIMIT 1
`

type GetBranchVisitorEventByClientRefParams struct {
	BranchID  int64  `json:"branch_id"`
	ClientRef string `json:"client_ref"`
}

func (q *Queries) GetBranchVisitorEventByClientRef(ctx context.Context, arg GetBranchVisitorEventByClientRefParams) (BranchVisitorEvent, error) {
	row := q.db.QueryRowContext(ctx, getBranchVisitorEventByClientRef, arg.BranchID, arg.ClientRef)
	var i BranchVisitorEvent
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ClientRef,
		&i.Day,
		&i.Direction,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}

const listBranchVisitorDays = `-- name: ListBranchVisitorDays :many
SELECT
  branch_id,
  day,
  COUNT(*) FILTER (WHERE direction = 'in')  AS in_count,
  COUNT(*) FILTER (WHERE direction = 'out') AS out_count
FROM branch_visitor_events
WHERE $3::bigint IS NULL OR branch_id = $3
GROUP BY branch_id, day
ORDER BY day DESC, branch_id
LIMIT $1 OFFSET $2
`

type ListBranchVisitorDaysParams struct {
	Limit    int32         `json:"limit"`
	Offset   int32         `json:"offset"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

type ListBranchVisitorDaysRow struct {
	BranchID int64  `json:"branch_id"`
	Day      string `json:"day"`
	InCount  int64  `json:"in_count"`
	OutCount int64  `json:"out_count"`
}

// One row per (branch, local day): gross customers-in vs customers-out,
// newest day first. sqlc.narg(branch_id) NULL means "all branches",
// matching ListBranchShifts' admin-filter convention.
func (q *Queries) ListBranchVisitorDays(ctx context.Context, arg ListBranchVisitorDaysParams) ([]ListBranchVisitorDaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listBranchVisitorDays, arg.Limit, arg.Offset, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBranchVisitorDaysRow{}
	for rows.Next() {
		var i ListBranchVisitorDaysRow
		if err := rows.Scan(
			&i.BranchID,
			&i.Day,
			&i.InCount,
			&i.OutCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
