// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branch_target.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createBranchTarget = `-- name: CreateBranchTarget :one
INSERT INTO branch_targets (
  branch_id,
  date_from,
  date_to,
  target_amount,
  color
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, branch_id, date_from, date_to, target_amount, color, created_at, updated_at, series_id, is_active
`

type CreateBranchTargetParams struct {
	BranchID     int64     `json:"branch_id"`
	DateFrom     time.Time `json:"date_from"`
	DateTo       time.Time `json:"date_to"`
	TargetAmount int64     `json:"target_amount"`
	Color        string    `json:"color"`
}

func (q *Queries) CreateBranchTarget(ctx context.Context, arg CreateBranchTargetParams) (BranchTarget, error) {
	row := q.db.QueryRowContext(ctx, createBranchTarget,
		arg.BranchID,
		arg.DateFrom,
		arg.DateTo,
		arg.TargetAmount,
		arg.Color,
	)
	var i BranchTarget
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.DateFrom,
		&i.DateTo,
		&i.TargetAmount,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SeriesID,
		&i.IsActive,
	)
	return i, err
}

const createGeneratedBranchTarget = `-- name: CreateGeneratedBranchTarget :one
INSERT INTO branch_targets (
  branch_id,
  date_from,
  date_to,
  target_amount,
  color,
  series_id
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, branch_id, date_from, date_to, target_amount, color, created_at, updated_at, series_id, is_active
`

type CreateGeneratedBranchTargetParams struct {
	BranchID     int64         `json:"branch_id"`
	DateFrom     time.Time     `json:"date_from"`
	DateTo       time.Time     `json:"date_to"`
	TargetAmount int64         `json:"target_amount"`
	Color        string        `json:"color"`
	SeriesID     sql.NullInt64 `json:"series_id"`
}

// Fires one period for a recurring series -- target_amount/color are
// passed in (a snapshot of the series at generation time) rather than
// joined live, so a later edit to the series template never rewrites a
// period that's already in progress or past, same as recurring_expenses'
// FireRecurringExpenseTx snapshotting its template's amount into the
// created expense row.
func (q *Queries) CreateGeneratedBranchTarget(ctx context.Context, arg CreateGeneratedBranchTargetParams) (BranchTarget, error) {
	row := q.db.QueryRowContext(ctx, createGeneratedBranchTarget,
		arg.BranchID,
		arg.DateFrom,
		arg.DateTo,
		arg.TargetAmount,
		arg.Color,
		arg.SeriesID,
	)
	var i BranchTarget
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.DateFrom,
		&i.DateTo,
		&i.TargetAmount,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SeriesID,
		&i.IsActive,
	)
	return i, err
}

const getBranchTarget = `-- name: GetBranchTarget :one
SELECT id, branch_id, date_from, date_to, target_amount, color, created_at, updated_at, series_id, is_active FROM branch_targets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBranchTarget(ctx context.Context, id int64) (BranchTarget, error) {
	row := q.db.QueryRowContext(ctx, getBranchTarget, id)
	var i BranchTarget
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.DateFrom,
		&i.DateTo,
		&i.TargetAmount,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SeriesID,
		&i.IsActive,
	)
	return i, err
}

const getBranchTargetBySeriesAndStart = `-- name: GetBranchTargetBySeriesAndStart :one
SELECT id, branch_id, date_from, date_to, target_amount, color, created_at, updated_at, series_id, is_active FROM branch_targets
WHERE series_id = $1 AND date_from = $2
LIMIT 1
`

type GetBranchTargetBySeriesAndStartParams struct {
	SeriesID sql.NullInt64 `json:"series_id"`
	DateFrom time.Time     `json:"date_from"`
}

func (q *Queries) GetBranchTargetBySeriesAndStart(ctx context.Context, arg GetBranchTargetBySeriesAndStartParams) (BranchTarget, error) {
	row := q.db.QueryRowContext(ctx, getBranchTargetBySeriesAndStart, arg.SeriesID, arg.DateFrom)
	var i BranchTarget
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.DateFrom,
		&i.DateTo,
		&i.TargetAmount,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SeriesID,
		&i.IsActive,
	)
	return i, err
}

const listBranchTargetsForBranch = `-- name: ListBranchTargetsForBranch :many
SELECT id, branch_id, date_from, date_to, target_amount, color, created_at, updated_at, series_id, is_active FROM branch_targets
WHERE branch_id = $1 AND is_active
ORDER BY target_amount
`

func (q *Queries) ListBranchTargetsForBranch(ctx context.Context, branchID int64) ([]BranchTarget, error) {
	rows, err := q.db.QueryContext(ctx, listBranchTargetsForBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchTarget{}
	for rows.Next() {
		var i BranchTarget
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.DateFrom,
			&i.DateTo,
			&i.TargetAmount,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SeriesID,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranchTargetsUpdatedSince = `-- name: ListBranchTargetsUpdatedSince :many
SELECT id, branch_id, date_from, date_to, target_amount, color, created_at, updated_at, series_id, is_active FROM branch_targets
WHERE branch_id = $1 AND updated_at > $2
ORDER BY updated_at
`

type ListBranchTargetsUpdatedSinceParams struct {
	BranchID  int64     `json:"branch_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListBranchTargetsUpdatedSince(ctx context.Context, arg ListBranchTargetsUpdatedSinceParams) ([]BranchTarget, error) {
	rows, err := q.db.QueryContext(ctx, listBranchTargetsUpdatedSince, arg.BranchID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchTarget{}
	for rows.Next() {
		var i BranchTarget
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.DateFrom,
			&i.DateTo,
			&i.TargetAmount,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SeriesID,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBranchTargetActive = `-- name: SetBranchTargetActive :one
UPDATE branch_targets
SET is_active = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, branch_id, date_from, date_to, target_amount, color, created_at, updated_at, series_id, is_active
`

type SetBranchTargetActiveParams struct {
	ID       int64 `json:"id"`
	IsActive bool  `json:"is_active"`
}

// The sync-facing "delete" -- see 000046_branch_target_soft_delete.up.sql
// for why this flips a flag instead of removing the row.
func (q *Queries) SetBranchTargetActive(ctx context.Context, arg SetBranchTargetActiveParams) (BranchTarget, error) {
	row := q.db.QueryRowContext(ctx, setBranchTargetActive, arg.ID, arg.IsActive)
	var i BranchTarget
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.DateFrom,
		&i.DateTo,
		&i.TargetAmount,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SeriesID,
		&i.IsActive,
	)
	return i, err
}

const sumBranchRevenueForRange = `-- name: SumBranchRevenueForRange :one
SELECT COALESCE(SUM(grand_total), 0)::bigint AS total
FROM branch_invoices
WHERE branch_id = $1
  AND (occurred_at AT TIME ZONE 'UTC')::date BETWEEN $2 AND $3
`

type SumBranchRevenueForRangeParams struct {
	BranchID int64     `json:"branch_id"`
	DateFrom time.Time `json:"date_from"`
	DateTo   time.Time `json:"date_to"`
}

// Net sales revenue: same grand_total-sum convention as ListDailyIncome in
// branch_invoice.sql (returns already net out via their signed grand_total).
func (q *Queries) SumBranchRevenueForRange(ctx context.Context, arg SumBranchRevenueForRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumBranchRevenueForRange, arg.BranchID, arg.DateFrom, arg.DateTo)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateBranchTarget = `-- name: UpdateBranchTarget :one
UPDATE branch_targets
SET date_from = $2,
    date_to = $3,
    target_amount = $4,
    color = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, branch_id, date_from, date_to, target_amount, color, created_at, updated_at, series_id, is_active
`

type UpdateBranchTargetParams struct {
	ID           int64     `json:"id"`
	DateFrom     time.Time `json:"date_from"`
	DateTo       time.Time `json:"date_to"`
	TargetAmount int64     `json:"target_amount"`
	Color        string    `json:"color"`
}

func (q *Queries) UpdateBranchTarget(ctx context.Context, arg UpdateBranchTargetParams) (BranchTarget, error) {
	row := q.db.QueryRowContext(ctx, updateBranchTarget,
		arg.ID,
		arg.DateFrom,
		arg.DateTo,
		arg.TargetAmount,
		arg.Color,
	)
	var i BranchTarget
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.DateFrom,
		&i.DateTo,
		&i.TargetAmount,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SeriesID,
		&i.IsActive,
	)
	return i, err
}
