// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branch_invoice.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countBranchInvoices = `-- name: CountBranchInvoices :one
SELECT COUNT(*) FROM branch_invoices
WHERE $1::bigint IS NULL OR branch_id = $1
`

func (q *Queries) CountBranchInvoices(ctx context.Context, branchID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBranchInvoices, branchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBranchInvoicesFiltered = `-- name: CountBranchInvoicesFiltered :one
SELECT COUNT(*) FROM branch_invoices
WHERE ($1::bigint IS NULL OR branch_id = $1)
  AND (
    $2::text = ''
    OR branch_invoice_code ILIKE '%' || $2::text || '%'
    OR salesperson_name ILIKE '%' || $2::text || '%'
  )
`

type CountBranchInvoicesFilteredParams struct {
	BranchID sql.NullInt64 `json:"branch_id"`
	Search   string        `json:"search"`
}

func (q *Queries) CountBranchInvoicesFiltered(ctx context.Context, arg CountBranchInvoicesFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBranchInvoicesFiltered, arg.BranchID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBranchInvoice = `-- name: CreateBranchInvoice :one
INSERT INTO branch_invoices (
  branch_id,
  client_ref,
  kind,
  branch_invoice_code,
  branch_cashbox_account_id,
  branch_shift_id,
  branch_inventory_id,
  branch_client_id,
  related_client_ref,
  discount,
  subtotal,
  discounted_total,
  grand_total,
  loyalty_points_delta,
  occurred_at,
  salesperson_name,
  historical
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, branch_id, client_ref, kind, branch_invoice_code, branch_cashbox_account_id, branch_shift_id, branch_inventory_id, branch_client_id, related_client_ref, discount, subtotal, discounted_total, grand_total, loyalty_points_delta, occurred_at, received_at, salesperson_name, historical
`

type CreateBranchInvoiceParams struct {
	BranchID               int64          `json:"branch_id"`
	ClientRef              string         `json:"client_ref"`
	Kind                   string         `json:"kind"`
	BranchInvoiceCode      string         `json:"branch_invoice_code"`
	BranchCashboxAccountID int64          `json:"branch_cashbox_account_id"`
	BranchShiftID          int64          `json:"branch_shift_id"`
	BranchInventoryID      int64          `json:"branch_inventory_id"`
	BranchClientID         sql.NullInt64  `json:"branch_client_id"`
	RelatedClientRef       sql.NullString `json:"related_client_ref"`
	Discount               int16          `json:"discount"`
	Subtotal               int64          `json:"subtotal"`
	DiscountedTotal        int64          `json:"discounted_total"`
	GrandTotal             int64          `json:"grand_total"`
	LoyaltyPointsDelta     int64          `json:"loyalty_points_delta"`
	OccurredAt             time.Time      `json:"occurred_at"`
	SalespersonName        string         `json:"salesperson_name"`
	Historical             bool           `json:"historical"`
}

func (q *Queries) CreateBranchInvoice(ctx context.Context, arg CreateBranchInvoiceParams) (BranchInvoice, error) {
	row := q.db.QueryRowContext(ctx, createBranchInvoice,
		arg.BranchID,
		arg.ClientRef,
		arg.Kind,
		arg.BranchInvoiceCode,
		arg.BranchCashboxAccountID,
		arg.BranchShiftID,
		arg.BranchInventoryID,
		arg.BranchClientID,
		arg.RelatedClientRef,
		arg.Discount,
		arg.Subtotal,
		arg.DiscountedTotal,
		arg.GrandTotal,
		arg.LoyaltyPointsDelta,
		arg.OccurredAt,
		arg.SalespersonName,
		arg.Historical,
	)
	var i BranchInvoice
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ClientRef,
		&i.Kind,
		&i.BranchInvoiceCode,
		&i.BranchCashboxAccountID,
		&i.BranchShiftID,
		&i.BranchInventoryID,
		&i.BranchClientID,
		&i.RelatedClientRef,
		&i.Discount,
		&i.Subtotal,
		&i.DiscountedTotal,
		&i.GrandTotal,
		&i.LoyaltyPointsDelta,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.SalespersonName,
		&i.Historical,
	)
	return i, err
}

const createBranchInvoiceItem = `-- name: CreateBranchInvoiceItem :one
INSERT INTO branch_invoice_items (
  branch_invoice_id,
  branch_product_id,
  unit_price,
  line_total,
  discount,
  quantity
) VALUES ( $1, $2, $3, $4, $5, $6 )
RETURNING id, branch_invoice_id, branch_product_id, unit_price, line_total, discount, quantity
`

type CreateBranchInvoiceItemParams struct {
	BranchInvoiceID int64 `json:"branch_invoice_id"`
	BranchProductID int64 `json:"branch_product_id"`
	UnitPrice       int64 `json:"unit_price"`
	LineTotal       int64 `json:"line_total"`
	Discount        int16 `json:"discount"`
	Quantity        int64 `json:"quantity"`
}

func (q *Queries) CreateBranchInvoiceItem(ctx context.Context, arg CreateBranchInvoiceItemParams) (BranchInvoiceItem, error) {
	row := q.db.QueryRowContext(ctx, createBranchInvoiceItem,
		arg.BranchInvoiceID,
		arg.BranchProductID,
		arg.UnitPrice,
		arg.LineTotal,
		arg.Discount,
		arg.Quantity,
	)
	var i BranchInvoiceItem
	err := row.Scan(
		&i.ID,
		&i.BranchInvoiceID,
		&i.BranchProductID,
		&i.UnitPrice,
		&i.LineTotal,
		&i.Discount,
		&i.Quantity,
	)
	return i, err
}

const createBranchInvoicePayment = `-- name: CreateBranchInvoicePayment :one
INSERT INTO branch_invoice_payments (branch_invoice_id, account_name, amount)
VALUES ($1, $2, $3)
RETURNING id, branch_invoice_id, account_name, amount
`

type CreateBranchInvoicePaymentParams struct {
	BranchInvoiceID int64  `json:"branch_invoice_id"`
	AccountName     string `json:"account_name"`
	Amount          int64  `json:"amount"`
}

func (q *Queries) CreateBranchInvoicePayment(ctx context.Context, arg CreateBranchInvoicePaymentParams) (BranchInvoicePayment, error) {
	row := q.db.QueryRowContext(ctx, createBranchInvoicePayment, arg.BranchInvoiceID, arg.AccountName, arg.Amount)
	var i BranchInvoicePayment
	err := row.Scan(
		&i.ID,
		&i.BranchInvoiceID,
		&i.AccountName,
		&i.Amount,
	)
	return i, err
}

const getBranchInvoice = `-- name: GetBranchInvoice :one
SELECT id, branch_id, client_ref, kind, branch_invoice_code, branch_cashbox_account_id, branch_shift_id, branch_inventory_id, branch_client_id, related_client_ref, discount, subtotal, discounted_total, grand_total, loyalty_points_delta, occurred_at, received_at, salesperson_name, historical FROM branch_invoices WHERE id = $1
`

func (q *Queries) GetBranchInvoice(ctx context.Context, id int64) (BranchInvoice, error) {
	row := q.db.QueryRowContext(ctx, getBranchInvoice, id)
	var i BranchInvoice
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ClientRef,
		&i.Kind,
		&i.BranchInvoiceCode,
		&i.BranchCashboxAccountID,
		&i.BranchShiftID,
		&i.BranchInventoryID,
		&i.BranchClientID,
		&i.RelatedClientRef,
		&i.Discount,
		&i.Subtotal,
		&i.DiscountedTotal,
		&i.GrandTotal,
		&i.LoyaltyPointsDelta,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.SalespersonName,
		&i.Historical,
	)
	return i, err
}

const getBranchInvoiceByClientRef = `-- name: GetBranchInvoiceByClientRef :one
SELECT id, branch_id, client_ref, kind, branch_invoice_code, branch_cashbox_account_id, branch_shift_id, branch_inventory_id, branch_client_id, related_client_ref, discount, subtotal, discounted_total, grand_total, loyalty_points_delta, occurred_at, received_at, salesperson_name, historical FROM branch_invoices
WHERE branch_id = $1 AND client_ref = $2
LIMIT 1
`

type GetBranchInvoiceByClientRefParams struct {
	BranchID  int64  `json:"branch_id"`
	ClientRef string `json:"client_ref"`
}

func (q *Queries) GetBranchInvoiceByClientRef(ctx context.Context, arg GetBranchInvoiceByClientRefParams) (BranchInvoice, error) {
	row := q.db.QueryRowContext(ctx, getBranchInvoiceByClientRef, arg.BranchID, arg.ClientRef)
	var i BranchInvoice
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ClientRef,
		&i.Kind,
		&i.BranchInvoiceCode,
		&i.BranchCashboxAccountID,
		&i.BranchShiftID,
		&i.BranchInventoryID,
		&i.BranchClientID,
		&i.RelatedClientRef,
		&i.Discount,
		&i.Subtotal,
		&i.DiscountedTotal,
		&i.GrandTotal,
		&i.LoyaltyPointsDelta,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.SalespersonName,
		&i.Historical,
	)
	return i, err
}

const listBranchInvoiceItems = `-- name: ListBranchInvoiceItems :many
SELECT id, branch_invoice_id, branch_product_id, unit_price, line_total, discount, quantity FROM branch_invoice_items
WHERE branch_invoice_id = $1
`

func (q *Queries) ListBranchInvoiceItems(ctx context.Context, branchInvoiceID int64) ([]BranchInvoiceItem, error) {
	rows, err := q.db.QueryContext(ctx, listBranchInvoiceItems, branchInvoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchInvoiceItem{}
	for rows.Next() {
		var i BranchInvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.BranchInvoiceID,
			&i.BranchProductID,
			&i.UnitPrice,
			&i.LineTotal,
			&i.Discount,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranchInvoicePayments = `-- name: ListBranchInvoicePayments :many
SELECT id, branch_invoice_id, account_name, amount FROM branch_invoice_payments
WHERE branch_invoice_id = $1
ORDER BY id
`

func (q *Queries) ListBranchInvoicePayments(ctx context.Context, branchInvoiceID int64) ([]BranchInvoicePayment, error) {
	rows, err := q.db.QueryContext(ctx, listBranchInvoicePayments, branchInvoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchInvoicePayment{}
	for rows.Next() {
		var i BranchInvoicePayment
		if err := rows.Scan(
			&i.ID,
			&i.BranchInvoiceID,
			&i.AccountName,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranchInvoices = `-- name: ListBranchInvoices :many
SELECT id, branch_id, client_ref, kind, branch_invoice_code, branch_cashbox_account_id, branch_shift_id, branch_inventory_id, branch_client_id, related_client_ref, discount, subtotal, discounted_total, grand_total, loyalty_points_delta, occurred_at, received_at, salesperson_name, historical FROM branch_invoices
WHERE $3::bigint IS NULL OR branch_id = $3
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListBranchInvoicesParams struct {
	Limit    int32         `json:"limit"`
	Offset   int32         `json:"offset"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

// sqlc.narg(branch_id) is nullable: NULL means "all branches", matching how
// the admin UI's branch filter works (a dropdown with an "All branches"
// option, not a required selection).
func (q *Queries) ListBranchInvoices(ctx context.Context, arg ListBranchInvoicesParams) ([]BranchInvoice, error) {
	rows, err := q.db.QueryContext(ctx, listBranchInvoices, arg.Limit, arg.Offset, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchInvoice{}
	for rows.Next() {
		var i BranchInvoice
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.ClientRef,
			&i.Kind,
			&i.BranchInvoiceCode,
			&i.BranchCashboxAccountID,
			&i.BranchShiftID,
			&i.BranchInventoryID,
			&i.BranchClientID,
			&i.RelatedClientRef,
			&i.Discount,
			&i.Subtotal,
			&i.DiscountedTotal,
			&i.GrandTotal,
			&i.LoyaltyPointsDelta,
			&i.OccurredAt,
			&i.ReceivedAt,
			&i.SalespersonName,
			&i.Historical,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranchInvoicesPage = `-- name: ListBranchInvoicesPage :many
SELECT id, branch_id, client_ref, kind, branch_invoice_code, branch_cashbox_account_id, branch_shift_id, branch_inventory_id, branch_client_id, related_client_ref, discount, subtotal, discounted_total, grand_total, loyalty_points_delta, occurred_at, received_at, salesperson_name, historical FROM branch_invoices
WHERE ($1::bigint IS NULL OR branch_id = $1)
  AND (
    $2::text = ''
    OR branch_invoice_code ILIKE '%' || $2::text || '%'
    OR salesperson_name ILIKE '%' || $2::text || '%'
  )
ORDER BY id DESC
LIMIT $4
OFFSET $3
`

type ListBranchInvoicesPageParams struct {
	BranchID   sql.NullInt64 `json:"branch_id"`
	Search     string        `json:"search"`
	PageOffset int32         `json:"page_offset"`
	PageSize   int32         `json:"page_size"`
}

func (q *Queries) ListBranchInvoicesPage(ctx context.Context, arg ListBranchInvoicesPageParams) ([]BranchInvoice, error) {
	rows, err := q.db.QueryContext(ctx, listBranchInvoicesPage,
		arg.BranchID,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchInvoice{}
	for rows.Next() {
		var i BranchInvoice
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.ClientRef,
			&i.Kind,
			&i.BranchInvoiceCode,
			&i.BranchCashboxAccountID,
			&i.BranchShiftID,
			&i.BranchInventoryID,
			&i.BranchClientID,
			&i.RelatedClientRef,
			&i.Discount,
			&i.Subtotal,
			&i.DiscountedTotal,
			&i.GrandTotal,
			&i.LoyaltyPointsDelta,
			&i.OccurredAt,
			&i.ReceivedAt,
			&i.SalespersonName,
			&i.Historical,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranchSalesDaysRange = `-- name: ListBranchSalesDaysRange :many
SELECT
  bi.branch_id,
  (bi.occurred_at AT TIME ZONE b.timezone)::date AS day,
  COUNT(*)::bigint AS invoice_count,
  COALESCE(SUM(bi.grand_total), 0)::bigint AS revenue
FROM branch_invoices bi
JOIN branches b ON b.id = bi.branch_id
WHERE bi.kind = 'sales'
  AND bi.occurred_at >= $1::date
  AND bi.occurred_at < ($2::date + 1)
  AND ($3::bigint IS NULL OR branch_id = $3)
GROUP BY branch_id, day
ORDER BY day, branch_id
`

type ListBranchSalesDaysRangeParams struct {
	FromDay  time.Time     `json:"from_day"`
	ToDay    time.Time     `json:"to_day"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

type ListBranchSalesDaysRangeRow struct {
	BranchID     int64     `json:"branch_id"`
	Day          time.Time `json:"day"`
	InvoiceCount int64     `json:"invoice_count"`
	Revenue      int64     `json:"revenue"`
}

// Per (branch, local day) sales-invoice count and gross sales revenue in an
// inclusive "YYYY-MM-DD" range, oldest first. Deliberately shaped like
// ListBranchVisitorDaysRange so the Footfall page can line footfall up
// against sales for the same window -- conversion rate, average ticket --
// with one extra request and no per-day query.
//
// Only kind = 'sales' counts: a return or exchange isn't a walk-in turning
// into a buyer, and its grand_total carries the branch's own signed
// refund/top-up convention (see ListDailyIncome) which would distort an
// "average sale" figure. The occurred_at range is compared against plain
// date bounds (not AT TIME ZONE per row) so idx_branch_invoices_occurred_at
// stays usable, same reasoning as ListDailyIncome.
func (q *Queries) ListBranchSalesDaysRange(ctx context.Context, arg ListBranchSalesDaysRangeParams) ([]ListBranchSalesDaysRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listBranchSalesDaysRange, arg.FromDay, arg.ToDay, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBranchSalesDaysRangeRow{}
	for rows.Next() {
		var i ListBranchSalesDaysRangeRow
		if err := rows.Scan(
			&i.BranchID,
			&i.Day,
			&i.InvoiceCount,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyIncome = `-- name: ListDailyIncome :many
SELECT
  (bi.occurred_at AT TIME ZONE b.timezone)::date AS day,
  SUM(bi.grand_total)::bigint AS total
FROM branch_invoices bi
JOIN branches b ON b.id = bi.branch_id
WHERE bi.occurred_at >= make_date($1::int, 1, 1)
  AND bi.occurred_at < make_date($1::int + 1, 1, 1)
  AND ($2::bigint IS NULL OR bi.branch_id = $2)
GROUP BY day
ORDER BY day
`

type ListDailyIncomeParams struct {
	Year     int32         `json:"year"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

type ListDailyIncomeRow struct {
	Day   time.Time `json:"day"`
	Total int64     `json:"total"`
}

// Sums grand_total across both kinds ('sales' and 'return') rather than
// treating them separately: a branch's return/exchange grand_total is
// already the net signed cash effect it reported (negative for a refund,
// positive for an even-or-up exchange -- see tx_exchange.go's netDifference
// in kashi-pos), so a plain sum already nets returns against sales
// correctly without this query needing to know or guess that sign
// convention itself.
// The year filter is a >=/< range against a fixed pair of dates rather than
// EXTRACT(YEAR FROM occurred_at) = $1 -- EXTRACT on every row can't use a
// plain btree index on occurred_at (idx_branch_invoices_occurred_at), while
// a range comparison can.
func (q *Queries) ListDailyIncome(ctx context.Context, arg ListDailyIncomeParams) ([]ListDailyIncomeRow, error) {
	rows, err := q.db.QueryContext(ctx, listDailyIncome, arg.Year, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDailyIncomeRow{}
	for rows.Next() {
		var i ListDailyIncomeRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
