// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branch_attendance.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countBranchAttendanceChanges = `-- name: CountBranchAttendanceChanges :one
SELECT COUNT(*) FROM branch_attendance_changes
WHERE $1::bigint IS NULL OR branch_id = $1
`

func (q *Queries) CountBranchAttendanceChanges(ctx context.Context, branchID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBranchAttendanceChanges, branchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBranchAttendanceEvents = `-- name: CountBranchAttendanceEvents :one
SELECT COUNT(*) FROM branch_attendance_events
WHERE $1::bigint IS NULL OR branch_id = $1
`

func (q *Queries) CountBranchAttendanceEvents(ctx context.Context, branchID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBranchAttendanceEvents, branchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBranchAttendanceChange = `-- name: CreateBranchAttendanceChange :one
INSERT INTO branch_attendance_changes (
  branch_id,
  client_ref,
  kind,
  salesperson_name,
  attendance_date,
  original_time,
  requested_time,
  requested_type,
  action,
  status,
  note,
  actor,
  occurred_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, branch_id, client_ref, kind, salesperson_name, attendance_date, original_time, requested_time, requested_type, action, status, note, actor, occurred_at, received_at
`

type CreateBranchAttendanceChangeParams struct {
	BranchID        int64     `json:"branch_id"`
	ClientRef       string    `json:"client_ref"`
	Kind            string    `json:"kind"`
	SalespersonName string    `json:"salesperson_name"`
	AttendanceDate  string    `json:"attendance_date"`
	OriginalTime    string    `json:"original_time"`
	RequestedTime   string    `json:"requested_time"`
	RequestedType   string    `json:"requested_type"`
	Action          string    `json:"action"`
	Status          string    `json:"status"`
	Note            string    `json:"note"`
	Actor           string    `json:"actor"`
	OccurredAt      time.Time `json:"occurred_at"`
}

func (q *Queries) CreateBranchAttendanceChange(ctx context.Context, arg CreateBranchAttendanceChangeParams) (BranchAttendanceChange, error) {
	row := q.db.QueryRowContext(ctx, createBranchAttendanceChange,
		arg.BranchID,
		arg.ClientRef,
		arg.Kind,
		arg.SalespersonName,
		arg.AttendanceDate,
		arg.OriginalTime,
		arg.RequestedTime,
		arg.RequestedType,
		arg.Action,
		arg.Status,
		arg.Note,
		arg.Actor,
		arg.OccurredAt,
	)
	var i BranchAttendanceChange
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ClientRef,
		&i.Kind,
		&i.SalespersonName,
		&i.AttendanceDate,
		&i.OriginalTime,
		&i.RequestedTime,
		&i.RequestedType,
		&i.Action,
		&i.Status,
		&i.Note,
		&i.Actor,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}

const createBranchAttendanceEvent = `-- name: CreateBranchAttendanceEvent :one
INSERT INTO branch_attendance_events (
  branch_id,
  client_ref,
  salesperson_name,
  attendance_user_id,
  event_date,
  event_time,
  event_at,
  type,
  status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, branch_id, client_ref, salesperson_name, attendance_user_id, event_date, event_time, event_at, type, status, received_at
`

type CreateBranchAttendanceEventParams struct {
	BranchID         int64  `json:"branch_id"`
	ClientRef        string `json:"client_ref"`
	SalespersonName  string `json:"salesperson_name"`
	AttendanceUserID string `json:"attendance_user_id"`
	EventDate        string `json:"event_date"`
	EventTime        string `json:"event_time"`
	EventAt          string `json:"event_at"`
	Type             string `json:"type"`
	Status           string `json:"status"`
}

func (q *Queries) CreateBranchAttendanceEvent(ctx context.Context, arg CreateBranchAttendanceEventParams) (BranchAttendanceEvent, error) {
	row := q.db.QueryRowContext(ctx, createBranchAttendanceEvent,
		arg.BranchID,
		arg.ClientRef,
		arg.SalespersonName,
		arg.AttendanceUserID,
		arg.EventDate,
		arg.EventTime,
		arg.EventAt,
		arg.Type,
		arg.Status,
	)
	var i BranchAttendanceEvent
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ClientRef,
		&i.SalespersonName,
		&i.AttendanceUserID,
		&i.EventDate,
		&i.EventTime,
		&i.EventAt,
		&i.Type,
		&i.Status,
		&i.ReceivedAt,
	)
	return i, err
}

const getBranchAttendanceChangeByClientRef = `-- name: GetBranchAttendanceChangeByClientRef :one
SELECT id, branch_id, client_ref, kind, salesperson_name, attendance_date, original_time, requested_time, requested_type, action, status, note, actor, occurred_at, received_at FROM branch_attendance_changes
WHERE branch_id = $1 AND client_ref = $2
LIMIT 1
`

type GetBranchAttendanceChangeByClientRefParams struct {
	BranchID  int64  `json:"branch_id"`
	ClientRef string `json:"client_ref"`
}

func (q *Queries) GetBranchAttendanceChangeByClientRef(ctx context.Context, arg GetBranchAttendanceChangeByClientRefParams) (BranchAttendanceChange, error) {
	row := q.db.QueryRowContext(ctx, getBranchAttendanceChangeByClientRef, arg.BranchID, arg.ClientRef)
	var i BranchAttendanceChange
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ClientRef,
		&i.Kind,
		&i.SalespersonName,
		&i.AttendanceDate,
		&i.OriginalTime,
		&i.RequestedTime,
		&i.RequestedType,
		&i.Action,
		&i.Status,
		&i.Note,
		&i.Actor,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}

const getBranchAttendanceEventByClientRef = `-- name: GetBranchAttendanceEventByClientRef :one
SELECT id, branch_id, client_ref, salesperson_name, attendance_user_id, event_date, event_time, event_at, type, status, received_at FROM branch_attendance_events
WHERE branch_id = $1 AND client_ref = $2
LIMIT 1
`

type GetBranchAttendanceEventByClientRefParams struct {
	BranchID  int64  `json:"branch_id"`
	ClientRef string `json:"client_ref"`
}

func (q *Queries) GetBranchAttendanceEventByClientRef(ctx context.Context, arg GetBranchAttendanceEventByClientRefParams) (BranchAttendanceEvent, error) {
	row := q.db.QueryRowContext(ctx, getBranchAttendanceEventByClientRef, arg.BranchID, arg.ClientRef)
	var i BranchAttendanceEvent
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ClientRef,
		&i.SalespersonName,
		&i.AttendanceUserID,
		&i.EventDate,
		&i.EventTime,
		&i.EventAt,
		&i.Type,
		&i.Status,
		&i.ReceivedAt,
	)
	return i, err
}

const listBranchAttendanceChanges = `-- name: ListBranchAttendanceChanges :many
SELECT id, branch_id, client_ref, kind, salesperson_name, attendance_date, original_time, requested_time, requested_type, action, status, note, actor, occurred_at, received_at FROM branch_attendance_changes
WHERE $3::bigint IS NULL OR branch_id = $3
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListBranchAttendanceChangesParams struct {
	Limit    int32         `json:"limit"`
	Offset   int32         `json:"offset"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

func (q *Queries) ListBranchAttendanceChanges(ctx context.Context, arg ListBranchAttendanceChangesParams) ([]BranchAttendanceChange, error) {
	rows, err := q.db.QueryContext(ctx, listBranchAttendanceChanges, arg.Limit, arg.Offset, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchAttendanceChange{}
	for rows.Next() {
		var i BranchAttendanceChange
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.ClientRef,
			&i.Kind,
			&i.SalespersonName,
			&i.AttendanceDate,
			&i.OriginalTime,
			&i.RequestedTime,
			&i.RequestedType,
			&i.Action,
			&i.Status,
			&i.Note,
			&i.Actor,
			&i.OccurredAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranchAttendanceEvents = `-- name: ListBranchAttendanceEvents :many
SELECT id, branch_id, client_ref, salesperson_name, attendance_user_id, event_date, event_time, event_at, type, status, received_at FROM branch_attendance_events
WHERE $3::bigint IS NULL OR branch_id = $3
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListBranchAttendanceEventsParams struct {
	Limit    int32         `json:"limit"`
	Offset   int32         `json:"offset"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

func (q *Queries) ListBranchAttendanceEvents(ctx context.Context, arg ListBranchAttendanceEventsParams) ([]BranchAttendanceEvent, error) {
	rows, err := q.db.QueryContext(ctx, listBranchAttendanceEvents, arg.Limit, arg.Offset, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchAttendanceEvent{}
	for rows.Next() {
		var i BranchAttendanceEvent
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.ClientRef,
			&i.SalespersonName,
			&i.AttendanceUserID,
			&i.EventDate,
			&i.EventTime,
			&i.EventAt,
			&i.Type,
			&i.Status,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
