// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendar_event.sql

package db

import (
	"context"
	"time"
)

const createCalendarEvent = `-- name: CreateCalendarEvent :one
INSERT INTO calendar_events (
  name,
  icon,
  color,
  start_date,
  end_date
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, name, icon, color, start_date, end_date, created_at
`

type CreateCalendarEventParams struct {
	Name      string    `json:"name"`
	Icon      string    `json:"icon"`
	Color     string    `json:"color"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) CreateCalendarEvent(ctx context.Context, arg CreateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRowContext(ctx, createCalendarEvent,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.StartDate,
		arg.EndDate,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCalendarEvent = `-- name: DeleteCalendarEvent :exec
DELETE FROM calendar_events
WHERE id = $1
`

func (q *Queries) DeleteCalendarEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCalendarEvent, id)
	return err
}

const listCalendarEvents = `-- name: ListCalendarEvents :many
SELECT id, name, icon, color, start_date, end_date, created_at FROM calendar_events
ORDER BY start_date, id
`

func (q *Queries) ListCalendarEvents(ctx context.Context) ([]CalendarEvent, error) {
	rows, err := q.db.QueryContext(ctx, listCalendarEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
