// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addClientLoyaltyPoints = `-- name: AddClientLoyaltyPoints :exec
UPDATE clients 
  SET total_loyalty_points = total_loyalty_points + $2,
  valid_loyalty_points = valid_loyalty_points + $3
WHERE id = $1
`

type AddClientLoyaltyPointsParams struct {
	ID                 int64 `json:"id"`
	TotalLoyaltyPoints int64 `json:"total_loyalty_points"`
	ValidLoyaltyPoints int64 `json:"valid_loyalty_points"`
}

func (q *Queries) AddClientLoyaltyPoints(ctx context.Context, arg AddClientLoyaltyPointsParams) error {
	_, err := q.db.ExecContext(ctx, addClientLoyaltyPoints, arg.ID, arg.TotalLoyaltyPoints, arg.ValidLoyaltyPoints)
	return err
}

const countClients = `-- name: CountClients :one
SELECT COUNT(*) FROM clients
WHERE $1::text IS NULL OR client_type = $1
`

func (q *Queries) CountClients(ctx context.Context, clientType sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClients, clientType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countClientsBySpending = `-- name: CountClientsBySpending :one
SELECT COUNT(*) FROM clients c
WHERE ($1::text IS NULL OR c.client_type = $1)
  AND ($2::text IS NULL OR c.name ILIKE '%' || $2::text || '%' OR c.phone ILIKE '%' || $2::text || '%')
`

type CountClientsBySpendingParams struct {
	ClientType sql.NullString `json:"client_type"`
	Search     sql.NullString `json:"search"`
}

// Same filters as ListClientsBySpending, minus the spend computation --
// used for the rest-of-clients table's pagination total. Deliberately
// ignores branch_id: the count of matching clients doesn't change with
// which branch's sales are being summed, only who qualifies by type/search.
func (q *Queries) CountClientsBySpending(ctx context.Context, arg CountClientsBySpendingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClientsBySpending, arg.ClientType, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
  name,
  phone,
  client_type
) VALUES (
    $1, $2, $3
) RETURNING id, name, phone, total_loyalty_points, valid_loyalty_points, created_at, updated_at, client_type
`

type CreateClientParams struct {
	Name       string `json:"name"`
	Phone      string `json:"phone"`
	ClientType string `json:"client_type"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient, arg.Name, arg.Phone, arg.ClientType)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.TotalLoyaltyPoints,
		&i.ValidLoyaltyPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientType,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients
WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteClient, id)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, name, phone, total_loyalty_points, valid_loyalty_points, created_at, updated_at, client_type FROM clients
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClient(ctx context.Context, id int64) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.TotalLoyaltyPoints,
		&i.ValidLoyaltyPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientType,
	)
	return i, err
}

const getClientByPhone = `-- name: GetClientByPhone :one
SELECT id, name, phone, total_loyalty_points, valid_loyalty_points, created_at, updated_at, client_type FROM clients
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetClientByPhone(ctx context.Context, phone string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByPhone, phone)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.TotalLoyaltyPoints,
		&i.ValidLoyaltyPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientType,
	)
	return i, err
}

const getClientLink = `-- name: GetClientLink :one
SELECT client_id FROM client_links
WHERE branch_id = $1 AND branch_client_id = $2
`

type GetClientLinkParams struct {
	BranchID       int64 `json:"branch_id"`
	BranchClientID int64 `json:"branch_client_id"`
}

func (q *Queries) GetClientLink(ctx context.Context, arg GetClientLinkParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getClientLink, arg.BranchID, arg.BranchClientID)
	var client_id int64
	err := row.Scan(&client_id)
	return client_id, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, phone, total_loyalty_points, valid_loyalty_points, created_at, updated_at, client_type FROM clients
WHERE $3::text IS NULL OR client_type = $3
ORDER BY name
LIMIT $1
OFFSET $2
`

type ListClientsParams struct {
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
	ClientType sql.NullString `json:"client_type"`
}

// sqlc.narg(client_type) is nullable: NULL means "all types" -- the admin
// clients page passes it when a Retail/Wholesale tab is selected, and
// omits it for a combined view if one is ever added.
func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients, arg.Limit, arg.Offset, arg.ClientType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.TotalLoyaltyPoints,
			&i.ValidLoyaltyPoints,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientsBySpending = `-- name: ListClientsBySpending :many
WITH ranked AS (
  SELECT
    c.id, c.name, c.phone, c.total_loyalty_points, c.valid_loyalty_points, c.created_at, c.updated_at, c.client_type,
    (
      CASE WHEN $4::bigint IS NULL THEN COALESCE(ci.central_total, 0) ELSE 0 END
      + COALESCE(bi.branch_total, 0)
    )::bigint AS total_spent,
    (
      CASE WHEN $4::bigint IS NULL THEN COALESCE(ci.central_invoice_count, 0) ELSE 0 END
      + COALESCE(bi.branch_invoice_count, 0)
    )::bigint AS invoice_count,
    (
      CASE WHEN $4::bigint IS NULL THEN COALESCE(ci.central_item_count, 0) ELSE 0 END
      + COALESCE(bi.branch_item_count, 0)
    )::bigint AS item_count
  FROM clients c
  LEFT JOIN (
    SELECT i.client_id,
      SUM(CASE WHEN si.invoice_id IS NOT NULL THEN i.grand_total ELSE -i.grand_total END) AS central_total,
      COUNT(DISTINCT i.id) AS central_invoice_count,
      COALESCE(SUM(ip.quantity), 0) AS central_item_count
    FROM invoices i
    LEFT JOIN sales_invoices si ON si.invoice_id = i.id
    LEFT JOIN invoice_products ip ON ip.invoice_id = i.id
    GROUP BY i.client_id
  ) ci ON ci.client_id = c.id
  LEFT JOIN (
    SELECT cl.client_id,
      SUM(b.grand_total) AS branch_total,
      COUNT(DISTINCT b.id) AS branch_invoice_count,
      COALESCE(SUM(bii.quantity), 0) AS branch_item_count
    FROM branch_invoices b
    JOIN client_links cl ON cl.branch_id = b.branch_id AND cl.branch_client_id = b.branch_client_id
    LEFT JOIN branch_invoice_items bii ON bii.branch_invoice_id = b.id
    WHERE $4::bigint IS NULL OR b.branch_id = $4
    GROUP BY cl.client_id
  ) bi ON bi.client_id = c.id
  WHERE ($5::text IS NULL OR c.client_type = $5)
    AND ($6::text IS NULL OR c.name ILIKE '%' || $6::text || '%' OR c.phone ILIKE '%' || $6::text || '%')
)
SELECT id, name, phone, total_loyalty_points, valid_loyalty_points, created_at, updated_at, client_type, total_spent, invoice_count, item_count
FROM ranked
ORDER BY
  (CASE $3::text
    WHEN 'invoices' THEN invoice_count
    WHEN 'items' THEN item_count
    ELSE total_spent
  END) DESC,
  name ASC
LIMIT $1
OFFSET $2
`

type ListClientsBySpendingParams struct {
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
	SortBy     string         `json:"sort_by"`
	BranchID   sql.NullInt64  `json:"branch_id"`
	ClientType sql.NullString `json:"client_type"`
	Search     sql.NullString `json:"search"`
}

type ListClientsBySpendingRow struct {
	ID                 int64     `json:"id"`
	Name               string    `json:"name"`
	Phone              string    `json:"phone"`
	TotalLoyaltyPoints int64     `json:"total_loyalty_points"`
	ValidLoyaltyPoints int64     `json:"valid_loyalty_points"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	ClientType         string    `json:"client_type"`
	TotalSpent         int64     `json:"total_spent"`
	InvoiceCount       int64     `json:"invoice_count"`
	ItemCount          int64     `json:"item_count"`
}

// Powers the clients "loyalty pyramid" + rest-of-clients table: every
// client ranked by total_spent, invoice_count, or item_count (chosen via
// sort_by -- see the ORDER BY at the bottom). Two sources feed each metric:
// kashi's own admin invoices (sales positive, returns negative --
// invoices.grand_total is always stored as a positive magnitude regardless
// of kind, see ReturnInvoiceTx) and branch-reported sales
// (branch_invoices.grand_total, which already carries the correct net sign
// -- see ListDailyIncome). sqlc.narg(branch_id) scopes to one branch's
// till; central admin invoices aren't attributed to any branch, so they're
// excluded entirely once a single branch is selected (an "All Branches"
// view is the only one where they belong). invoice_count/item_count follow
// the same all-or-one-branch rule for consistency with total_spent.
// invoice_count/item_count are computed in the `ranked` CTE rather than as
// plain SELECT-list aliases so the ORDER BY's CASE expression can actually
// reference them: Postgres only resolves an output alias in ORDER BY when
// it's used bare, not when it's embedded in a larger expression (there it's
// looked up as an ordinary column instead, which fails since it isn't one
// of the FROM clause's columns). Wrapping in a CTE turns them into real
// columns of the derived table, so the CASE inside ORDER BY resolves fine.
func (q *Queries) ListClientsBySpending(ctx context.Context, arg ListClientsBySpendingParams) ([]ListClientsBySpendingRow, error) {
	rows, err := q.db.QueryContext(ctx, listClientsBySpending,
		arg.Limit,
		arg.Offset,
		arg.SortBy,
		arg.BranchID,
		arg.ClientType,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientsBySpendingRow{}
	for rows.Next() {
		var i ListClientsBySpendingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.TotalLoyaltyPoints,
			&i.ValidLoyaltyPoints,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientType,
			&i.TotalSpent,
			&i.InvoiceCount,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientsUpdatedSince = `-- name: ListClientsUpdatedSince :many
SELECT id, name, phone, total_loyalty_points, valid_loyalty_points, created_at, updated_at, client_type FROM clients
WHERE updated_at > $1 AND client_type = 'retail'
ORDER BY updated_at
`

// Feeds the branch catch-up endpoint (see branch_catchup.go), same pattern
// as currencies/cashbox_accounts/products. Wholesale clients never appear
// here -- they're a central-office concept, not something a branch till
// should ever see in its client search. Converting an already-synced
// retail client to wholesale won't retract it from branches that already
// have it locally (no delete propagation exists for any synced entity
// today); acceptable since that conversion is expected to be rare.
func (q *Queries) ListClientsUpdatedSince(ctx context.Context, updatedAt time.Time) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClientsUpdatedSince, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.TotalLoyaltyPoints,
			&i.ValidLoyaltyPoints,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientsWithLoyalty = `-- name: ListClientsWithLoyalty :many
SELECT c.id, c.name, c.phone, c.total_loyalty_points, c.valid_loyalty_points, c.created_at, c.updated_at, c.client_type, COALESCE(bl.branch_points, 0)::bigint AS branch_loyalty_points
FROM clients c
LEFT JOIN (
  SELECT cl.client_id, SUM(bi.loyalty_points_delta) AS branch_points
  FROM branch_invoices bi
  JOIN client_links cl ON cl.branch_id = bi.branch_id AND cl.branch_client_id = bi.branch_client_id
  GROUP BY cl.client_id
) bl ON bl.client_id = c.id
WHERE $3::text IS NULL OR c.client_type = $3
ORDER BY c.name
LIMIT $1
OFFSET $2
`

type ListClientsWithLoyaltyParams struct {
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
	ClientType sql.NullString `json:"client_type"`
}

type ListClientsWithLoyaltyRow struct {
	ID                  int64     `json:"id"`
	Name                string    `json:"name"`
	Phone               string    `json:"phone"`
	TotalLoyaltyPoints  int64     `json:"total_loyalty_points"`
	ValidLoyaltyPoints  int64     `json:"valid_loyalty_points"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
	ClientType          string    `json:"client_type"`
	BranchLoyaltyPoints int64     `json:"branch_loyalty_points"`
}

// Same rows as ListClients, but with each branch's reported loyalty points
// (branch_invoices.loyalty_points_delta, via client_links) summed in
// alongside kashi's own admin-invoice points. Used by the admin clients
// page so the displayed balance isn't missing everything earned at a
// branch till.
func (q *Queries) ListClientsWithLoyalty(ctx context.Context, arg ListClientsWithLoyaltyParams) ([]ListClientsWithLoyaltyRow, error) {
	rows, err := q.db.QueryContext(ctx, listClientsWithLoyalty, arg.Limit, arg.Offset, arg.ClientType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientsWithLoyaltyRow{}
	for rows.Next() {
		var i ListClientsWithLoyaltyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.TotalLoyaltyPoints,
			&i.ValidLoyaltyPoints,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientType,
			&i.BranchLoyaltyPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumClientLoyaltyPoints = `-- name: SumClientLoyaltyPoints :one
SELECT COALESCE(SUM(bi.loyalty_points_delta), 0)::bigint AS total
FROM branch_invoices bi
JOIN client_links cl ON cl.branch_id = bi.branch_id AND cl.branch_client_id = bi.branch_client_id
WHERE cl.client_id = $1
`

// The redemption-time query: every branch's contribution to this client's
// loyalty balance, added up. Each branch is decisive for what it reports
// (loyalty_points_delta on branch_invoices) -- this never recomputes that
// number, only sums what's already been reported.
func (q *Queries) SumClientLoyaltyPoints(ctx context.Context, clientID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumClientLoyaltyPoints, clientID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
  SET name = $2,
  phone = $3,
  client_type = $4,
  updated_at = now()
WHERE id = $1
RETURNING id, name, phone, total_loyalty_points, valid_loyalty_points, created_at, updated_at, client_type
`

type UpdateClientParams struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Phone      string `json:"phone"`
	ClientType string `json:"client_type"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.ClientType,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.TotalLoyaltyPoints,
		&i.ValidLoyaltyPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientType,
	)
	return i, err
}

const upsertClientLink = `-- name: UpsertClientLink :exec
INSERT INTO client_links (branch_id, branch_client_id, client_id)
VALUES ($1, $2, $3)
ON CONFLICT (branch_id, branch_client_id) DO UPDATE SET client_id = EXCLUDED.client_id
`

type UpsertClientLinkParams struct {
	BranchID       int64 `json:"branch_id"`
	BranchClientID int64 `json:"branch_client_id"`
	ClientID       int64 `json:"client_id"`
}

func (q *Queries) UpsertClientLink(ctx context.Context, arg UpsertClientLinkParams) error {
	_, err := q.db.ExecContext(ctx, upsertClientLink, arg.BranchID, arg.BranchClientID, arg.ClientID)
	return err
}
