// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: colors.sql

package db

import (
	"context"
)

const createColor = `-- name: CreateColor :one
INSERT INTO colors (
  name,
  hex_value
) VALUES (
    $1, $2
) RETURNING id, name, hex_value, version
`

type CreateColorParams struct {
	Name     string `json:"name"`
	HexValue string `json:"hex_value"`
}

func (q *Queries) CreateColor(ctx context.Context, arg CreateColorParams) (Color, error) {
	row := q.db.QueryRowContext(ctx, createColor, arg.Name, arg.HexValue)
	var i Color
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HexValue,
		&i.Version,
	)
	return i, err
}

const listColors = `-- name: ListColors :many
SELECT id, name, hex_value, version FROM colors
ORDER BY name
`

func (q *Queries) ListColors(ctx context.Context) ([]Color, error) {
	rows, err := q.db.QueryContext(ctx, listColors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Color{}
	for rows.Next() {
		var i Color
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HexValue,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
