// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coupon_category.sql

package db

import (
	"context"
	"database/sql"
)

const createCouponCategory = `-- name: CreateCouponCategory :one
INSERT INTO coupon_categories (
  name,
  is_active,
  icon,
  color,
  scope
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, name, is_active, icon, color, scope, created_at, updated_at
`

type CreateCouponCategoryParams struct {
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
	Icon     string `json:"icon"`
	Color    string `json:"color"`
	Scope    string `json:"scope"`
}

func (q *Queries) CreateCouponCategory(ctx context.Context, arg CreateCouponCategoryParams) (CouponCategory, error) {
	row := q.db.QueryRowContext(ctx, createCouponCategory,
		arg.Name,
		arg.IsActive,
		arg.Icon,
		arg.Color,
		arg.Scope,
	)
	var i CouponCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.Icon,
		&i.Color,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCouponCategory = `-- name: DeleteCouponCategory :exec
DELETE FROM coupon_categories
WHERE id = $1
`

func (q *Queries) DeleteCouponCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCouponCategory, id)
	return err
}

const getCouponCategory = `-- name: GetCouponCategory :one
SELECT id, name, is_active, icon, color, scope, created_at, updated_at FROM coupon_categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCouponCategory(ctx context.Context, id int64) (CouponCategory, error) {
	row := q.db.QueryRowContext(ctx, getCouponCategory, id)
	var i CouponCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.Icon,
		&i.Color,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCouponCategories = `-- name: ListCouponCategories :many
SELECT id, name, is_active, icon, color, scope, created_at, updated_at FROM coupon_categories
WHERE ($1::text IS NULL OR scope = $1)
ORDER BY id
`

func (q *Queries) ListCouponCategories(ctx context.Context, scope sql.NullString) ([]CouponCategory, error) {
	rows, err := q.db.QueryContext(ctx, listCouponCategories, scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CouponCategory{}
	for rows.Next() {
		var i CouponCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.Icon,
			&i.Color,
			&i.Scope,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCouponCategory = `-- name: UpdateCouponCategory :one
UPDATE coupon_categories
SET name = $2,
    is_active = $3,
    icon = $4,
    color = $5,
    scope = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, is_active, icon, color, scope, created_at, updated_at
`

type UpdateCouponCategoryParams struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
	Icon     string `json:"icon"`
	Color    string `json:"color"`
	Scope    string `json:"scope"`
}

func (q *Queries) UpdateCouponCategory(ctx context.Context, arg UpdateCouponCategoryParams) (CouponCategory, error) {
	row := q.db.QueryRowContext(ctx, updateCouponCategory,
		arg.ID,
		arg.Name,
		arg.IsActive,
		arg.Icon,
		arg.Color,
		arg.Scope,
	)
	var i CouponCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.Icon,
		&i.Color,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
