// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: currency.sql

package db

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const countCurrencies = `-- name: CountCurrencies :one
SELECT COUNT(*) FROM currencies
`

func (q *Queries) CountCurrencies(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCurrencies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCurrency = `-- name: CreateCurrency :one
INSERT INTO currencies (
  name,
  code,
  symbol,
  value_in_default_currency,
  units_per_usd_micros,
  cash_rounding_unit
)
VALUES ( $1, $2, $3, $4, $5, $6 )
RETURNING code, name, symbol, is_default, value_in_default_currency, is_active, units_per_usd_micros, cash_rounding_unit, updated_at
`

type CreateCurrencyParams struct {
	Name                   string `json:"name"`
	Code                   string `json:"code"`
	Symbol                 string `json:"symbol"`
	ValueInDefaultCurrency int64  `json:"value_in_default_currency"`
	UnitsPerUsdMicros      int64  `json:"units_per_usd_micros"`
	CashRoundingUnit       int64  `json:"cash_rounding_unit"`
}

func (q *Queries) CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error) {
	row := q.db.QueryRowContext(ctx, createCurrency,
		arg.Name,
		arg.Code,
		arg.Symbol,
		arg.ValueInDefaultCurrency,
		arg.UnitsPerUsdMicros,
		arg.CashRoundingUnit,
	)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.IsDefault,
		&i.ValueInDefaultCurrency,
		&i.IsActive,
		&i.UnitsPerUsdMicros,
		&i.CashRoundingUnit,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCurrencies = `-- name: DeleteCurrencies :execrows
delete from currencies
where code = ANY($1::text[])
`

func (q *Queries) DeleteCurrencies(ctx context.Context, codes []string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCurrencies, pq.Array(codes))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCurrency = `-- name: DeleteCurrency :exec
delete from currencies
where code = $1
`

func (q *Queries) DeleteCurrency(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, deleteCurrency, code)
	return err
}

const getCurrency = `-- name: GetCurrency :one
SELECT code, name, symbol, is_default, value_in_default_currency, is_active, units_per_usd_micros, cash_rounding_unit, updated_at FROM currencies
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetCurrency(ctx context.Context, code string) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getCurrency, code)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.IsDefault,
		&i.ValueInDefaultCurrency,
		&i.IsActive,
		&i.UnitsPerUsdMicros,
		&i.CashRoundingUnit,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultCurrency = `-- name: GetDefaultCurrency :one
SELECT code, name, symbol, is_default, value_in_default_currency, is_active, units_per_usd_micros, cash_rounding_unit, updated_at FROM currencies
WHERE is_default = true
`

func (q *Queries) GetDefaultCurrency(ctx context.Context) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getDefaultCurrency)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.IsDefault,
		&i.ValueInDefaultCurrency,
		&i.IsActive,
		&i.UnitsPerUsdMicros,
		&i.CashRoundingUnit,
		&i.UpdatedAt,
	)
	return i, err
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT code, name, symbol, is_default, value_in_default_currency, is_active, units_per_usd_micros, cash_rounding_unit, updated_at FROM currencies
ORDER BY code
LIMIT NULLIF($2::int, 0)
OFFSET $1
`

type ListCurrenciesParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

// page_size = 0 returns every currency (the CurrencySelect picker needs the
// whole list); any positive value pages. Order is always by code, so the
// picker and the paged table agree.
func (q *Queries) ListCurrencies(ctx context.Context, arg ListCurrenciesParams) ([]Currency, error) {
	rows, err := q.db.QueryContext(ctx, listCurrencies, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.IsDefault,
			&i.ValueInDefaultCurrency,
			&i.IsActive,
			&i.UnitsPerUsdMicros,
			&i.CashRoundingUnit,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrenciesUpdatedSince = `-- name: ListCurrenciesUpdatedSince :many
SELECT code, name, symbol, is_default, value_in_default_currency, is_active, units_per_usd_micros, cash_rounding_unit, updated_at FROM currencies
WHERE updated_at > $1
ORDER BY updated_at
`

func (q *Queries) ListCurrenciesUpdatedSince(ctx context.Context, updatedAt time.Time) ([]Currency, error) {
	rows, err := q.db.QueryContext(ctx, listCurrenciesUpdatedSince, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.IsDefault,
			&i.ValueInDefaultCurrency,
			&i.IsActive,
			&i.UnitsPerUsdMicros,
			&i.CashRoundingUnit,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCurrency = `-- name: UpdateCurrency :one
UPDATE currencies
SET name = $2,
symbol = $3,
value_in_default_currency = $4,
is_active = $5,
units_per_usd_micros = $6,
cash_rounding_unit = $7,
updated_at = now()
WHERE code = $1
RETURNING code, name, symbol, is_default, value_in_default_currency, is_active, units_per_usd_micros, cash_rounding_unit, updated_at
`

type UpdateCurrencyParams struct {
	Code                   string `json:"code"`
	Name                   string `json:"name"`
	Symbol                 string `json:"symbol"`
	ValueInDefaultCurrency int64  `json:"value_in_default_currency"`
	IsActive               bool   `json:"is_active"`
	UnitsPerUsdMicros      int64  `json:"units_per_usd_micros"`
	CashRoundingUnit       int64  `json:"cash_rounding_unit"`
}

func (q *Queries) UpdateCurrency(ctx context.Context, arg UpdateCurrencyParams) (Currency, error) {
	row := q.db.QueryRowContext(ctx, updateCurrency,
		arg.Code,
		arg.Name,
		arg.Symbol,
		arg.ValueInDefaultCurrency,
		arg.IsActive,
		arg.UnitsPerUsdMicros,
		arg.CashRoundingUnit,
	)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.IsDefault,
		&i.ValueInDefaultCurrency,
		&i.IsActive,
		&i.UnitsPerUsdMicros,
		&i.CashRoundingUnit,
		&i.UpdatedAt,
	)
	return i, err
}
