// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countDashboardExpenses = `-- name: CountDashboardExpenses :one
SELECT (
  (
    SELECT COUNT(*) FROM branch_expenses be
    WHERE $1::text IN ('all', 'branch')
      AND be.occurred_at >= $2::timestamptz
      AND be.occurred_at < $3::timestamptz
      AND ($4::bigint IS NULL OR be.branch_id = $4)
  )
  +
  (
    SELECT COUNT(*) FROM expenses e
    WHERE $1::text IN ('all', 'admin')
      AND e.created_at >= $2::timestamptz
      AND e.created_at < $3::timestamptz
  )
)::bigint AS total
`

type CountDashboardExpensesParams struct {
	Scope    string        `json:"scope"`
	DateFrom time.Time     `json:"date_from"`
	DateTo   time.Time     `json:"date_to"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

func (q *Queries) CountDashboardExpenses(ctx context.Context, arg CountDashboardExpensesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDashboardExpenses,
		arg.Scope,
		arg.DateFrom,
		arg.DateTo,
		arg.BranchID,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countDashboardPurchases = `-- name: CountDashboardPurchases :one
SELECT COUNT(*)::bigint AS total
FROM purchases p
WHERE $1::text IN ('all', 'admin')
  AND p.purchased_at >= $2::timestamptz
  AND p.purchased_at < $3::timestamptz
`

type CountDashboardPurchasesParams struct {
	Scope    string    `json:"scope"`
	DateFrom time.Time `json:"date_from"`
	DateTo   time.Time `json:"date_to"`
}

func (q *Queries) CountDashboardPurchases(ctx context.Context, arg CountDashboardPurchasesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDashboardPurchases, arg.Scope, arg.DateFrom, arg.DateTo)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countDashboardSales = `-- name: CountDashboardSales :one
SELECT (
  (
    SELECT COUNT(*) FROM branch_invoices b
    WHERE b.kind = 'sales'
      AND $1::text IN ('all', 'branch')
      AND b.occurred_at >= $2::timestamptz
      AND b.occurred_at < $3::timestamptz
      AND ($4::bigint IS NULL OR b.branch_id = $4)
  )
  +
  (
    SELECT COUNT(*) FROM invoices i
    JOIN sales_invoices si ON si.invoice_id = i.id
    WHERE $1::text IN ('all', 'admin')
      AND i.created_at >= $2::timestamptz
      AND i.created_at < $3::timestamptz
  )
)::bigint AS total
`

type CountDashboardSalesParams struct {
	Scope    string        `json:"scope"`
	DateFrom time.Time     `json:"date_from"`
	DateTo   time.Time     `json:"date_to"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

func (q *Queries) CountDashboardSales(ctx context.Context, arg CountDashboardSalesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDashboardSales,
		arg.Scope,
		arg.DateFrom,
		arg.DateTo,
		arg.BranchID,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const dashboardActivitiesList = `-- name: DashboardActivitiesList :many

WITH activities AS (
  SELECT
    'Invoice'::text AS activity,
    b.branch_id,
    br.name AS branch_name,
    concat(initcap(b.kind), ' · ', b.branch_invoice_code)::text AS details,
    b.grand_total::bigint AS amount,
    ''::text AS currency_code,
    b.received_at AS synced_at
  FROM branch_invoices b
  JOIN branches br ON br.id = b.branch_id
  WHERE $3::text <> 'admin'
    AND b.received_at >= $4::timestamptz
    AND b.received_at < $5::timestamptz
    AND ($6::bigint IS NULL OR b.branch_id = $6)

  UNION ALL
  SELECT 'Expense', e.branch_id, br.name, e.description,
    -e.amount, e.currency_code, e.received_at
  FROM branch_expenses e
  JOIN branches br ON br.id = e.branch_id
  WHERE $3::text <> 'admin'
    AND e.received_at >= $4::timestamptz
    AND e.received_at < $5::timestamptz
    AND ($6::bigint IS NULL OR e.branch_id = $6)

  UNION ALL
  SELECT 'Loan', l.branch_id, br.name, l.description,
    l.amount, l.currency_code, l.received_at
  FROM loans l
  JOIN branches br ON br.id = l.branch_id
  WHERE $3::text <> 'admin'
    AND l.origin = 'branch_loan'
    AND l.received_at >= $4::timestamptz
    AND l.received_at < $5::timestamptz
    AND ($6::bigint IS NULL OR l.branch_id = $6)

  UNION ALL
  SELECT 'Shift closed', s.branch_id, br.name,
    concat_ws(' · ', nullif(s.closing_person_name, ''), 'USD variance')::text,
    s.variance_usd, 'USD', s.received_at
  FROM branch_shifts s
  JOIN branches br ON br.id = s.branch_id
  WHERE $3::text <> 'admin'
    AND s.received_at >= $4::timestamptz
    AND s.received_at < $5::timestamptz
    AND ($6::bigint IS NULL OR s.branch_id = $6)

  UNION ALL
  SELECT 'Settlement changed', s.branch_id, br.name,
    concat('Invoice ', s.sale_client_ref)::text,
    s.grand_total, '', s.received_at
  FROM branch_invoice_settlements s
  JOIN branches br ON br.id = s.branch_id
  WHERE $3::text <> 'admin'
    AND s.received_at >= $4::timestamptz
    AND s.received_at < $5::timestamptz
    AND ($6::bigint IS NULL OR s.branch_id = $6)

  UNION ALL
  SELECT 'Attendance', a.branch_id, br.name,
    concat_ws(' · ', a.salesperson_name, a.type, a.event_date, a.event_time)::text,
    0::bigint, '', a.received_at
  FROM branch_attendance_events a
  JOIN branches br ON br.id = a.branch_id
  WHERE $3::text <> 'admin'
    AND a.received_at >= $4::timestamptz
    AND a.received_at < $5::timestamptz
    AND ($6::bigint IS NULL OR a.branch_id = $6)

  UNION ALL
  SELECT 'Attendance changed', a.branch_id, br.name,
    concat_ws(' · ', a.salesperson_name, a.kind, a.status, a.note)::text,
    0::bigint, '', a.received_at
  FROM branch_attendance_changes a
  JOIN branches br ON br.id = a.branch_id
  WHERE $3::text <> 'admin'
    AND a.received_at >= $4::timestamptz
    AND a.received_at < $5::timestamptz
    AND ($6::bigint IS NULL OR a.branch_id = $6)
)
SELECT activities.activity, activities.branch_id, activities.branch_name, activities.details, activities.amount, activities.currency_code, activities.synced_at, COUNT(*) OVER()::bigint AS total_count
FROM activities
ORDER BY synced_at DESC
LIMIT $2 OFFSET $1
`

type DashboardActivitiesListParams struct {
	PageID   int32         `json:"page_id"`
	PageSize int32         `json:"page_size"`
	Scope    string        `json:"scope"`
	DateFrom time.Time     `json:"date_from"`
	DateTo   time.Time     `json:"date_to"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

type DashboardActivitiesListRow struct {
	Activity     string    `json:"activity"`
	BranchID     int64     `json:"branch_id"`
	BranchName   string    `json:"branch_name"`
	Details      string    `json:"details"`
	Amount       int64     `json:"amount"`
	CurrencyCode string    `json:"currency_code"`
	SyncedAt     time.Time `json:"synced_at"`
	TotalCount   int64     `json:"total_count"`
}

// Queries behind the home dashboard's Overview tab: the summary cards, the
// revenue/expense trend charts, and the aggregated Sales / Purchases /
// Recent Expenses tables. Every query takes a half-open [date_from,
// date_to) timestamptz range (the handler passes start-of-next-day as
// date_to) and, where a branch dimension exists, a nullable branch_id
// (NULL = all branches, same convention as ListBranchInvoices).
//
// "branch" data is what the POS branches sync up (branch_invoices,
// branch_expenses); "admin" data is kashi's own centrally-entered records
// (invoices/sales_invoices, expenses). The dashboard's scope filter picks
// one or both; the list queries take that as an explicit `scope` arg so a
// single UNION ALL can serve all three modes, while the scalar summary
// queries are split per source and the handler adds up whichever apply.
// One chronological feed across every kind of persisted branch sync. The
// union happens before LIMIT/OFFSET so pagination is correct globally, not
// independently per source table. received_at is used deliberately: this
// table answers "what synced recently", even when a branch catches up an
// older occurred_at record.
func (q *Queries) DashboardActivitiesList(ctx context.Context, arg DashboardActivitiesListParams) ([]DashboardActivitiesListRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardActivitiesList,
		arg.PageID,
		arg.PageSize,
		arg.Scope,
		arg.DateFrom,
		arg.DateTo,
		arg.BranchID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardActivitiesListRow{}
	for rows.Next() {
		var i DashboardActivitiesListRow
		if err := rows.Scan(
			&i.Activity,
			&i.BranchID,
			&i.BranchName,
			&i.Details,
			&i.Amount,
			&i.CurrencyCode,
			&i.SyncedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardAdminExpenseSeries = `-- name: DashboardAdminExpenseSeries :many
SELECT
  (created_at AT TIME ZONE 'UTC')::date AS day,
  COALESCE(SUM(amount), 0)::bigint AS total
FROM expenses
WHERE created_at >= $1::timestamptz
  AND created_at < $2::timestamptz
GROUP BY day
ORDER BY day
`

type DashboardAdminExpenseSeriesParams struct {
	DateFrom time.Time `json:"date_from"`
	DateTo   time.Time `json:"date_to"`
}

type DashboardAdminExpenseSeriesRow struct {
	Day   time.Time `json:"day"`
	Total int64     `json:"total"`
}

func (q *Queries) DashboardAdminExpenseSeries(ctx context.Context, arg DashboardAdminExpenseSeriesParams) ([]DashboardAdminExpenseSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardAdminExpenseSeries, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardAdminExpenseSeriesRow{}
	for rows.Next() {
		var i DashboardAdminExpenseSeriesRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardAdminExpensesTotal = `-- name: DashboardAdminExpensesTotal :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total
FROM expenses
WHERE created_at >= $1::timestamptz
  AND created_at < $2::timestamptz
`

type DashboardAdminExpensesTotalParams struct {
	DateFrom time.Time `json:"date_from"`
	DateTo   time.Time `json:"date_to"`
}

func (q *Queries) DashboardAdminExpensesTotal(ctx context.Context, arg DashboardAdminExpensesTotalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, dashboardAdminExpensesTotal, arg.DateFrom, arg.DateTo)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const dashboardAdminNewClients = `-- name: DashboardAdminNewClients :one
SELECT COUNT(*)::bigint AS total
FROM clients
WHERE created_at >= $1::timestamptz
  AND created_at < $2::timestamptz
`

type DashboardAdminNewClientsParams struct {
	DateFrom time.Time `json:"date_from"`
	DateTo   time.Time `json:"date_to"`
}

func (q *Queries) DashboardAdminNewClients(ctx context.Context, arg DashboardAdminNewClientsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, dashboardAdminNewClients, arg.DateFrom, arg.DateTo)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const dashboardAdminRevenueSeries = `-- name: DashboardAdminRevenueSeries :many
SELECT
  (i.created_at AT TIME ZONE 'UTC')::date AS day,
  COALESCE(SUM(i.grand_total), 0)::bigint AS total
FROM invoices i
JOIN sales_invoices si ON si.invoice_id = i.id
WHERE i.created_at >= $1::timestamptz
  AND i.created_at < $2::timestamptz
GROUP BY day
ORDER BY day
`

type DashboardAdminRevenueSeriesParams struct {
	DateFrom time.Time `json:"date_from"`
	DateTo   time.Time `json:"date_to"`
}

type DashboardAdminRevenueSeriesRow struct {
	Day   time.Time `json:"day"`
	Total int64     `json:"total"`
}

func (q *Queries) DashboardAdminRevenueSeries(ctx context.Context, arg DashboardAdminRevenueSeriesParams) ([]DashboardAdminRevenueSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardAdminRevenueSeries, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardAdminRevenueSeriesRow{}
	for rows.Next() {
		var i DashboardAdminRevenueSeriesRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardAdminSummary = `-- name: DashboardAdminSummary :one
SELECT
  COALESCE((
    SELECT SUM(ip.quantity)
    FROM invoice_products ip
    JOIN sales_invoices si ON si.invoice_id = ip.invoice_id
    JOIN invoices i2 ON i2.id = ip.invoice_id
    WHERE i2.created_at >= $1::timestamptz
      AND i2.created_at < $2::timestamptz
  ), 0)::bigint AS items_sold,
  COALESCE(SUM(i.grand_total), 0)::bigint AS revenue,
  COUNT(*)::bigint AS invoices
FROM invoices i
JOIN sales_invoices si ON si.invoice_id = i.id
WHERE i.created_at >= $1::timestamptz
  AND i.created_at < $2::timestamptz
`

type DashboardAdminSummaryParams struct {
	DateFrom time.Time `json:"date_from"`
	DateTo   time.Time `json:"date_to"`
}

type DashboardAdminSummaryRow struct {
	ItemsSold int64 `json:"items_sold"`
	Revenue   int64 `json:"revenue"`
	Invoices  int64 `json:"invoices"`
}

func (q *Queries) DashboardAdminSummary(ctx context.Context, arg DashboardAdminSummaryParams) (DashboardAdminSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardAdminSummary, arg.DateFrom, arg.DateTo)
	var i DashboardAdminSummaryRow
	err := row.Scan(&i.ItemsSold, &i.Revenue, &i.Invoices)
	return i, err
}

const dashboardBranchExpenseSeries = `-- name: DashboardBranchExpenseSeries :many
SELECT
  (occurred_at AT TIME ZONE 'UTC')::date AS day,
  COALESCE(SUM(amount), 0)::bigint AS total
FROM branch_expenses
WHERE occurred_at >= $1::timestamptz
  AND occurred_at < $2::timestamptz
  AND ($3::bigint IS NULL OR branch_id = $3)
GROUP BY day
ORDER BY day
`

type DashboardBranchExpenseSeriesParams struct {
	DateFrom time.Time     `json:"date_from"`
	DateTo   time.Time     `json:"date_to"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

type DashboardBranchExpenseSeriesRow struct {
	Day   time.Time `json:"day"`
	Total int64     `json:"total"`
}

func (q *Queries) DashboardBranchExpenseSeries(ctx context.Context, arg DashboardBranchExpenseSeriesParams) ([]DashboardBranchExpenseSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardBranchExpenseSeries, arg.DateFrom, arg.DateTo, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardBranchExpenseSeriesRow{}
	for rows.Next() {
		var i DashboardBranchExpenseSeriesRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardBranchExpensesTotal = `-- name: DashboardBranchExpensesTotal :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total
FROM branch_expenses
WHERE occurred_at >= $1::timestamptz
  AND occurred_at < $2::timestamptz
  AND ($3::bigint IS NULL OR branch_id = $3)
`

type DashboardBranchExpensesTotalParams struct {
	DateFrom time.Time     `json:"date_from"`
	DateTo   time.Time     `json:"date_to"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

func (q *Queries) DashboardBranchExpensesTotal(ctx context.Context, arg DashboardBranchExpensesTotalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, dashboardBranchExpensesTotal, arg.DateFrom, arg.DateTo, arg.BranchID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const dashboardBranchNewClients = `-- name: DashboardBranchNewClients :one
SELECT COUNT(*)::bigint AS total
FROM clients c
WHERE c.created_at >= $1::timestamptz
  AND c.created_at < $2::timestamptz
  AND (
    $3::bigint IS NULL
    OR EXISTS (
      SELECT 1 FROM client_links cl
      WHERE cl.client_id = c.id AND cl.branch_id = $3
    )
  )
`

type DashboardBranchNewClientsParams struct {
	DateFrom time.Time     `json:"date_from"`
	DateTo   time.Time     `json:"date_to"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

// Clients first seen at a branch in the range. With a branch selected,
// count distinct linked clients whose central row was created in-range;
// with no branch, every client created in-range.
func (q *Queries) DashboardBranchNewClients(ctx context.Context, arg DashboardBranchNewClientsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, dashboardBranchNewClients, arg.DateFrom, arg.DateTo, arg.BranchID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const dashboardBranchRevenueSeries = `-- name: DashboardBranchRevenueSeries :many
SELECT
  (occurred_at AT TIME ZONE 'UTC')::date AS day,
  COALESCE(SUM(grand_total), 0)::bigint AS total
FROM branch_invoices
WHERE occurred_at >= $1::timestamptz
  AND occurred_at < $2::timestamptz
  AND ($3::bigint IS NULL OR branch_id = $3)
GROUP BY day
ORDER BY day
`

type DashboardBranchRevenueSeriesParams struct {
	DateFrom time.Time     `json:"date_from"`
	DateTo   time.Time     `json:"date_to"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

type DashboardBranchRevenueSeriesRow struct {
	Day   time.Time `json:"day"`
	Total int64     `json:"total"`
}

func (q *Queries) DashboardBranchRevenueSeries(ctx context.Context, arg DashboardBranchRevenueSeriesParams) ([]DashboardBranchRevenueSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardBranchRevenueSeries, arg.DateFrom, arg.DateTo, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardBranchRevenueSeriesRow{}
	for rows.Next() {
		var i DashboardBranchRevenueSeriesRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardBranchSummary = `-- name: DashboardBranchSummary :one
SELECT
  COALESCE((
    SELECT SUM(bii.quantity)
    FROM branch_invoice_items bii
    JOIN branch_invoices b2 ON b2.id = bii.branch_invoice_id
    WHERE b2.kind = 'sales'
      AND b2.occurred_at >= $1::timestamptz
      AND b2.occurred_at < $2::timestamptz
      AND ($3::bigint IS NULL OR b2.branch_id = $3)
  ), 0)::bigint AS items_sold,
  COALESCE(SUM(b.grand_total), 0)::bigint AS revenue,
  COUNT(*) FILTER (WHERE b.kind = 'sales')::bigint AS invoices
FROM branch_invoices b
WHERE b.occurred_at >= $1::timestamptz
  AND b.occurred_at < $2::timestamptz
  AND ($3::bigint IS NULL OR b.branch_id = $3)
`

type DashboardBranchSummaryParams struct {
	DateFrom time.Time     `json:"date_from"`
	DateTo   time.Time     `json:"date_to"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

type DashboardBranchSummaryRow struct {
	ItemsSold int64 `json:"items_sold"`
	Revenue   int64 `json:"revenue"`
	Invoices  int64 `json:"invoices"`
}

// items_sold / revenue / invoice count for branch sales in the range.
// Returns are excluded from items_sold and the count (they aren't sales),
// but revenue sums every kind so refunds net out, matching ListDailyIncome.
func (q *Queries) DashboardBranchSummary(ctx context.Context, arg DashboardBranchSummaryParams) (DashboardBranchSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardBranchSummary, arg.DateFrom, arg.DateTo, arg.BranchID)
	var i DashboardBranchSummaryRow
	err := row.Scan(&i.ItemsSold, &i.Revenue, &i.Invoices)
	return i, err
}

const dashboardDueLoans = `-- name: DashboardDueLoans :one
SELECT (
  COALESCE((
    SELECT SUM(l.amount) FROM loans l
    WHERE (
      ($1::text IN ('all', 'branch') AND l.origin = 'branch_loan'
        AND ($2::bigint IS NULL OR l.branch_id = $2))
      OR ($1::text IN ('all', 'admin') AND l.origin = 'central_loan')
    )
  ), 0)
  -
  COALESCE((
    SELECT SUM(lp.amount) FROM loan_payments lp
    JOIN loans l ON l.id = lp.loan_id
    WHERE (
      ($1::text IN ('all', 'branch') AND l.origin = 'branch_loan'
        AND ($2::bigint IS NULL OR l.branch_id = $2))
      OR ($1::text IN ('all', 'admin') AND l.origin = 'central_loan')
    )
  ), 0)
)::bigint AS outstanding
`

type DashboardDueLoansParams struct {
	Scope    string        `json:"scope"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

// Outstanding loan balance = disbursed - repaid. loans has no due date, so
// "due" here just means still owed. Branch arm = origin 'branch_loan'
// (scoped by branch_id when set); admin arm = origin 'central_loan'.
// loan_payments carry no branch dimension of their own, so they follow
// their parent loan's arm. Not date-range bound -- a balance, not a flow.
func (q *Queries) DashboardDueLoans(ctx context.Context, arg DashboardDueLoansParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, dashboardDueLoans, arg.Scope, arg.BranchID)
	var outstanding int64
	err := row.Scan(&outstanding)
	return outstanding, err
}

const dashboardExpensesList = `-- name: DashboardExpensesList :many
SELECT
  source::text AS source,
  description::text AS description,
  category::text AS category,
  amount::bigint AS amount,
  (SELECT code FROM currencies WHERE is_default LIMIT 1)::text AS currency,
  occurred_at::timestamptz AS occurred_at,
  image_id::bigint AS image_id
FROM (
  SELECT
    'branch'::text AS source,
    be.description AS description,
    COALESCE(ec.name, '')::text AS category,
    be.amount AS amount,
    be.occurred_at AS occurred_at,
    COALESCE((
      SELECT bei.id FROM branch_expense_images bei
      WHERE bei.branch_expense_id = be.id
      ORDER BY bei.id
      LIMIT 1
    ), 0) AS image_id
  FROM branch_expenses be
  LEFT JOIN expense_categories ec ON ec.id = be.category_id
  WHERE $3::text IN ('all', 'branch')
    AND be.occurred_at >= $4::timestamptz
    AND be.occurred_at < $5::timestamptz
    AND ($6::bigint IS NULL OR be.branch_id = $6)

  UNION ALL

  SELECT
    'admin'::text AS source,
    e.description AS description,
    COALESCE(ec.name, '')::text AS category,
    e.amount AS amount,
    e.created_at AS occurred_at,
    0::bigint AS image_id
  FROM expenses e
  LEFT JOIN expense_categories ec ON ec.id = e.category_id
  WHERE $3::text IN ('all', 'admin')
    AND e.created_at >= $4::timestamptz
    AND e.created_at < $5::timestamptz
) rows
ORDER BY occurred_at DESC
LIMIT $1 OFFSET $2
`

type DashboardExpensesListParams struct {
	Limit    int32         `json:"limit"`
	Offset   int32         `json:"offset"`
	Scope    string        `json:"scope"`
	DateFrom time.Time     `json:"date_from"`
	DateTo   time.Time     `json:"date_to"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

type DashboardExpensesListRow struct {
	Source      string    `json:"source"`
	Description string    `json:"description"`
	Category    string    `json:"category"`
	Amount      int64     `json:"amount"`
	Currency    string    `json:"currency"`
	OccurredAt  time.Time `json:"occurred_at"`
	ImageID     int64     `json:"image_id"`
}

// image_id is 0, not NULL, when an expense has no receipt photo (admin
// expenses never do): keeps the generated column a plain int64 and lets
// the frontend treat 0 as "no image".
func (q *Queries) DashboardExpensesList(ctx context.Context, arg DashboardExpensesListParams) ([]DashboardExpensesListRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardExpensesList,
		arg.Limit,
		arg.Offset,
		arg.Scope,
		arg.DateFrom,
		arg.DateTo,
		arg.BranchID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardExpensesListRow{}
	for rows.Next() {
		var i DashboardExpensesListRow
		if err := rows.Scan(
			&i.Source,
			&i.Description,
			&i.Category,
			&i.Amount,
			&i.Currency,
			&i.OccurredAt,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardPurchaseSeries = `-- name: DashboardPurchaseSeries :many
SELECT
  (p.purchased_at AT TIME ZONE 'UTC')::date AS day,
  COALESCE(SUM(pi.quantity * pi.unit_price), 0)::bigint AS total
FROM purchases p
JOIN purchase_items pi ON pi.purchase_id = p.id
WHERE p.purchased_at >= $1::timestamptz
  AND p.purchased_at < $2::timestamptz
GROUP BY day
ORDER BY day
`

type DashboardPurchaseSeriesParams struct {
	DateFrom time.Time `json:"date_from"`
	DateTo   time.Time `json:"date_to"`
}

type DashboardPurchaseSeriesRow struct {
	Day   time.Time `json:"day"`
	Total int64     `json:"total"`
}

func (q *Queries) DashboardPurchaseSeries(ctx context.Context, arg DashboardPurchaseSeriesParams) ([]DashboardPurchaseSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardPurchaseSeries, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardPurchaseSeriesRow{}
	for rows.Next() {
		var i DashboardPurchaseSeriesRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardPurchasesList = `-- name: DashboardPurchasesList :many
SELECT
  p.id AS id,
  s.name AS supplier,
  COALESCE((
    SELECT SUM(pi.quantity * pi.unit_price)
    FROM purchase_items pi
    WHERE pi.purchase_id = p.id
  ), 0)::bigint AS total,
  COALESCE((
    SELECT SUM(pi.quantity)
    FROM purchase_items pi
    WHERE pi.purchase_id = p.id
  ), 0)::bigint AS items,
  (SELECT code FROM currencies WHERE is_default LIMIT 1)::text AS currency,
  p.purchased_at AS purchased_at
FROM purchases p
JOIN suppliers s ON s.id = p.supplier_id
WHERE $3::text IN ('all', 'admin')
  AND p.purchased_at >= $4::timestamptz
  AND p.purchased_at < $5::timestamptz
ORDER BY p.purchased_at DESC
LIMIT $1 OFFSET $2
`

type DashboardPurchasesListParams struct {
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	Scope    string    `json:"scope"`
	DateFrom time.Time `json:"date_from"`
	DateTo   time.Time `json:"date_to"`
}

type DashboardPurchasesListRow struct {
	ID          int64     `json:"id"`
	Supplier    string    `json:"supplier"`
	Total       int64     `json:"total"`
	Items       int64     `json:"items"`
	Currency    string    `json:"currency"`
	PurchasedAt time.Time `json:"purchased_at"`
}

// Purchases are admin-only -- there is no branch purchase concept -- so the
// scope arg only ever excludes them (scope = 'branch'), never adds a second
// source. total is summed from purchase_items since purchases carries no
// amount column of its own.
func (q *Queries) DashboardPurchasesList(ctx context.Context, arg DashboardPurchasesListParams) ([]DashboardPurchasesListRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardPurchasesList,
		arg.Limit,
		arg.Offset,
		arg.Scope,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardPurchasesListRow{}
	for rows.Next() {
		var i DashboardPurchasesListRow
		if err := rows.Scan(
			&i.ID,
			&i.Supplier,
			&i.Total,
			&i.Items,
			&i.Currency,
			&i.PurchasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardPurchasesTotal = `-- name: DashboardPurchasesTotal :one
SELECT COALESCE(SUM(pi.quantity * pi.unit_price), 0)::bigint AS total
FROM purchases p
JOIN purchase_items pi ON pi.purchase_id = p.id
WHERE p.purchased_at >= $1::timestamptz
  AND p.purchased_at < $2::timestamptz
`

type DashboardPurchasesTotalParams struct {
	DateFrom time.Time `json:"date_from"`
	DateTo   time.Time `json:"date_to"`
}

// Cost of goods bought in the range. Admin-only (no branch purchase
// concept); total is summed from purchase_items since purchases carries no
// amount column of its own, matching DashboardPurchasesList.
func (q *Queries) DashboardPurchasesTotal(ctx context.Context, arg DashboardPurchasesTotalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, dashboardPurchasesTotal, arg.DateFrom, arg.DateTo)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const dashboardSalesList = `-- name: DashboardSalesList :many
SELECT
  source::text AS source,
  client::text AS client,
  total::bigint AS total,
  (SELECT code FROM currencies WHERE is_default LIMIT 1)::text AS currency,
  occurred_at::timestamptz AS occurred_at
FROM (
  SELECT
    'branch'::text AS source,
    COALESCE(bc.name, '')::text AS client,
    b.grand_total AS total,
    b.occurred_at AS occurred_at
  FROM branch_invoices b
  LEFT JOIN client_links cl
    ON cl.branch_id = b.branch_id AND cl.branch_client_id = b.branch_client_id
  LEFT JOIN clients bc ON bc.id = cl.client_id
  WHERE b.kind = 'sales'
    AND $3::text IN ('all', 'branch')
    AND b.occurred_at >= $4::timestamptz
    AND b.occurred_at < $5::timestamptz
    AND ($6::bigint IS NULL OR b.branch_id = $6)

  UNION ALL

  SELECT
    'admin'::text AS source,
    COALESCE(c.name, '')::text AS client,
    i.grand_total AS total,
    i.created_at AS occurred_at
  FROM invoices i
  JOIN sales_invoices si ON si.invoice_id = i.id
  LEFT JOIN clients c ON c.id = i.client_id
  WHERE $3::text IN ('all', 'admin')
    AND i.created_at >= $4::timestamptz
    AND i.created_at < $5::timestamptz
) rows
ORDER BY occurred_at DESC
LIMIT $1 OFFSET $2
`

type DashboardSalesListParams struct {
	Limit    int32         `json:"limit"`
	Offset   int32         `json:"offset"`
	Scope    string        `json:"scope"`
	DateFrom time.Time     `json:"date_from"`
	DateTo   time.Time     `json:"date_to"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

type DashboardSalesListRow struct {
	Source     string    `json:"source"`
	Client     string    `json:"client"`
	Total      int64     `json:"total"`
	Currency   string    `json:"currency"`
	OccurredAt time.Time `json:"occurred_at"`
}

// currency is the app's single default currency code (every amount in the
// schema is stored in its minor unit -- see 000009_create_currencies).
// The branch-invoice client name is resolved through client_links; when
// the branch never synced a client link it comes back empty.
func (q *Queries) DashboardSalesList(ctx context.Context, arg DashboardSalesListParams) ([]DashboardSalesListRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardSalesList,
		arg.Limit,
		arg.Offset,
		arg.Scope,
		arg.DateFrom,
		arg.DateTo,
		arg.BranchID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardSalesListRow{}
	for rows.Next() {
		var i DashboardSalesListRow
		if err := rows.Scan(
			&i.Source,
			&i.Client,
			&i.Total,
			&i.Currency,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardTargetList = `-- name: DashboardTargetList :many
SELECT
  t.id,
  t.branch_id,
  b.name AS branch_name,
  t.date_from,
  t.date_to,
  t.target_amount,
  t.color,
  COALESCE((
    SELECT SUM(bi.grand_total)
    FROM branch_invoices bi
    WHERE bi.branch_id = t.branch_id
      AND (bi.occurred_at AT TIME ZONE 'UTC')::date BETWEEN t.date_from AND t.date_to
  ), 0)::bigint AS revenue
FROM branch_targets t
JOIN branches b ON b.id = t.branch_id
WHERE t.is_active
  AND t.date_from <= $1::date
  AND t.date_to >= $1::date
  AND ($2::bigint IS NULL OR t.branch_id = $2)
ORDER BY b.name, t.date_from
`

type DashboardTargetListParams struct {
	AsOf     time.Time     `json:"as_of"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

type DashboardTargetListRow struct {
	ID           int64     `json:"id"`
	BranchID     int64     `json:"branch_id"`
	BranchName   string    `json:"branch_name"`
	DateFrom     time.Time `json:"date_from"`
	DateTo       time.Time `json:"date_to"`
	TargetAmount int64     `json:"target_amount"`
	Color        string    `json:"color"`
	Revenue      int64     `json:"revenue"`
}

// Every branch_target that is active and spans `as_of` (today), with its
// live revenue (the target's own [date_from, date_to] window against its
// own branch). One progress bar per row on the dashboard; the handler also
// sums these for the overall attainment percentage. branch_targets are
// branch-only, so the handler skips this under admin scope.
func (q *Queries) DashboardTargetList(ctx context.Context, arg DashboardTargetListParams) ([]DashboardTargetListRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardTargetList, arg.AsOf, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardTargetListRow{}
	for rows.Next() {
		var i DashboardTargetListRow
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.BranchName,
			&i.DateFrom,
			&i.DateTo,
			&i.TargetAmount,
			&i.Color,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardTopDueLoans = `-- name: DashboardTopDueLoans :many
SELECT
  l.id,
  l.description,
  l.origin,
  COALESCE(b.name, '') AS branch_name,
  l.amount,
  (l.amount - COALESCE((
    SELECT SUM(lp.amount) FROM loan_payments lp WHERE lp.loan_id = l.id
  ), 0))::bigint AS outstanding
FROM loans l
LEFT JOIN branches b ON b.id = l.branch_id
WHERE (
    ($1::text IN ('all', 'branch') AND l.origin = 'branch_loan'
      AND ($2::bigint IS NULL OR l.branch_id = $2))
    OR ($1::text IN ('all', 'admin') AND l.origin = 'central_loan')
  )
  AND (l.amount - COALESCE((
    SELECT SUM(lp.amount) FROM loan_payments lp WHERE lp.loan_id = l.id
  ), 0)) > 0
ORDER BY outstanding DESC
LIMIT $3::int
`

type DashboardTopDueLoansParams struct {
	Scope    string        `json:"scope"`
	BranchID sql.NullInt64 `json:"branch_id"`
	TopN     int32         `json:"top_n"`
}

type DashboardTopDueLoansRow struct {
	ID          int64  `json:"id"`
	Description string `json:"description"`
	Origin      string `json:"origin"`
	BranchName  string `json:"branch_name"`
	Amount      int64  `json:"amount"`
	Outstanding int64  `json:"outstanding"`
}

// The loans with the largest outstanding balance, for the dashboard's
// "Due Loans" list. Same scope/branch gating as DashboardDueLoans; fully
// repaid loans (outstanding <= 0) are dropped.
func (q *Queries) DashboardTopDueLoans(ctx context.Context, arg DashboardTopDueLoansParams) ([]DashboardTopDueLoansRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardTopDueLoans, arg.Scope, arg.BranchID, arg.TopN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardTopDueLoansRow{}
	for rows.Next() {
		var i DashboardTopDueLoansRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Origin,
			&i.BranchName,
			&i.Amount,
			&i.Outstanding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
