// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employee.sql

package db

import (
	"context"
	"database/sql"
)

const countEmployees = `-- name: CountEmployees :one
SELECT COUNT(*) FROM employees
WHERE (
    BTRIM($1::text) = ''
    OR name ILIKE '%' || BTRIM($1::text) || '%'
    OR role ILIKE '%' || BTRIM($1::text) || '%'
  )
  AND ($2::bigint IS NULL OR branch_id = $2)
`

type CountEmployeesParams struct {
	Search   string        `json:"search"`
	BranchID sql.NullInt64 `json:"branch_id"`
}

func (q *Queries) CountEmployees(ctx context.Context, arg CountEmployeesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmployees, arg.Search, arg.BranchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (
  branch_id,
  name,
  role,
  status,
  hired_on,
  base_salary_cents,
  commission_cents,
  late_deduction_rate_cents,
  late_deduction_unit,
  late_units_centi
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, branch_id, name, role, status, hired_on, base_salary_cents, commission_cents, late_deduction_rate_cents, late_deduction_unit, late_units_centi, created_at, updated_at
`

type CreateEmployeeParams struct {
	BranchID               sql.NullInt64 `json:"branch_id"`
	Name                   string        `json:"name"`
	Role                   string        `json:"role"`
	Status                 string        `json:"status"`
	HiredOn                sql.NullTime  `json:"hired_on"`
	BaseSalaryCents        int64         `json:"base_salary_cents"`
	CommissionCents        int64         `json:"commission_cents"`
	LateDeductionRateCents int64         `json:"late_deduction_rate_cents"`
	LateDeductionUnit      string        `json:"late_deduction_unit"`
	LateUnitsCenti         int64         `json:"late_units_centi"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRowContext(ctx, createEmployee,
		arg.BranchID,
		arg.Name,
		arg.Role,
		arg.Status,
		arg.HiredOn,
		arg.BaseSalaryCents,
		arg.CommissionCents,
		arg.LateDeductionRateCents,
		arg.LateDeductionUnit,
		arg.LateUnitsCenti,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.HiredOn,
		&i.BaseSalaryCents,
		&i.CommissionCents,
		&i.LateDeductionRateCents,
		&i.LateDeductionUnit,
		&i.LateUnitsCenti,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees WHERE id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEmployee, id)
	return err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, branch_id, name, role, status, hired_on, base_salary_cents, commission_cents, late_deduction_rate_cents, late_deduction_unit, late_units_centi, created_at, updated_at FROM employees
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmployee(ctx context.Context, id int64) (Employee, error) {
	row := q.db.QueryRowContext(ctx, getEmployee, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.HiredOn,
		&i.BaseSalaryCents,
		&i.CommissionCents,
		&i.LateDeductionRateCents,
		&i.LateDeductionUnit,
		&i.LateUnitsCenti,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, branch_id, name, role, status, hired_on, base_salary_cents, commission_cents, late_deduction_rate_cents, late_deduction_unit, late_units_centi, created_at, updated_at FROM employees
WHERE (
    BTRIM($1::text) = ''
    OR name ILIKE '%' || BTRIM($1::text) || '%'
    OR role ILIKE '%' || BTRIM($1::text) || '%'
  )
  AND ($2::bigint IS NULL OR branch_id = $2)
ORDER BY name
LIMIT $4
OFFSET $3
`

type ListEmployeesParams struct {
	Search     string        `json:"search"`
	BranchID   sql.NullInt64 `json:"branch_id"`
	PageOffset int32         `json:"page_offset"`
	PageSize   int32         `json:"page_size"`
}

func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Employee, error) {
	rows, err := q.db.QueryContext(ctx, listEmployees,
		arg.Search,
		arg.BranchID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Name,
			&i.Role,
			&i.Status,
			&i.HiredOn,
			&i.BaseSalaryCents,
			&i.CommissionCents,
			&i.LateDeductionRateCents,
			&i.LateDeductionUnit,
			&i.LateUnitsCenti,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET branch_id = $2,
    name = $3,
    role = $4,
    status = $5,
    hired_on = $6,
    base_salary_cents = $7,
    commission_cents = $8,
    late_deduction_rate_cents = $9,
    late_deduction_unit = $10,
    late_units_centi = $11,
    updated_at = now()
WHERE id = $1
RETURNING id, branch_id, name, role, status, hired_on, base_salary_cents, commission_cents, late_deduction_rate_cents, late_deduction_unit, late_units_centi, created_at, updated_at
`

type UpdateEmployeeParams struct {
	ID                     int64         `json:"id"`
	BranchID               sql.NullInt64 `json:"branch_id"`
	Name                   string        `json:"name"`
	Role                   string        `json:"role"`
	Status                 string        `json:"status"`
	HiredOn                sql.NullTime  `json:"hired_on"`
	BaseSalaryCents        int64         `json:"base_salary_cents"`
	CommissionCents        int64         `json:"commission_cents"`
	LateDeductionRateCents int64         `json:"late_deduction_rate_cents"`
	LateDeductionUnit      string        `json:"late_deduction_unit"`
	LateUnitsCenti         int64         `json:"late_units_centi"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRowContext(ctx, updateEmployee,
		arg.ID,
		arg.BranchID,
		arg.Name,
		arg.Role,
		arg.Status,
		arg.HiredOn,
		arg.BaseSalaryCents,
		arg.CommissionCents,
		arg.LateDeductionRateCents,
		arg.LateDeductionUnit,
		arg.LateUnitsCenti,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.HiredOn,
		&i.BaseSalaryCents,
		&i.CommissionCents,
		&i.LateDeductionRateCents,
		&i.LateDeductionUnit,
		&i.LateUnitsCenti,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmployeeSalary = `-- name: UpdateEmployeeSalary :one
UPDATE employees
SET base_salary_cents = $2,
    commission_cents = $3,
    late_deduction_rate_cents = $4,
    late_deduction_unit = $5,
    late_units_centi = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, branch_id, name, role, status, hired_on, base_salary_cents, commission_cents, late_deduction_rate_cents, late_deduction_unit, late_units_centi, created_at, updated_at
`

type UpdateEmployeeSalaryParams struct {
	ID                     int64  `json:"id"`
	BaseSalaryCents        int64  `json:"base_salary_cents"`
	CommissionCents        int64  `json:"commission_cents"`
	LateDeductionRateCents int64  `json:"late_deduction_rate_cents"`
	LateDeductionUnit      string `json:"late_deduction_unit"`
	LateUnitsCenti         int64  `json:"late_units_centi"`
}

func (q *Queries) UpdateEmployeeSalary(ctx context.Context, arg UpdateEmployeeSalaryParams) (Employee, error) {
	row := q.db.QueryRowContext(ctx, updateEmployeeSalary,
		arg.ID,
		arg.BaseSalaryCents,
		arg.CommissionCents,
		arg.LateDeductionRateCents,
		arg.LateDeductionUnit,
		arg.LateUnitsCenti,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.HiredOn,
		&i.BaseSalaryCents,
		&i.CommissionCents,
		&i.LateDeductionRateCents,
		&i.LateDeductionUnit,
		&i.LateUnitsCenti,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
