// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expense.sql

package db

import (
	"context"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
  description,
  amount,
  currency_code
) 
VALUES ( $1, $2, $3 )
RETURNING id, description, amount, currency_code, created_at
`

type CreateExpenseParams struct {
	Description  string `json:"description"`
	Amount       int64  `json:"amount"`
	CurrencyCode string `json:"currency_code"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense, arg.Description, arg.Amount, arg.CurrencyCode)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.CurrencyCode,
		&i.CreatedAt,
	)
	return i, err
}

const getExpense = `-- name: GetExpense :one
SELECT id, description, amount, currency_code, created_at FROM expenses
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetExpense(ctx context.Context, id int64) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getExpense, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.CurrencyCode,
		&i.CreatedAt,
	)
	return i, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, description, amount, currency_code, created_at FROM expenses
WHERE id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListExpensesParams struct {
	ID     int64 `json:"id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpenses, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.CurrencyCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
