// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expense_category.sql

package db

import (
	"context"
)

const createExpenseCategory = `-- name: CreateExpenseCategory :one
INSERT INTO expense_categories (
  name,
  is_active,
  icon,
  color
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, is_active, created_at, icon, color
`

type CreateExpenseCategoryParams struct {
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
	Icon     string `json:"icon"`
	Color    string `json:"color"`
}

func (q *Queries) CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRowContext(ctx, createExpenseCategory,
		arg.Name,
		arg.IsActive,
		arg.Icon,
		arg.Color,
	)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.Icon,
		&i.Color,
	)
	return i, err
}

const deleteExpenseCategory = `-- name: DeleteExpenseCategory :exec
DELETE FROM expense_categories
WHERE id = $1
`

func (q *Queries) DeleteExpenseCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpenseCategory, id)
	return err
}

const getExpenseCategory = `-- name: GetExpenseCategory :one
SELECT id, name, is_active, created_at, icon, color FROM expense_categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetExpenseCategory(ctx context.Context, id int64) (ExpenseCategory, error) {
	row := q.db.QueryRowContext(ctx, getExpenseCategory, id)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.Icon,
		&i.Color,
	)
	return i, err
}

const listExpenseCategories = `-- name: ListExpenseCategories :many
SELECT id, name, is_active, created_at, icon, color FROM expense_categories
ORDER BY id
`

func (q *Queries) ListExpenseCategories(ctx context.Context) ([]ExpenseCategory, error) {
	rows, err := q.db.QueryContext(ctx, listExpenseCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseCategory{}
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.Icon,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpenseCategory = `-- name: UpdateExpenseCategory :one
UPDATE expense_categories
SET name = $2,
    is_active = $3,
    icon = $4,
    color = $5
WHERE id = $1
RETURNING id, name, is_active, created_at, icon, color
`

type UpdateExpenseCategoryParams struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
	Icon     string `json:"icon"`
	Color    string `json:"color"`
}

func (q *Queries) UpdateExpenseCategory(ctx context.Context, arg UpdateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRowContext(ctx, updateExpenseCategory,
		arg.ID,
		arg.Name,
		arg.IsActive,
		arg.Icon,
		arg.Color,
	)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.Icon,
		&i.Color,
	)
	return i, err
}
