// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expense_category.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createExpenseCategory = `-- name: CreateExpenseCategory :one
INSERT INTO expense_categories (
  name,
  is_active,
  icon,
  color,
  scope
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, name, is_active, created_at, icon, color, scope, updated_at
`

type CreateExpenseCategoryParams struct {
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
	Icon     string `json:"icon"`
	Color    string `json:"color"`
	Scope    string `json:"scope"`
}

func (q *Queries) CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRowContext(ctx, createExpenseCategory,
		arg.Name,
		arg.IsActive,
		arg.Icon,
		arg.Color,
		arg.Scope,
	)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.Icon,
		&i.Color,
		&i.Scope,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpenseCategory = `-- name: DeleteExpenseCategory :exec
DELETE FROM expense_categories
WHERE id = $1
`

func (q *Queries) DeleteExpenseCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpenseCategory, id)
	return err
}

const getExpenseCategory = `-- name: GetExpenseCategory :one
SELECT id, name, is_active, created_at, icon, color, scope, updated_at FROM expense_categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetExpenseCategory(ctx context.Context, id int64) (ExpenseCategory, error) {
	row := q.db.QueryRowContext(ctx, getExpenseCategory, id)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.Icon,
		&i.Color,
		&i.Scope,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpenseCategories = `-- name: ListExpenseCategories :many
SELECT id, name, is_active, created_at, icon, color, scope, updated_at FROM expense_categories
WHERE ($1::text IS NULL OR scope = $1)
ORDER BY id
`

func (q *Queries) ListExpenseCategories(ctx context.Context, scope sql.NullString) ([]ExpenseCategory, error) {
	rows, err := q.db.QueryContext(ctx, listExpenseCategories, scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseCategory{}
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.Icon,
			&i.Color,
			&i.Scope,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseCategoriesUpdatedSince = `-- name: ListExpenseCategoriesUpdatedSince :many
SELECT id, name, is_active, created_at, icon, color, scope, updated_at FROM expense_categories
WHERE scope = 'branch' AND updated_at > $1
ORDER BY updated_at
`

// Only branch-scoped categories are synced down to kashi-pos.
func (q *Queries) ListExpenseCategoriesUpdatedSince(ctx context.Context, updatedAt time.Time) ([]ExpenseCategory, error) {
	rows, err := q.db.QueryContext(ctx, listExpenseCategoriesUpdatedSince, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseCategory{}
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.Icon,
			&i.Color,
			&i.Scope,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpenseCategory = `-- name: UpdateExpenseCategory :one
UPDATE expense_categories
SET name = $2,
    is_active = $3,
    icon = $4,
    color = $5,
    scope = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, is_active, created_at, icon, color, scope, updated_at
`

type UpdateExpenseCategoryParams struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
	Icon     string `json:"icon"`
	Color    string `json:"color"`
	Scope    string `json:"scope"`
}

func (q *Queries) UpdateExpenseCategory(ctx context.Context, arg UpdateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRowContext(ctx, updateExpenseCategory,
		arg.ID,
		arg.Name,
		arg.IsActive,
		arg.Icon,
		arg.Color,
		arg.Scope,
	)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.Icon,
		&i.Color,
		&i.Scope,
		&i.UpdatedAt,
	)
	return i, err
}
