// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoice.sql

package db

import (
	"context"
)

const addInvoiceProduct = `-- name: AddInvoiceProduct :one
INSERT INTO invoice_products (
  invoice_id,
  product_id,
  unit_price,
  line_total,
  discount,
  quantity
)
VALUES ( $1, $2, $3, $4, $5, $6 )
RETURNING invoice_id, product_id, unit_price, line_total, discount, quantity
`

type AddInvoiceProductParams struct {
	InvoiceID int64 `json:"invoice_id"`
	ProductID int64 `json:"product_id"`
	UnitPrice int64 `json:"unit_price"`
	LineTotal int64 `json:"line_total"`
	Discount  int16 `json:"discount"`
	Quantity  int64 `json:"quantity"`
}

func (q *Queries) AddInvoiceProduct(ctx context.Context, arg AddInvoiceProductParams) (InvoiceProduct, error) {
	row := q.db.QueryRowContext(ctx, addInvoiceProduct,
		arg.InvoiceID,
		arg.ProductID,
		arg.UnitPrice,
		arg.LineTotal,
		arg.Discount,
		arg.Quantity,
	)
	var i InvoiceProduct
	err := row.Scan(
		&i.InvoiceID,
		&i.ProductID,
		&i.UnitPrice,
		&i.LineTotal,
		&i.Discount,
		&i.Quantity,
	)
	return i, err
}

const countInvoices = `-- name: CountInvoices :one
SELECT COUNT(*) FROM invoices
`

func (q *Queries) CountInvoices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInvoices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
  cashbox_id,
  shift_id,
  invoice_code,
  invoice_index,
  year,
  client_id,
  inventory_id,
  discount,
  subtotal,
  discounted_total,
  grand_total
)
VALUES ( $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, cashbox_id, shift_id, invoice_code, invoice_index, year, client_id, inventory_id, discount, subtotal, discounted_total, grand_total, created_at
`

type CreateInvoiceParams struct {
	CashboxID       int64  `json:"cashbox_id"`
	ShiftID         int64  `json:"shift_id"`
	InvoiceCode     string `json:"invoice_code"`
	InvoiceIndex    int64  `json:"invoice_index"`
	Year            int32  `json:"year"`
	ClientID        int64  `json:"client_id"`
	InventoryID     int64  `json:"inventory_id"`
	Discount        int16  `json:"discount"`
	Subtotal        int64  `json:"subtotal"`
	DiscountedTotal int64  `json:"discounted_total"`
	GrandTotal      int64  `json:"grand_total"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, createInvoice,
		arg.CashboxID,
		arg.ShiftID,
		arg.InvoiceCode,
		arg.InvoiceIndex,
		arg.Year,
		arg.ClientID,
		arg.InventoryID,
		arg.Discount,
		arg.Subtotal,
		arg.DiscountedTotal,
		arg.GrandTotal,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.CashboxID,
		&i.ShiftID,
		&i.InvoiceCode,
		&i.InvoiceIndex,
		&i.Year,
		&i.ClientID,
		&i.InventoryID,
		&i.Discount,
		&i.Subtotal,
		&i.DiscountedTotal,
		&i.GrandTotal,
		&i.CreatedAt,
	)
	return i, err
}

const createReturnInvoice = `-- name: CreateReturnInvoice :one
INSERT INTO return_invoices (invoice_id, sales_invoice_id)
VALUES ($1, $2)
RETURNING invoice_id, sales_invoice_id
`

type CreateReturnInvoiceParams struct {
	InvoiceID      int64 `json:"invoice_id"`
	SalesInvoiceID int64 `json:"sales_invoice_id"`
}

func (q *Queries) CreateReturnInvoice(ctx context.Context, arg CreateReturnInvoiceParams) (ReturnInvoice, error) {
	row := q.db.QueryRowContext(ctx, createReturnInvoice, arg.InvoiceID, arg.SalesInvoiceID)
	var i ReturnInvoice
	err := row.Scan(&i.InvoiceID, &i.SalesInvoiceID)
	return i, err
}

const createSalesInvoice = `-- name: CreateSalesInvoice :one
INSERT INTO sales_invoices (invoice_id)
VALUES ($1)
RETURNING invoice_id
`

func (q *Queries) CreateSalesInvoice(ctx context.Context, invoiceID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSalesInvoice, invoiceID)
	var invoice_id int64
	err := row.Scan(&invoice_id)
	return invoice_id, err
}

const decrementInvoicesIndex = `-- name: DecrementInvoicesIndex :one
INSERT INTO invoice_indexes  (year, cashbox_id, type, last_index)
VALUES ($1, $2, $3, 1)
ON CONFLICT (year, cashbox_id)
DO UPDATE SET last_index = invoice_indexes.last_index - 1
RETURNING last_index
`

type DecrementInvoicesIndexParams struct {
	Year      int32     `json:"year"`
	CashboxID int64     `json:"cashbox_id"`
	Type      IndexType `json:"type"`
}

func (q *Queries) DecrementInvoicesIndex(ctx context.Context, arg DecrementInvoicesIndexParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, decrementInvoicesIndex, arg.Year, arg.CashboxID, arg.Type)
	var last_index int64
	err := row.Scan(&last_index)
	return last_index, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, cashbox_id, shift_id, invoice_code, invoice_index, year, client_id, inventory_id, discount, subtotal, discounted_total, grand_total, created_at FROM invoices
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInvoice(ctx context.Context, id int64) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.CashboxID,
		&i.ShiftID,
		&i.InvoiceCode,
		&i.InvoiceIndex,
		&i.Year,
		&i.ClientID,
		&i.InventoryID,
		&i.Discount,
		&i.Subtotal,
		&i.DiscountedTotal,
		&i.GrandTotal,
		&i.CreatedAt,
	)
	return i, err
}

const getReturnInvoice = `-- name: GetReturnInvoice :one
SELECT invoice_id, sales_invoice_id FROM return_invoices
WHERE invoice_id = $1 LIMIT 1
`

func (q *Queries) GetReturnInvoice(ctx context.Context, invoiceID int64) (ReturnInvoice, error) {
	row := q.db.QueryRowContext(ctx, getReturnInvoice, invoiceID)
	var i ReturnInvoice
	err := row.Scan(&i.InvoiceID, &i.SalesInvoiceID)
	return i, err
}

const getSalesInvoice = `-- name: GetSalesInvoice :one
SELECT invoice_id FROM sales_invoices
WHERE invoice_id = $1 LIMIT 1
`

func (q *Queries) GetSalesInvoice(ctx context.Context, invoiceID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSalesInvoice, invoiceID)
	var invoice_id int64
	err := row.Scan(&invoice_id)
	return invoice_id, err
}

const incrementInvoicesIndex = `-- name: IncrementInvoicesIndex :one
INSERT INTO invoice_indexes  (year, cashbox_id, type, last_index)
VALUES ($1, $2, $3, 1)
ON CONFLICT (year, cashbox_id)
DO UPDATE SET last_index = invoice_indexes.last_index + 1
RETURNING last_index
`

type IncrementInvoicesIndexParams struct {
	Year      int32     `json:"year"`
	CashboxID int64     `json:"cashbox_id"`
	Type      IndexType `json:"type"`
}

func (q *Queries) IncrementInvoicesIndex(ctx context.Context, arg IncrementInvoicesIndexParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, incrementInvoicesIndex, arg.Year, arg.CashboxID, arg.Type)
	var last_index int64
	err := row.Scan(&last_index)
	return last_index, err
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, cashbox_id, shift_id, invoice_code, invoice_index, year, client_id, inventory_id, discount, subtotal, discounted_total, grand_total, created_at
FROM invoices
ORDER BY created_at
DESC
LIMIT $1
OFFSET $2
`

type ListInvoicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.CashboxID,
			&i.ShiftID,
			&i.InvoiceCode,
			&i.InvoiceIndex,
			&i.Year,
			&i.ClientID,
			&i.InventoryID,
			&i.Discount,
			&i.Subtotal,
			&i.DiscountedTotal,
			&i.GrandTotal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
