// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoice_type.sql

package db

import (
	"context"
)

const createInvoiceType = `-- name: CreateInvoiceType :one
INSERT INTO invoice_types (
  name,
  code,
  is_default,
  is_active
)
VALUES ( $1, $2, $3, $4 )
RETURNING id, name, code, is_default, is_active, created_at
`

type CreateInvoiceTypeParams struct {
	Name      string `json:"name"`
	Code      string `json:"code"`
	IsDefault bool   `json:"is_default"`
	IsActive  bool   `json:"is_active"`
}

func (q *Queries) CreateInvoiceType(ctx context.Context, arg CreateInvoiceTypeParams) (InvoiceType, error) {
	row := q.db.QueryRowContext(ctx, createInvoiceType,
		arg.Name,
		arg.Code,
		arg.IsDefault,
		arg.IsActive,
	)
	var i InvoiceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultInvoiceType = `-- name: GetDefaultInvoiceType :one
SELECT id, name, code, is_default, is_active, created_at FROM invoice_types
WHERE is_default = true LIMIT 1
`

func (q *Queries) GetDefaultInvoiceType(ctx context.Context) (InvoiceType, error) {
	row := q.db.QueryRowContext(ctx, getDefaultInvoiceType)
	var i InvoiceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceType = `-- name: GetInvoiceType :one
SELECT id, name, code, is_default, is_active, created_at FROM invoice_types
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInvoiceType(ctx context.Context, id int64) (InvoiceType, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceType, id)
	var i InvoiceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listInvoiceTypes = `-- name: ListInvoiceTypes :many
SELECT id, name, code, is_default, is_active, created_at FROM invoice_types
ORDER BY id
`

func (q *Queries) ListInvoiceTypes(ctx context.Context) ([]InvoiceType, error) {
	rows, err := q.db.QueryContext(ctx, listInvoiceTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceType{}
	for rows.Next() {
		var i InvoiceType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.IsDefault,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceType = `-- name: UpdateInvoiceType :one
UPDATE invoice_types
SET name = $2,
    code = $3,
    is_active = $4
WHERE id = $1
RETURNING id, name, code, is_default, is_active, created_at
`

type UpdateInvoiceTypeParams struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Code     string `json:"code"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) UpdateInvoiceType(ctx context.Context, arg UpdateInvoiceTypeParams) (InvoiceType, error) {
	row := q.db.QueryRowContext(ctx, updateInvoiceType,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.IsActive,
	)
	var i InvoiceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
