// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loan_payment.sql

package db

import (
	"context"
	"database/sql"
)

const countLoanPayments = `-- name: CountLoanPayments :one
SELECT COUNT(*) FROM loan_payments
WHERE ($1::bigint IS NULL OR loan_id = $1)
  AND ($2::bigint IS NULL OR loan_id IN (
    SELECT id FROM loans WHERE category_id = $2
  ))
  AND ($3::text IS NULL OR note ILIKE '%' || $3 || '%')
`

type CountLoanPaymentsParams struct {
	LoanID     sql.NullInt64  `json:"loan_id"`
	CategoryID sql.NullInt64  `json:"category_id"`
	Search     sql.NullString `json:"search"`
}

func (q *Queries) CountLoanPayments(ctx context.Context, arg CountLoanPaymentsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLoanPayments, arg.LoanID, arg.CategoryID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoanPayment = `-- name: CreateLoanPayment :one
INSERT INTO loan_payments (
  loan_id,
  amount,
  currency_code,
  note
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, loan_id, amount, currency_code, note, paid_at
`

type CreateLoanPaymentParams struct {
	LoanID       int64  `json:"loan_id"`
	Amount       int64  `json:"amount"`
	CurrencyCode string `json:"currency_code"`
	Note         string `json:"note"`
}

func (q *Queries) CreateLoanPayment(ctx context.Context, arg CreateLoanPaymentParams) (LoanPayment, error) {
	row := q.db.QueryRowContext(ctx, createLoanPayment,
		arg.LoanID,
		arg.Amount,
		arg.CurrencyCode,
		arg.Note,
	)
	var i LoanPayment
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.Amount,
		&i.CurrencyCode,
		&i.Note,
		&i.PaidAt,
	)
	return i, err
}

const deleteLoanPayment = `-- name: DeleteLoanPayment :exec
DELETE FROM loan_payments
WHERE id = $1
`

func (q *Queries) DeleteLoanPayment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLoanPayment, id)
	return err
}

const getLoanPayment = `-- name: GetLoanPayment :one
SELECT id, loan_id, amount, currency_code, note, paid_at FROM loan_payments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLoanPayment(ctx context.Context, id int64) (LoanPayment, error) {
	row := q.db.QueryRowContext(ctx, getLoanPayment, id)
	var i LoanPayment
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.Amount,
		&i.CurrencyCode,
		&i.Note,
		&i.PaidAt,
	)
	return i, err
}

const listLoanPayments = `-- name: ListLoanPayments :many
SELECT id, loan_id, amount, currency_code, note, paid_at FROM loan_payments
WHERE ($3::bigint IS NULL OR loan_id = $3)
  AND ($4::bigint IS NULL OR loan_id IN (
    SELECT id FROM loans WHERE category_id = $4
  ))
  AND ($5::text IS NULL OR note ILIKE '%' || $5 || '%')
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListLoanPaymentsParams struct {
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
	LoanID     sql.NullInt64  `json:"loan_id"`
	CategoryID sql.NullInt64  `json:"category_id"`
	Search     sql.NullString `json:"search"`
}

// sqlc.narg(loan_id) is nullable: NULL means "all loans". sqlc.narg(category_id)
// filters by the parent loan's lender-source category.
func (q *Queries) ListLoanPayments(ctx context.Context, arg ListLoanPaymentsParams) ([]LoanPayment, error) {
	rows, err := q.db.QueryContext(ctx, listLoanPayments,
		arg.Limit,
		arg.Offset,
		arg.LoanID,
		arg.CategoryID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoanPayment{}
	for rows.Next() {
		var i LoanPayment
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.Amount,
			&i.CurrencyCode,
			&i.Note,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
