// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: low_stock.sql

package db

import (
	"context"
	"database/sql"
)

const countIgnoredLowStockProducts = `-- name: CountIgnoredLowStockProducts :one
SELECT count(*)
FROM products p
WHERE p.is_active
  AND NOT p.low_stock_alerts_enabled
  AND ($1::text = ''
       OR p.name ILIKE '%' || $1 || '%'
       OR p.code ILIKE '%' || $1 || '%')
`

func (q *Queries) CountIgnoredLowStockProducts(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIgnoredLowStockProducts, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLowStockProducts = `-- name: CountLowStockProducts :one
WITH stock AS (
  SELECT pv.product_id, COALESCE(SUM(ist.quantity), 0)::bigint AS on_hand
  FROM product_variants pv
  LEFT JOIN inventory_stock ist ON ist.variant_id = pv.id
  GROUP BY pv.product_id
)
SELECT count(*)
FROM products p
LEFT JOIN stock s ON s.product_id = p.id
CROSS JOIN app_settings a
WHERE p.is_active
  AND p.low_stock_alerts_enabled
  AND COALESCE(s.on_hand, 0) <= COALESCE(p.low_stock_threshold, a.default_low_stock_threshold)
  AND ($1::text IS NULL
       OR ($1::text = 'out_of_stock' AND COALESCE(s.on_hand, 0) <= 0)
       OR ($1::text = 'low_stock' AND COALESCE(s.on_hand, 0) > 0))
  AND ($2::text = ''
       OR p.name ILIKE '%' || $2 || '%'
       OR p.code ILIKE '%' || $2 || '%')
`

type CountLowStockProductsParams struct {
	Status sql.NullString `json:"status"`
	Search string         `json:"search"`
}

func (q *Queries) CountLowStockProducts(ctx context.Context, arg CountLowStockProductsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLowStockProducts, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLowStockSummary = `-- name: GetLowStockSummary :one
WITH stock AS (
  SELECT pv.product_id, COALESCE(SUM(ist.quantity), 0)::bigint AS on_hand
  FROM product_variants pv
  LEFT JOIN inventory_stock ist ON ist.variant_id = pv.id
  GROUP BY pv.product_id
)
SELECT
  count(*) FILTER (
    WHERE COALESCE(s.on_hand, 0) <= COALESCE(p.low_stock_threshold, a.default_low_stock_threshold)
      AND COALESCE(s.on_hand, 0) > 0
  )::bigint AS low_stock_count,
  count(*) FILTER (WHERE COALESCE(s.on_hand, 0) <= 0)::bigint AS out_of_stock_count,
  count(*)::bigint AS total_products
FROM products p
LEFT JOIN stock s ON s.product_id = p.id
CROSS JOIN app_settings a
WHERE p.is_active
  AND p.low_stock_alerts_enabled
`

type GetLowStockSummaryRow struct {
	LowStockCount   int64 `json:"low_stock_count"`
	OutOfStockCount int64 `json:"out_of_stock_count"`
	TotalProducts   int64 `json:"total_products"`
}

// Counts across all active, alert-enabled products, ignoring search --
// backs the summary cards, which should reflect the whole picture even
// while the table below is filtered.
func (q *Queries) GetLowStockSummary(ctx context.Context) (GetLowStockSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getLowStockSummary)
	var i GetLowStockSummaryRow
	err := row.Scan(&i.LowStockCount, &i.OutOfStockCount, &i.TotalProducts)
	return i, err
}

const listIgnoredLowStockProducts = `-- name: ListIgnoredLowStockProducts :many
SELECT
  p.id,
  p.code,
  p.name,
  p.low_stock_threshold,
  COALESCE(s.on_hand, 0)::bigint AS on_hand,
  COALESCE(p.low_stock_threshold, a.default_low_stock_threshold)::bigint AS effective_threshold
FROM products p
LEFT JOIN (
  SELECT pv.product_id, COALESCE(SUM(ist.quantity), 0)::bigint AS on_hand
  FROM product_variants pv
  LEFT JOIN inventory_stock ist ON ist.variant_id = pv.id
  GROUP BY pv.product_id
) s ON s.product_id = p.id
CROSS JOIN app_settings a
WHERE p.is_active
  AND NOT p.low_stock_alerts_enabled
  AND ($1::text = ''
       OR p.name ILIKE '%' || $1 || '%'
       OR p.code ILIKE '%' || $1 || '%')
ORDER BY p.name
LIMIT $3
OFFSET $2
`

type ListIgnoredLowStockProductsParams struct {
	Search     string `json:"search"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type ListIgnoredLowStockProductsRow struct {
	ID                 int64         `json:"id"`
	Code               string        `json:"code"`
	Name               string        `json:"name"`
	LowStockThreshold  sql.NullInt64 `json:"low_stock_threshold"`
	OnHand             int64         `json:"on_hand"`
	EffectiveThreshold int64         `json:"effective_threshold"`
}

// Products that have opted out of low-stock alerting entirely, regardless
// of on-hand or threshold -- lets the muted list be reviewed and reversed.
func (q *Queries) ListIgnoredLowStockProducts(ctx context.Context, arg ListIgnoredLowStockProductsParams) ([]ListIgnoredLowStockProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIgnoredLowStockProducts, arg.Search, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIgnoredLowStockProductsRow{}
	for rows.Next() {
		var i ListIgnoredLowStockProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.LowStockThreshold,
			&i.OnHand,
			&i.EffectiveThreshold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLowStockProducts = `-- name: ListLowStockProducts :many

WITH stock AS (
  SELECT pv.product_id, COALESCE(SUM(ist.quantity), 0)::bigint AS on_hand
  FROM product_variants pv
  LEFT JOIN inventory_stock ist ON ist.variant_id = pv.id
  GROUP BY pv.product_id
)
SELECT
  p.id,
  p.code,
  p.name,
  p.low_stock_threshold,
  COALESCE(s.on_hand, 0)::bigint AS on_hand,
  COALESCE(p.low_stock_threshold, a.default_low_stock_threshold)::bigint AS effective_threshold
FROM products p
LEFT JOIN stock s ON s.product_id = p.id
CROSS JOIN app_settings a
WHERE p.is_active
  AND p.low_stock_alerts_enabled
  AND COALESCE(s.on_hand, 0) <= COALESCE(p.low_stock_threshold, a.default_low_stock_threshold)
  AND ($1::text IS NULL
       OR ($1::text = 'out_of_stock' AND COALESCE(s.on_hand, 0) <= 0)
       OR ($1::text = 'low_stock' AND COALESCE(s.on_hand, 0) > 0))
  AND ($2::text = ''
       OR p.name ILIKE '%' || $2 || '%'
       OR p.code ILIKE '%' || $2 || '%')
ORDER BY on_hand ASC, p.name
LIMIT $4
OFFSET $3
`

type ListLowStockProductsParams struct {
	Status     sql.NullString `json:"status"`
	Search     string         `json:"search"`
	PageOffset int32          `json:"page_offset"`
	PageLimit  int32          `json:"page_limit"`
}

type ListLowStockProductsRow struct {
	ID                 int64         `json:"id"`
	Code               string        `json:"code"`
	Name               string        `json:"name"`
	LowStockThreshold  sql.NullInt64 `json:"low_stock_threshold"`
	OnHand             int64         `json:"on_hand"`
	EffectiveThreshold int64         `json:"effective_threshold"`
}

// Low stock alerts. A product's on-hand is the sum of inventory_stock
// across every SKU (variant) and every inventory it's stocked in; its
// effective threshold is its own override if set, else the single global
// app_settings.default_low_stock_threshold.
// status narrows to one bucket: 'out_of_stock' (on_hand <= 0) or
// 'low_stock' (on_hand > 0, i.e. low but not yet out); NULL keeps both,
// matching the "at or below threshold" definition used everywhere else.
func (q *Queries) ListLowStockProducts(ctx context.Context, arg ListLowStockProductsParams) ([]ListLowStockProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLowStockProducts,
		arg.Status,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLowStockProductsRow{}
	for rows.Next() {
		var i ListLowStockProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.LowStockThreshold,
			&i.OnHand,
			&i.EffectiveThreshold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultLowStockThreshold = `-- name: SetDefaultLowStockThreshold :one
UPDATE app_settings
SET default_low_stock_threshold = $1
WHERE id = 1
RETURNING id, financials_high_season_months, updated_at, activity_message_seconds, activity_display_mode, barcode_label_width, barcode_label_height, upcoming_events_days, upcoming_events_menu_days, hidden_builtin_events, default_low_stock_threshold
`

func (q *Queries) SetDefaultLowStockThreshold(ctx context.Context, defaultLowStockThreshold int64) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, setDefaultLowStockThreshold, defaultLowStockThreshold)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.FinancialsHighSeasonMonths,
		&i.UpdatedAt,
		&i.ActivityMessageSeconds,
		&i.ActivityDisplayMode,
		&i.BarcodeLabelWidth,
		&i.BarcodeLabelHeight,
		&i.UpcomingEventsDays,
		&i.UpcomingEventsMenuDays,
		&i.HiddenBuiltinEvents,
		&i.DefaultLowStockThreshold,
	)
	return i, err
}

const setProductLowStockAlertsEnabled = `-- name: SetProductLowStockAlertsEnabled :exec
UPDATE products
SET low_stock_alerts_enabled = $2
WHERE id = $1
`

type SetProductLowStockAlertsEnabledParams struct {
	ID                    int64 `json:"id"`
	LowStockAlertsEnabled bool  `json:"low_stock_alerts_enabled"`
}

func (q *Queries) SetProductLowStockAlertsEnabled(ctx context.Context, arg SetProductLowStockAlertsEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setProductLowStockAlertsEnabled, arg.ID, arg.LowStockAlertsEnabled)
	return err
}

const updateProductLowStockThreshold = `-- name: UpdateProductLowStockThreshold :exec
UPDATE products
SET low_stock_threshold = $1
WHERE id = $2
`

type UpdateProductLowStockThresholdParams struct {
	LowStockThreshold sql.NullInt64 `json:"low_stock_threshold"`
	ID                int64         `json:"id"`
}

// A null threshold clears the override, falling back to the app-wide default.
func (q *Queries) UpdateProductLowStockThreshold(ctx context.Context, arg UpdateProductLowStockThresholdParams) error {
	_, err := q.db.ExecContext(ctx, updateProductLowStockThreshold, arg.LowStockThreshold, arg.ID)
	return err
}
