// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: price_list.sql

package db

import (
	"context"
	"time"
)

const countPriceListsFiltered = `-- name: CountPriceListsFiltered :one
SELECT COUNT(*) FROM price_lists
WHERE BTRIM($1::text) = ''
   OR name ILIKE '%' || BTRIM($1::text) || '%'
`

func (q *Queries) CountPriceListsFiltered(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPriceListsFiltered, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPriceList = `-- name: CreatePriceList :one
INSERT INTO price_lists (
  name,
  is_active,
  is_default,
  valid_from,
  valid_to
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, name, is_active, is_default, valid_from, valid_to, created_at
`

type CreatePriceListParams struct {
	Name      string    `json:"name"`
	IsActive  bool      `json:"is_active"`
	IsDefault bool      `json:"is_default"`
	ValidFrom time.Time `json:"valid_from"`
	ValidTo   time.Time `json:"valid_to"`
}

func (q *Queries) CreatePriceList(ctx context.Context, arg CreatePriceListParams) (PriceList, error) {
	row := q.db.QueryRowContext(ctx, createPriceList,
		arg.Name,
		arg.IsActive,
		arg.IsDefault,
		arg.ValidFrom,
		arg.ValidTo,
	)
	var i PriceList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.IsDefault,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
	)
	return i, err
}

const deletePriceList = `-- name: DeletePriceList :exec
DELETE FROM price_lists
WHERE id = $1
`

func (q *Queries) DeletePriceList(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePriceList, id)
	return err
}

const getPriceList = `-- name: GetPriceList :one
SELECT id, name, is_active, is_default, valid_from, valid_to, created_at FROM price_lists
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPriceList(ctx context.Context, id int64) (PriceList, error) {
	row := q.db.QueryRowContext(ctx, getPriceList, id)
	var i PriceList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.IsDefault,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
	)
	return i, err
}

const listPriceLists = `-- name: ListPriceLists :many
SELECT id, name, is_active, is_default, valid_from, valid_to, created_at FROM price_lists
WHERE BTRIM($1::text) = ''
   OR name ILIKE '%' || BTRIM($1::text) || '%'
ORDER BY id DESC
LIMIT $3
OFFSET $2
`

type ListPriceListsParams struct {
	Search     string `json:"search"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

func (q *Queries) ListPriceLists(ctx context.Context, arg ListPriceListsParams) ([]PriceList, error) {
	rows, err := q.db.QueryContext(ctx, listPriceLists, arg.Search, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceList{}
	for rows.Next() {
		var i PriceList
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.IsDefault,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsetDefaultPriceList = `-- name: UnsetDefaultPriceList :exec
UPDATE price_lists
SET is_default = false
WHERE is_default = true AND id != $1
`

func (q *Queries) UnsetDefaultPriceList(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unsetDefaultPriceList, id)
	return err
}

const updatePriceList = `-- name: UpdatePriceList :exec
UPDATE price_lists
SET name = $2, is_active = $3, is_default = $4, valid_from = $5, valid_to = $6
WHERE id = $1
`

type UpdatePriceListParams struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	IsActive  bool      `json:"is_active"`
	IsDefault bool      `json:"is_default"`
	ValidFrom time.Time `json:"valid_from"`
	ValidTo   time.Time `json:"valid_to"`
}

func (q *Queries) UpdatePriceList(ctx context.Context, arg UpdatePriceListParams) error {
	_, err := q.db.ExecContext(ctx, updatePriceList,
		arg.ID,
		arg.Name,
		arg.IsActive,
		arg.IsDefault,
		arg.ValidFrom,
		arg.ValidTo,
	)
	return err
}
