// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: price_list_branch.sql

package db

import (
	"context"
)

const deletePriceListBranch = `-- name: DeletePriceListBranch :exec
DELETE FROM price_list_branches
WHERE branch_id = $1
`

func (q *Queries) DeletePriceListBranch(ctx context.Context, branchID int64) error {
	_, err := q.db.ExecContext(ctx, deletePriceListBranch, branchID)
	return err
}

const deletePriceListBranchesForList = `-- name: DeletePriceListBranchesForList :exec
DELETE FROM price_list_branches
WHERE price_list_id = $1
`

func (q *Queries) DeletePriceListBranchesForList(ctx context.Context, priceListID int64) error {
	_, err := q.db.ExecContext(ctx, deletePriceListBranchesForList, priceListID)
	return err
}

const getPriceListBranch = `-- name: GetPriceListBranch :one
SELECT branch_id, price_list_id, created_at FROM price_list_branches
WHERE branch_id = $1 LIMIT 1
`

func (q *Queries) GetPriceListBranch(ctx context.Context, branchID int64) (PriceListBranch, error) {
	row := q.db.QueryRowContext(ctx, getPriceListBranch, branchID)
	var i PriceListBranch
	err := row.Scan(&i.BranchID, &i.PriceListID, &i.CreatedAt)
	return i, err
}

const listBranchesForPriceList = `-- name: ListBranchesForPriceList :many
SELECT b.id, b.name, b.code
FROM price_list_branches plb
JOIN branches b ON b.id = plb.branch_id
WHERE plb.price_list_id = $1
ORDER BY b.name
`

type ListBranchesForPriceListRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Code string `json:"code"`
}

func (q *Queries) ListBranchesForPriceList(ctx context.Context, priceListID int64) ([]ListBranchesForPriceListRow, error) {
	rows, err := q.db.QueryContext(ctx, listBranchesForPriceList, priceListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBranchesForPriceListRow{}
	for rows.Next() {
		var i ListBranchesForPriceListRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceListBranchIDs = `-- name: ListPriceListBranchIDs :many
SELECT branch_id FROM price_list_branches
WHERE price_list_id = $1
ORDER BY branch_id
`

func (q *Queries) ListPriceListBranchIDs(ctx context.Context, priceListID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPriceListBranchIDs, priceListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var branch_id int64
		if err := rows.Scan(&branch_id); err != nil {
			return nil, err
		}
		items = append(items, branch_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPriceListBranch = `-- name: UpsertPriceListBranch :exec
INSERT INTO price_list_branches (branch_id, price_list_id)
VALUES ($1, $2)
ON CONFLICT (branch_id)
DO UPDATE SET price_list_id = EXCLUDED.price_list_id
`

type UpsertPriceListBranchParams struct {
	BranchID    int64 `json:"branch_id"`
	PriceListID int64 `json:"price_list_id"`
}

func (q *Queries) UpsertPriceListBranch(ctx context.Context, arg UpsertPriceListBranchParams) error {
	_, err := q.db.ExecContext(ctx, upsertPriceListBranch, arg.BranchID, arg.PriceListID)
	return err
}
