// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: price_list_item.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const countPriceListItemsWithProduct = `-- name: CountPriceListItemsWithProduct :one
SELECT COUNT(*)
FROM price_list_items pli
JOIN products p ON p.id = pli.product_id
WHERE pli.price_list_id = $1
  AND ($2::text = ''
       OR p.name ILIKE '%' || $2::text || '%'
       OR p.code ILIKE '%' || $2::text || '%')
`

type CountPriceListItemsWithProductParams struct {
	PriceListID int64  `json:"price_list_id"`
	Search      string `json:"search"`
}

func (q *Queries) CountPriceListItemsWithProduct(ctx context.Context, arg CountPriceListItemsWithProductParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPriceListItemsWithProduct, arg.PriceListID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPriceListItem = `-- name: CreatePriceListItem :one
INSERT INTO price_list_items (price_list_id, product_id, price)
VALUES ($1, $2, $3)
ON CONFLICT (price_list_id, product_id)
DO UPDATE SET price = $3
RETURNING price_list_id, product_id, price
`

type CreatePriceListItemParams struct {
	PriceListID int64 `json:"price_list_id"`
	ProductID   int64 `json:"product_id"`
	Price       int64 `json:"price"`
}

func (q *Queries) CreatePriceListItem(ctx context.Context, arg CreatePriceListItemParams) (PriceListItem, error) {
	row := q.db.QueryRowContext(ctx, createPriceListItem, arg.PriceListID, arg.ProductID, arg.Price)
	var i PriceListItem
	err := row.Scan(&i.PriceListID, &i.ProductID, &i.Price)
	return i, err
}

const deletePriceListItem = `-- name: DeletePriceListItem :exec
DELETE FROM price_list_items
WHERE price_list_id = $1 AND product_id = $2
`

type DeletePriceListItemParams struct {
	PriceListID int64 `json:"price_list_id"`
	ProductID   int64 `json:"product_id"`
}

func (q *Queries) DeletePriceListItem(ctx context.Context, arg DeletePriceListItemParams) error {
	_, err := q.db.ExecContext(ctx, deletePriceListItem, arg.PriceListID, arg.ProductID)
	return err
}

const deletePriceListItems = `-- name: DeletePriceListItems :execrows
DELETE FROM price_list_items
WHERE price_list_id = $1 AND product_id = ANY($2::bigint[])
`

type DeletePriceListItemsParams struct {
	PriceListID int64   `json:"price_list_id"`
	ProductIds  []int64 `json:"product_ids"`
}

func (q *Queries) DeletePriceListItems(ctx context.Context, arg DeletePriceListItemsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePriceListItems, arg.PriceListID, pq.Array(arg.ProductIds))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDefaultPriceForProduct = `-- name: GetDefaultPriceForProduct :one
SELECT pli.price FROM price_list_items pli
JOIN price_lists pl ON pl.id = pli.price_list_id
WHERE pli.product_id = $1
AND pl.is_active = true AND pl.is_default = true
AND now() >= pl.valid_from AND now() <= pl.valid_to
LIMIT 1
`

func (q *Queries) GetDefaultPriceForProduct(ctx context.Context, productID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDefaultPriceForProduct, productID)
	var price int64
	err := row.Scan(&price)
	return price, err
}

const getProductPriceFromList = `-- name: GetProductPriceFromList :one
SELECT price_list_id, product_id, price FROM price_list_items
WHERE price_list_id = $1 AND product_id = $2
`

type GetProductPriceFromListParams struct {
	PriceListID int64 `json:"price_list_id"`
	ProductID   int64 `json:"product_id"`
}

func (q *Queries) GetProductPriceFromList(ctx context.Context, arg GetProductPriceFromListParams) (PriceListItem, error) {
	row := q.db.QueryRowContext(ctx, getProductPriceFromList, arg.PriceListID, arg.ProductID)
	var i PriceListItem
	err := row.Scan(&i.PriceListID, &i.ProductID, &i.Price)
	return i, err
}

const listPriceListItems = `-- name: ListPriceListItems :many
SELECT price_list_id, product_id, price FROM price_list_items
WHERE price_list_id = $1
ORDER BY product_id
`

func (q *Queries) ListPriceListItems(ctx context.Context, priceListID int64) ([]PriceListItem, error) {
	rows, err := q.db.QueryContext(ctx, listPriceListItems, priceListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceListItem{}
	for rows.Next() {
		var i PriceListItem
		if err := rows.Scan(&i.PriceListID, &i.ProductID, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceListItemsWithProduct = `-- name: ListPriceListItemsWithProduct :many
SELECT pli.price_list_id, pli.product_id, pli.price,
       p.code AS product_code, p.name AS product_name
FROM price_list_items pli
JOIN products p ON p.id = pli.product_id
WHERE pli.price_list_id = $1
  AND ($2::text = ''
       OR p.name ILIKE '%' || $2::text || '%'
       OR p.code ILIKE '%' || $2::text || '%')
ORDER BY p.name, pli.product_id
LIMIT $4
OFFSET $3
`

type ListPriceListItemsWithProductParams struct {
	PriceListID int64  `json:"price_list_id"`
	Search      string `json:"search"`
	PageOffset  int32  `json:"page_offset"`
	PageSize    int32  `json:"page_size"`
}

type ListPriceListItemsWithProductRow struct {
	PriceListID int64  `json:"price_list_id"`
	ProductID   int64  `json:"product_id"`
	Price       int64  `json:"price"`
	ProductCode string `json:"product_code"`
	ProductName string `json:"product_name"`
}

func (q *Queries) ListPriceListItemsWithProduct(ctx context.Context, arg ListPriceListItemsWithProductParams) ([]ListPriceListItemsWithProductRow, error) {
	rows, err := q.db.QueryContext(ctx, listPriceListItemsWithProduct,
		arg.PriceListID,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPriceListItemsWithProductRow{}
	for rows.Next() {
		var i ListPriceListItemsWithProductRow
		if err := rows.Scan(
			&i.PriceListID,
			&i.ProductID,
			&i.Price,
			&i.ProductCode,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePriceListItem = `-- name: UpdatePriceListItem :exec
UPDATE price_list_items
SET price = $3
WHERE price_list_id = $1 AND product_id = $2
`

type UpdatePriceListItemParams struct {
	PriceListID int64 `json:"price_list_id"`
	ProductID   int64 `json:"product_id"`
	Price       int64 `json:"price"`
}

func (q *Queries) UpdatePriceListItem(ctx context.Context, arg UpdatePriceListItemParams) error {
	_, err := q.db.ExecContext(ctx, updatePriceListItem, arg.PriceListID, arg.ProductID, arg.Price)
	return err
}
