// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*)
FROM products p
WHERE ($1::text = ''
       OR p.code ILIKE '%' || $1 || '%'
       OR p.name ILIKE '%' || $1 || '%'
       OR p.description ILIKE '%' || $1 || '%')
  AND ($2::bool IS NULL OR p.is_active = $2)
  AND ($3::timestamptz IS NULL OR p.created_at >= $3)
  AND ($4::timestamptz IS NULL OR p.created_at < $4)
  AND ($5::bool IS NULL
       OR EXISTS (SELECT 1 FROM product_variants v WHERE v.product_id = p.id) = $5)
  AND (cardinality($6::bigint[]) = 0
       OR (SELECT count(DISTINCT pa.attribute_value_id)
             FROM products_attributes pa
            WHERE pa.product_id = p.id
              AND pa.attribute_value_id = ANY($6::bigint[]))
           = cardinality($6::bigint[]))
`

type CountProductsParams struct {
	Search            string       `json:"search"`
	IsActive          sql.NullBool `json:"is_active"`
	CreatedFrom       sql.NullTime `json:"created_from"`
	CreatedTo         sql.NullTime `json:"created_to"`
	HasVariants       sql.NullBool `json:"has_variants"`
	AttributeValueIds []int64      `json:"attribute_value_ids"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProducts,
		arg.Search,
		arg.IsActive,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.HasVariants,
		pq.Array(arg.AttributeValueIds),
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  code,
  name,
  description
) VALUES (
    $1, $2, $3
) RETURNING id, code, name, description, is_active, created_at
`

type CreateProductParams struct {
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.Code, arg.Name, arg.Description)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, code, name, description, is_active, created_at FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.code, p.name, p.description, p.is_active, p.created_at
FROM products p
WHERE ($1::text = ''
       OR p.code ILIKE '%' || $1 || '%'
       OR p.name ILIKE '%' || $1 || '%'
       OR p.description ILIKE '%' || $1 || '%')
  AND ($2::bool IS NULL OR p.is_active = $2)
  AND ($3::timestamptz IS NULL OR p.created_at >= $3)
  AND ($4::timestamptz IS NULL OR p.created_at < $4)
  AND ($5::bool IS NULL
       OR EXISTS (SELECT 1 FROM product_variants v WHERE v.product_id = p.id) = $5)
  AND (cardinality($6::bigint[]) = 0
       OR (SELECT count(DISTINCT pa.attribute_value_id)
             FROM products_attributes pa
            WHERE pa.product_id = p.id
              AND pa.attribute_value_id = ANY($6::bigint[]))
           = cardinality($6::bigint[]))
ORDER BY p.id
LIMIT $8 OFFSET $7
`

type ListProductsParams struct {
	Search            string       `json:"search"`
	IsActive          sql.NullBool `json:"is_active"`
	CreatedFrom       sql.NullTime `json:"created_from"`
	CreatedTo         sql.NullTime `json:"created_to"`
	HasVariants       sql.NullBool `json:"has_variants"`
	AttributeValueIds []int64      `json:"attribute_value_ids"`
	PageOffset        int32        `json:"page_offset"`
	PageLimit         int32        `json:"page_limit"`
}

// Search matches code/name/description (case-insensitive). Every filter is
// optional: empty search string, NULL narg, or empty attribute_value_ids
// array all mean "don't filter on this". attribute_value_ids is an AND --
// the product must carry every selected value.
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts,
		arg.Search,
		arg.IsActive,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.HasVariants,
		pq.Array(arg.AttributeValueIds),
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
  SET name = $2,
  code = $3,
  description = $4,
  is_active = $5
WHERE id = $1
`

type UpdateProductParams struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description"`
	IsActive    bool   `json:"is_active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.IsActive,
	)
	return err
}

const upsertProductAttribute = `-- name: UpsertProductAttribute :exec
INSERT INTO products_attributes (attribute_id, product_id, attribute_value_id)
VALUES ($1, $2, $3)
ON CONFLICT (attribute_id, product_id)
DO UPDATE SET attribute_value_id = EXCLUDED.attribute_value_id
`

type UpsertProductAttributeParams struct {
	AttributeID      int64 `json:"attribute_id"`
	ProductID        int64 `json:"product_id"`
	AttributeValueID int64 `json:"attribute_value_id"`
}

func (q *Queries) UpsertProductAttribute(ctx context.Context, arg UpsertProductAttributeParams) error {
	_, err := q.db.ExecContext(ctx, upsertProductAttribute, arg.AttributeID, arg.ProductID, arg.AttributeValueID)
	return err
}
