// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_variants.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countProductVariants = `-- name: CountProductVariants :one
SELECT COUNT(*) FROM product_variants
`

func (q *Queries) CountProductVariants(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductVariants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVariantsForBarcodes = `-- name: CountVariantsForBarcodes :one
SELECT COUNT(*)
FROM product_variants pv
JOIN products p ON p.id = pv.product_id
WHERE ($1::text = ''
       OR p.name ILIKE '%' || $1 || '%'
       OR p.code ILIKE '%' || $1 || '%'
       OR pv.barcode ILIKE '%' || $1 || '%')
`

func (q *Queries) CountVariantsForBarcodes(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVariantsForBarcodes, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variants (
  product_id,
  color_id,
  size_id,
  barcode,
  price
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, product_id, color_id, size_id, barcode, price, is_active, created_at, updated_at, avg_cost
`

type CreateProductVariantParams struct {
	ProductID int64         `json:"product_id"`
	ColorID   sql.NullInt64 `json:"color_id"`
	SizeID    sql.NullInt64 `json:"size_id"`
	Barcode   string        `json:"barcode"`
	Price     sql.NullInt64 `json:"price"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, createProductVariant,
		arg.ProductID,
		arg.ColorID,
		arg.SizeID,
		arg.Barcode,
		arg.Price,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ColorID,
		&i.SizeID,
		&i.Barcode,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvgCost,
	)
	return i, err
}

const deleteProductVariant = `-- name: DeleteProductVariant :exec
DELETE FROM product_variants
WHERE id = $1
`

func (q *Queries) DeleteProductVariant(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProductVariant, id)
	return err
}

const getProductVariant = `-- name: GetProductVariant :one
SELECT id, product_id, color_id, size_id, barcode, price, is_active, created_at, updated_at, avg_cost FROM product_variants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductVariant(ctx context.Context, id int64) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, getProductVariant, id)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ColorID,
		&i.SizeID,
		&i.Barcode,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvgCost,
	)
	return i, err
}

const getProductVariantByBarcode = `-- name: GetProductVariantByBarcode :one
SELECT id, product_id, color_id, size_id, barcode, price, is_active, created_at, updated_at, avg_cost FROM product_variants
WHERE barcode = $1 LIMIT 1
`

func (q *Queries) GetProductVariantByBarcode(ctx context.Context, barcode string) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, getProductVariantByBarcode, barcode)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ColorID,
		&i.SizeID,
		&i.Barcode,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvgCost,
	)
	return i, err
}

const getVariantForLabel = `-- name: GetVariantForLabel :one
SELECT
  pv.id,
  pv.barcode,
  pv.price,
  p.code AS product_code,
  p.name AS product_name,
  COALESCE(c.name, '')  AS color_name,
  COALESCE(s.name, '')  AS size_name,
  COALESCE(brand_val.value, '') AS brand
FROM product_variants pv
JOIN products p ON p.id = pv.product_id
LEFT JOIN colors c ON c.id = pv.color_id
LEFT JOIN sizes  s ON s.id = pv.size_id
LEFT JOIN products_attributes brand_pa ON brand_pa.product_id = p.id AND brand_pa.attribute_id = 2
LEFT JOIN attributes_values brand_val ON brand_val.id = brand_pa.attribute_value_id
WHERE pv.id = $1
`

type GetVariantForLabelRow struct {
	ID          int64         `json:"id"`
	Barcode     string        `json:"barcode"`
	Price       sql.NullInt64 `json:"price"`
	ProductCode string        `json:"product_code"`
	ProductName string        `json:"product_name"`
	ColorName   string        `json:"color_name"`
	SizeName    string        `json:"size_name"`
	Brand       string        `json:"brand"`
}

func (q *Queries) GetVariantForLabel(ctx context.Context, id int64) (GetVariantForLabelRow, error) {
	row := q.db.QueryRowContext(ctx, getVariantForLabel, id)
	var i GetVariantForLabelRow
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.Price,
		&i.ProductCode,
		&i.ProductName,
		&i.ColorName,
		&i.SizeName,
		&i.Brand,
	)
	return i, err
}

const getVariantTotalOnHand = `-- name: GetVariantTotalOnHand :one
SELECT COALESCE(SUM(quantity), 0)::bigint AS total
FROM inventory_stock
WHERE variant_id = $1
`

func (q *Queries) GetVariantTotalOnHand(ctx context.Context, variantID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVariantTotalOnHand, variantID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const listProductVariants = `-- name: ListProductVariants :many
SELECT product_variants.id, product_variants.product_id, product_variants.color_id, product_variants.size_id, product_variants.barcode, product_variants.price, product_variants.is_active, product_variants.created_at, product_variants.updated_at, product_variants.avg_cost, products.id, products.code, products.name, products.description, products.is_active, products.created_at FROM product_variants
INNER JOIN products ON products.id = product_variants.product_id
ORDER BY product_variants.id
LIMIT $1
OFFSET $2
`

type ListProductVariantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductVariantsRow struct {
	ProductVariant ProductVariant `json:"product_variant"`
	Product        Product        `json:"product"`
}

func (q *Queries) ListProductVariants(ctx context.Context, arg ListProductVariantsParams) ([]ListProductVariantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductVariants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductVariantsRow{}
	for rows.Next() {
		var i ListProductVariantsRow
		if err := rows.Scan(
			&i.ProductVariant.ID,
			&i.ProductVariant.ProductID,
			&i.ProductVariant.ColorID,
			&i.ProductVariant.SizeID,
			&i.ProductVariant.Barcode,
			&i.ProductVariant.Price,
			&i.ProductVariant.IsActive,
			&i.ProductVariant.CreatedAt,
			&i.ProductVariant.UpdatedAt,
			&i.ProductVariant.AvgCost,
			&i.Product.ID,
			&i.Product.Code,
			&i.Product.Name,
			&i.Product.Description,
			&i.Product.IsActive,
			&i.Product.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariantsByProduct = `-- name: ListProductVariantsByProduct :many
SELECT id, product_id, color_id, size_id, barcode, price, is_active, created_at, updated_at, avg_cost FROM product_variants
WHERE product_id = $1
ORDER BY id
`

func (q *Queries) ListProductVariantsByProduct(ctx context.Context, productID int64) ([]ProductVariant, error) {
	rows, err := q.db.QueryContext(ctx, listProductVariantsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ColorID,
			&i.SizeID,
			&i.Barcode,
			&i.Price,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvgCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariantsForSync = `-- name: ListProductVariantsForSync :many
SELECT
  product_variants.id,
  product_variants.barcode,
  product_variants.price,
  product_variants.is_active,
  product_variants.updated_at,
  products.code,
  products.name,
  products.description,
  colors.name AS color_name,
  sizes.name AS size_name,
  brand_val.value AS brand,
  subcategory_val.value AS sub_category,
  kind_val.value AS kind,
  season_val.value AS season,
  year_val.value AS year
FROM product_variants
JOIN products ON products.id = product_variants.product_id
LEFT JOIN colors ON colors.id = product_variants.color_id
LEFT JOIN sizes ON sizes.id = product_variants.size_id
LEFT JOIN products_attributes brand_pa ON brand_pa.product_id = products.id AND brand_pa.attribute_id = 2
LEFT JOIN attributes_values brand_val ON brand_val.id = brand_pa.attribute_value_id
LEFT JOIN products_attributes subcategory_pa ON subcategory_pa.product_id = products.id AND subcategory_pa.attribute_id = 1
LEFT JOIN attributes_values subcategory_val ON subcategory_val.id = subcategory_pa.attribute_value_id
LEFT JOIN products_attributes kind_pa ON kind_pa.product_id = products.id AND kind_pa.attribute_id = 3
LEFT JOIN attributes_values kind_val ON kind_val.id = kind_pa.attribute_value_id
LEFT JOIN products_attributes season_pa ON season_pa.product_id = products.id AND season_pa.attribute_id = 7
LEFT JOIN attributes_values season_val ON season_val.id = season_pa.attribute_value_id
LEFT JOIN products_attributes year_pa ON year_pa.product_id = products.id AND year_pa.attribute_id = 6
LEFT JOIN attributes_values year_val ON year_val.id = year_pa.attribute_value_id
WHERE product_variants.updated_at > $1
ORDER BY product_variants.updated_at
`

type ListProductVariantsForSyncRow struct {
	ID          int64          `json:"id"`
	Barcode     string         `json:"barcode"`
	Price       sql.NullInt64  `json:"price"`
	IsActive    bool           `json:"is_active"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	ColorName   sql.NullString `json:"color_name"`
	SizeName    sql.NullString `json:"size_name"`
	Brand       sql.NullString `json:"brand"`
	SubCategory sql.NullString `json:"sub_category"`
	Kind        sql.NullString `json:"kind"`
	Season      sql.NullString `json:"season"`
	Year        sql.NullString `json:"year"`
}

// Flattened for kashi-pos, which has no separate "product" row -- each
// variant carries everything a branch needs to create or update its own
// flat product row. Colors/sizes/attributes are resolved to their name
// here (not sent as ids) since kashi-pos matches everything by name, not
// by kashi's internal ids.
//
// Attribute ids (2=brand, 1=sub-category, 3=kind, 7=season, 6=year) match
// the fixed seed in 000005_create_products_attributes_table.up.sql.
// Editing a product's attributes doesn't currently bump
// product_variants.updated_at (no endpoint does that edit yet -- see
// api/product.go), so an attribute-only change wouldn't be picked up by
// this filter if one ever existed; today attributes are only ever set at
// creation time, in the same moment the variant's own updated_at is set,
// so this doesn't miss anything in practice yet.
func (q *Queries) ListProductVariantsForSync(ctx context.Context, updatedAt time.Time) ([]ListProductVariantsForSyncRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductVariantsForSync, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductVariantsForSyncRow{}
	for rows.Next() {
		var i ListProductVariantsForSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.Barcode,
			&i.Price,
			&i.IsActive,
			&i.UpdatedAt,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.ColorName,
			&i.SizeName,
			&i.Brand,
			&i.SubCategory,
			&i.Kind,
			&i.Season,
			&i.Year,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariantsUpdatedSince = `-- name: ListProductVariantsUpdatedSince :many
SELECT id, product_id, color_id, size_id, barcode, price, is_active, created_at, updated_at, avg_cost FROM product_variants
WHERE updated_at > $1
ORDER BY updated_at
`

func (q *Queries) ListProductVariantsUpdatedSince(ctx context.Context, updatedAt time.Time) ([]ProductVariant, error) {
	rows, err := q.db.QueryContext(ctx, listProductVariantsUpdatedSince, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ColorID,
			&i.SizeID,
			&i.Barcode,
			&i.Price,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvgCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsForBarcodes = `-- name: ListVariantsForBarcodes :many
SELECT
  pv.id,
  pv.barcode,
  pv.price,
  pv.is_active,
  pv.created_at,
  p.id   AS product_id,
  p.code AS product_code,
  p.name AS product_name,
  COALESCE(c.name, '')  AS color_name,
  COALESCE(s.type, '')  AS size_type,
  COALESCE(s.name, '')  AS size_name,
  COALESCE(brand_val.value, '') AS brand
FROM product_variants pv
JOIN products p ON p.id = pv.product_id
LEFT JOIN colors c ON c.id = pv.color_id
LEFT JOIN sizes  s ON s.id = pv.size_id
LEFT JOIN products_attributes brand_pa ON brand_pa.product_id = p.id AND brand_pa.attribute_id = 2
LEFT JOIN attributes_values brand_val ON brand_val.id = brand_pa.attribute_value_id
WHERE ($1::text = ''
       OR p.name ILIKE '%' || $1 || '%'
       OR p.code ILIKE '%' || $1 || '%'
       OR pv.barcode ILIKE '%' || $1 || '%')
ORDER BY pv.id DESC
LIMIT $3
OFFSET $2
`

type ListVariantsForBarcodesParams struct {
	Search     string `json:"search"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type ListVariantsForBarcodesRow struct {
	ID          int64         `json:"id"`
	Barcode     string        `json:"barcode"`
	Price       sql.NullInt64 `json:"price"`
	IsActive    bool          `json:"is_active"`
	CreatedAt   time.Time     `json:"created_at"`
	ProductID   int64         `json:"product_id"`
	ProductCode string        `json:"product_code"`
	ProductName string        `json:"product_name"`
	ColorName   string        `json:"color_name"`
	SizeType    string        `json:"size_type"`
	SizeName    string        `json:"size_name"`
	Brand       string        `json:"brand"`
}

func (q *Queries) ListVariantsForBarcodes(ctx context.Context, arg ListVariantsForBarcodesParams) ([]ListVariantsForBarcodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listVariantsForBarcodes, arg.Search, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariantsForBarcodesRow{}
	for rows.Next() {
		var i ListVariantsForBarcodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Barcode,
			&i.Price,
			&i.IsActive,
			&i.CreatedAt,
			&i.ProductID,
			&i.ProductCode,
			&i.ProductName,
			&i.ColorName,
			&i.SizeType,
			&i.SizeName,
			&i.Brand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVariantBarcode = `-- name: SetVariantBarcode :one
UPDATE product_variants
SET barcode = $2, updated_at = now()
WHERE id = $1
RETURNING id, product_id, color_id, size_id, barcode, price, is_active, created_at, updated_at, avg_cost
`

type SetVariantBarcodeParams struct {
	ID      int64  `json:"id"`
	Barcode string `json:"barcode"`
}

func (q *Queries) SetVariantBarcode(ctx context.Context, arg SetVariantBarcodeParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, setVariantBarcode, arg.ID, arg.Barcode)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ColorID,
		&i.SizeID,
		&i.Barcode,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvgCost,
	)
	return i, err
}

const updateProductVariant = `-- name: UpdateProductVariant :one
UPDATE product_variants
SET color_id = $2,
size_id = $3,
barcode = $4,
price = $5,
is_active = $6,
updated_at = now()
WHERE id = $1
RETURNING id, product_id, color_id, size_id, barcode, price, is_active, created_at, updated_at, avg_cost
`

type UpdateProductVariantParams struct {
	ID       int64         `json:"id"`
	ColorID  sql.NullInt64 `json:"color_id"`
	SizeID   sql.NullInt64 `json:"size_id"`
	Barcode  string        `json:"barcode"`
	Price    sql.NullInt64 `json:"price"`
	IsActive bool          `json:"is_active"`
}

func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, updateProductVariant,
		arg.ID,
		arg.ColorID,
		arg.SizeID,
		arg.Barcode,
		arg.Price,
		arg.IsActive,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ColorID,
		&i.SizeID,
		&i.Barcode,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvgCost,
	)
	return i, err
}

const updateProductVariantAvgCost = `-- name: UpdateProductVariantAvgCost :exec
UPDATE product_variants
SET avg_cost = CASE
    WHEN $1::bigint <= 0 THEN $2
    ELSE ($1::bigint * avg_cost
          + $3::bigint * $2)
         / NULLIF($1::bigint + $3::bigint, 0)
  END,
  updated_at = now()
WHERE id = $4
`

type UpdateProductVariantAvgCostParams struct {
	CurrentQty int64 `json:"current_qty"`
	UnitCost   int64 `json:"unit_cost"`
	InQty      int64 `json:"in_qty"`
	ID         int64 `json:"id"`
}

// Roll the variant's global moving-average cost forward on a stock receipt.
// current_qty is the on-hand across all locations before this receipt.
func (q *Queries) UpdateProductVariantAvgCost(ctx context.Context, arg UpdateProductVariantAvgCostParams) error {
	_, err := q.db.ExecContext(ctx, updateProductVariantAvgCost,
		arg.CurrentQty,
		arg.UnitCost,
		arg.InQty,
		arg.ID,
	)
	return err
}
