// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_variants.sql

package db

import (
	"context"
)

const createProductColor = `-- name: CreateProductColor :one
INSERT INTO products_colors (
  product_id,
  color_id
) VALUES (
    $1, $2
) RETURNING product_id, color_id
`

type CreateProductColorParams struct {
	ProductID int64 `json:"product_id"`
	ColorID   int64 `json:"color_id"`
}

func (q *Queries) CreateProductColor(ctx context.Context, arg CreateProductColorParams) (ProductsColor, error) {
	row := q.db.QueryRowContext(ctx, createProductColor, arg.ProductID, arg.ColorID)
	var i ProductsColor
	err := row.Scan(&i.ProductID, &i.ColorID)
	return i, err
}

const createProductSize = `-- name: CreateProductSize :one
INSERT INTO products_sizes (
  product_id,
  size_id
) VALUES (
    $1, $2
) RETURNING product_id, size_id
`

type CreateProductSizeParams struct {
	ProductID int64 `json:"product_id"`
	SizeID    int64 `json:"size_id"`
}

func (q *Queries) CreateProductSize(ctx context.Context, arg CreateProductSizeParams) (ProductsSize, error) {
	row := q.db.QueryRowContext(ctx, createProductSize, arg.ProductID, arg.SizeID)
	var i ProductsSize
	err := row.Scan(&i.ProductID, &i.SizeID)
	return i, err
}
