// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AddCashboxAccountBalance(ctx context.Context, arg AddCashboxAccountBalanceParams) (ShiftsAccountsBalance, error)
	AddClientLoyaltyPoints(ctx context.Context, arg AddClientLoyaltyPointsParams) error
	AddInventoryProduct(ctx context.Context, arg AddInventoryProductParams) (InventoriesProduct, error)
	AddInventoryProductQuantity(ctx context.Context, arg AddInventoryProductQuantityParams) error
	AddInvoiceProduct(ctx context.Context, arg AddInvoiceProductParams) (InvoiceProduct, error)
	AddPurchaseItem(ctx context.Context, arg AddPurchaseItemParams) (PurchaseItem, error)
	AddPurchasedProduct(ctx context.Context, arg AddPurchasedProductParams) (ProductSupplier, error)
	AddPurchasedProductCost(ctx context.Context, arg AddPurchasedProductCostParams) (ProductSupplierCost, error)
	CloseShift(ctx context.Context, id int64) error
	CompleteBranchCommand(ctx context.Context, arg CompleteBranchCommandParams) (BranchCommand, error)
	CountBranchExpenses(ctx context.Context, branchID sql.NullInt64) (int64, error)
	CountBranchInvoices(ctx context.Context, branchID sql.NullInt64) (int64, error)
	CountClients(ctx context.Context, clientType sql.NullString) (int64, error)
	CountCoupons(ctx context.Context) (int64, error)
	CountCurrencies(ctx context.Context) (int64, error)
	CountDiscountLists(ctx context.Context) (int64, error)
	CountInventories(ctx context.Context) (int64, error)
	CountInvoices(ctx context.Context) (int64, error)
	CountLoanPayments(ctx context.Context, loanID sql.NullInt64) (int64, error)
	CountLoans(ctx context.Context, arg CountLoansParams) (int64, error)
	CountProductVariants(ctx context.Context) (int64, error)
	CountProducts(ctx context.Context) (int64, error)
	CountPurchases(ctx context.Context) (int64, error)
	CountShifts(ctx context.Context) (int64, error)
	CountSuppliers(ctx context.Context) (int64, error)
	CountTransfers(ctx context.Context) (int64, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateAssetType(ctx context.Context, type_ string) (AssetsType, error)
	CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error)
	CreateBranchCommand(ctx context.Context, arg CreateBranchCommandParams) (BranchCommand, error)
	CreateBranchExpense(ctx context.Context, arg CreateBranchExpenseParams) (BranchExpense, error)
	CreateBranchInvoice(ctx context.Context, arg CreateBranchInvoiceParams) (BranchInvoice, error)
	CreateBranchInvoiceItem(ctx context.Context, arg CreateBranchInvoiceItemParams) (BranchInvoiceItem, error)
	CreateBranchLoan(ctx context.Context, arg CreateBranchLoanParams) (Loan, error)
	CreateBranchSalesperson(ctx context.Context, arg CreateBranchSalespersonParams) (Salesperson, error)
	CreateBranchTarget(ctx context.Context, arg CreateBranchTargetParams) (BranchTarget, error)
	CreateBranchTargetSeries(ctx context.Context, arg CreateBranchTargetSeriesParams) (BranchTargetSeries, error)
	CreateCashbox(ctx context.Context, arg CreateCashboxParams) (Cashbox, error)
	CreateCashboxAccount(ctx context.Context, arg CreateCashboxAccountParams) (CashboxAccount, error)
	CreateCentralLoan(ctx context.Context, arg CreateCentralLoanParams) (Loan, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateColor(ctx context.Context, arg CreateColorParams) (Color, error)
	CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error)
	CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error)
	CreateDiscountList(ctx context.Context, arg CreateDiscountListParams) (DiscountList, error)
	CreateDiscountListItem(ctx context.Context, arg CreateDiscountListItemParams) (DiscountListItem, error)
	CreateEntryItem(ctx context.Context, arg CreateEntryItemParams) (Entry, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error)
	// Fires one period for a recurring series -- target_amount/color are
	// passed in (a snapshot of the series at generation time) rather than
	// joined live, so a later edit to the series template never rewrites a
	// period that's already in progress or past, same as recurring_expenses'
	// FireRecurringExpenseTx snapshotting its template's amount into the
	// created expense row.
	CreateGeneratedBranchTarget(ctx context.Context, arg CreateGeneratedBranchTargetParams) (BranchTarget, error)
	CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateInvoiceType(ctx context.Context, arg CreateInvoiceTypeParams) (InvoiceType, error)
	CreateLoanCategory(ctx context.Context, arg CreateLoanCategoryParams) (LoanCategory, error)
	CreateLoanPayment(ctx context.Context, arg CreateLoanPaymentParams) (LoanPayment, error)
	CreatePriceList(ctx context.Context, arg CreatePriceListParams) (PriceList, error)
	CreatePriceListItem(ctx context.Context, arg CreatePriceListItemParams) (PriceListItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductAttribute(ctx context.Context, arg CreateProductAttributeParams) (ProductsAttribute, error)
	CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error)
	CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error)
	CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) (RecurringExpense, error)
	CreateReturnInvoice(ctx context.Context, arg CreateReturnInvoiceParams) (ReturnInvoice, error)
	CreateSalesInvoice(ctx context.Context, invoiceID int64) (int64, error)
	CreateSalesperson(ctx context.Context, arg CreateSalespersonParams) (Salesperson, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShift(ctx context.Context, cashboxID int64) (Shift, error)
	CreateSize(ctx context.Context, arg CreateSizeParams) (Size, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateTransferItem(ctx context.Context, arg CreateTransferItemParams) (TransferItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Part of deleting a whole recurring series (see DeleteBranchTargetSeriesTx
	// in tx_branch_target_series.go) -- every period it ever generated needs
	// to disappear the same way a single deleted target does, not just stop
	// getting new ones.
	DeactivateBranchTargetsBySeries(ctx context.Context, seriesID sql.NullInt64) error
	DeactivateCoupon(ctx context.Context, code string) error
	DecrementInvoicesIndex(ctx context.Context, arg DecrementInvoicesIndexParams) (int64, error)
	DeleteAsset(ctx context.Context, id int64) error
	DeleteAssetType(ctx context.Context, id int64) error
	DeleteBranchTargetSeries(ctx context.Context, id int64) (BranchTargetSeries, error)
	DeleteClient(ctx context.Context, id int64) error
	DeleteCurrency(ctx context.Context, code string) error
	DeleteDiscountListItem(ctx context.Context, arg DeleteDiscountListItemParams) error
	DeleteExpenseCategory(ctx context.Context, id int64) error
	DeleteInventory(ctx context.Context, id int64) error
	DeleteInventoryProduct(ctx context.Context, arg DeleteInventoryProductParams) error
	DeleteLoanCategory(ctx context.Context, id int64) error
	DeleteLoanPayment(ctx context.Context, id int64) error
	DeletePriceListItem(ctx context.Context, arg DeletePriceListItemParams) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteSalesperson(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetAsset(ctx context.Context, id int64) (Asset, error)
	GetAttribute(ctx context.Context, name string) (Attribute, error)
	// upserting instead of inserting makes product creation with attributes easier
	GetAttributeValue(ctx context.Context, id int64) (AttributesValue, error)
	GetBranch(ctx context.Context, id int64) (Branch, error)
	GetBranchByCode(ctx context.Context, code string) (Branch, error)
	GetBranchCommand(ctx context.Context, id int64) (BranchCommand, error)
	GetBranchExpenseByClientRef(ctx context.Context, arg GetBranchExpenseByClientRefParams) (BranchExpense, error)
	GetBranchInvoice(ctx context.Context, id int64) (BranchInvoice, error)
	GetBranchInvoiceByClientRef(ctx context.Context, arg GetBranchInvoiceByClientRefParams) (BranchInvoice, error)
	GetBranchLoanByClientRef(ctx context.Context, arg GetBranchLoanByClientRefParams) (Loan, error)
	GetBranchSettings(ctx context.Context, branchID int64) (BranchSetting, error)
	GetBranchTarget(ctx context.Context, id int64) (BranchTarget, error)
	GetBranchTargetBySeriesAndStart(ctx context.Context, arg GetBranchTargetBySeriesAndStartParams) (BranchTarget, error)
	GetBranchTargetSeries(ctx context.Context, id int64) (BranchTargetSeries, error)
	GetCashbox(ctx context.Context, id int64) (Cashbox, error)
	GetCashboxAccount(ctx context.Context, id int64) (CashboxAccount, error)
	GetCashboxAccountBalance(ctx context.Context, arg GetCashboxAccountBalanceParams) (ShiftsAccountsBalance, error)
	GetClient(ctx context.Context, id int64) (Client, error)
	GetClientByPhone(ctx context.Context, phone string) (Client, error)
	GetClientLink(ctx context.Context, arg GetClientLinkParams) (int64, error)
	GetCoupon(ctx context.Context, code string) (Coupon, error)
	GetCurrency(ctx context.Context, code string) (Currency, error)
	GetDefaultCurrency(ctx context.Context) (Currency, error)
	GetDefaultDiscountForProduct(ctx context.Context, productID int64) (int16, error)
	GetDefaultInvoiceType(ctx context.Context) (InvoiceType, error)
	GetDefaultPriceForProduct(ctx context.Context, productID int64) (int64, error)
	GetDiscountList(ctx context.Context, id int64) (DiscountList, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetExpense(ctx context.Context, id int64) (Expense, error)
	GetExpenseCategory(ctx context.Context, id int64) (ExpenseCategory, error)
	GetInventory(ctx context.Context, id int64) (Inventory, error)
	GetInvoice(ctx context.Context, id int64) (Invoice, error)
	GetInvoiceType(ctx context.Context, id int64) (InvoiceType, error)
	GetLoan(ctx context.Context, id int64) (Loan, error)
	GetLoanCategory(ctx context.Context, id int64) (LoanCategory, error)
	GetLoanPayment(ctx context.Context, id int64) (LoanPayment, error)
	GetNextBarcodeItemValue(ctx context.Context) (int64, error)
	GetPriceList(ctx context.Context, id int64) (PriceList, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetProductAttributeValue(ctx context.Context, arg GetProductAttributeValueParams) (ProductsAttribute, error)
	GetProductAttributes(ctx context.Context, productID int64) ([]ProductsAttribute, error)
	GetProductDiscountFromList(ctx context.Context, arg GetProductDiscountFromListParams) (DiscountListItem, error)
	GetProductPriceFromList(ctx context.Context, arg GetProductPriceFromListParams) (PriceListItem, error)
	GetProductVariant(ctx context.Context, id int64) (ProductVariant, error)
	GetProductVariantByBarcode(ctx context.Context, barcode string) (ProductVariant, error)
	GetPurchase(ctx context.Context, id int64) (Purchase, error)
	GetRecurringExpense(ctx context.Context, id int64) (RecurringExpense, error)
	GetReturnInvoice(ctx context.Context, invoiceID int64) (ReturnInvoice, error)
	GetSalesInvoice(ctx context.Context, invoiceID int64) (int64, error)
	GetSalesperson(ctx context.Context, id int64) (Salesperson, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetShift(ctx context.Context, id int64) (Shift, error)
	GetSupplier(ctx context.Context, id int64) (Supplier, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, name string) (User, error)
	IncrementInvoicesIndex(ctx context.Context, arg IncrementInvoicesIndexParams) (int64, error)
	ListActiveBranchTargetSeries(ctx context.Context) ([]BranchTargetSeries, error)
	ListAllCashboxAccounts(ctx context.Context) ([]CashboxAccount, error)
	ListAllCurrencies(ctx context.Context) ([]Currency, error)
	ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error)
	ListAttributeValues(ctx context.Context, arg ListAttributeValuesParams) ([]ListAttributeValuesRow, error)
	ListAttributes(ctx context.Context) ([]Attribute, error)
	ListBranchCommands(ctx context.Context, arg ListBranchCommandsParams) ([]BranchCommand, error)
	// sqlc.narg(branch_id) is nullable: NULL means "all branches", matching
	// ListBranchInvoices' admin-filter convention.
	ListBranchExpenses(ctx context.Context, arg ListBranchExpensesParams) ([]BranchExpense, error)
	ListBranchInvoiceItems(ctx context.Context, branchInvoiceID int64) ([]BranchInvoiceItem, error)
	// sqlc.narg(branch_id) is nullable: NULL means "all branches", matching how
	// the admin UI's branch filter works (a dropdown with an "All branches"
	// option, not a required selection).
	ListBranchInvoices(ctx context.Context, arg ListBranchInvoicesParams) ([]BranchInvoice, error)
	ListBranchTargetSeriesForBranch(ctx context.Context, branchID int64) ([]BranchTargetSeries, error)
	ListBranchTargetsForBranch(ctx context.Context, branchID int64) ([]BranchTarget, error)
	ListBranchTargetsUpdatedSince(ctx context.Context, arg ListBranchTargetsUpdatedSinceParams) ([]BranchTarget, error)
	ListBranches(ctx context.Context) ([]Branch, error)
	ListCashboxAccounts(ctx context.Context, arg ListCashboxAccountsParams) ([]CashboxAccount, error)
	ListCashboxAccountsUpdatedSince(ctx context.Context, updatedAt time.Time) ([]CashboxAccount, error)
	ListCashboxes(ctx context.Context, arg ListCashboxesParams) ([]Cashbox, error)
	// sqlc.narg(client_type) is nullable: NULL means "all types" -- the admin
	// clients page passes it when a Retail/Wholesale tab is selected, and
	// omits it for a combined view if one is ever added.
	ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error)
	// Feeds the branch catch-up endpoint (see branch_catchup.go), same pattern
	// as currencies/cashbox_accounts/products. Wholesale clients never appear
	// here -- they're a central-office concept, not something a branch till
	// should ever see in its client search. Converting an already-synced
	// retail client to wholesale won't retract it from branches that already
	// have it locally (no delete propagation exists for any synced entity
	// today); acceptable since that conversion is expected to be rare.
	ListClientsUpdatedSince(ctx context.Context, updatedAt time.Time) ([]Client, error)
	ListColors(ctx context.Context) ([]Color, error)
	ListCoupons(ctx context.Context, arg ListCouponsParams) ([]Coupon, error)
	ListCurrencies(ctx context.Context, arg ListCurrenciesParams) ([]Currency, error)
	ListCurrenciesUpdatedSince(ctx context.Context, updatedAt time.Time) ([]Currency, error)
	// Sums grand_total across both kinds ('sales' and 'return') rather than
	// treating them separately: a branch's return/exchange grand_total is
	// already the net signed cash effect it reported (negative for a refund,
	// positive for an even-or-up exchange -- see tx_exchange.go's netDifference
	// in kashi-pos), so a plain sum already nets returns against sales
	// correctly without this query needing to know or guess that sign
	// convention itself.
	ListDailyIncome(ctx context.Context, arg ListDailyIncomeParams) ([]ListDailyIncomeRow, error)
	ListDiscountListItems(ctx context.Context, discountListID int64) ([]DiscountListItem, error)
	ListDiscountLists(ctx context.Context, arg ListDiscountListsParams) ([]DiscountList, error)
	ListDueRecurringExpenses(ctx context.Context, nextDueAt time.Time) ([]RecurringExpense, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListExpenseCategories(ctx context.Context) ([]ExpenseCategory, error)
	ListExpenses(ctx context.Context, arg ListExpensesParams) ([]Expense, error)
	ListInventories(ctx context.Context, arg ListInventoriesParams) ([]Inventory, error)
	ListInventoryProducts(ctx context.Context, inventoryID int64) ([]ListInventoryProductsRow, error)
	ListInvoiceTypes(ctx context.Context) ([]InvoiceType, error)
	ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]Invoice, error)
	ListLoanCategories(ctx context.Context) ([]LoanCategory, error)
	// sqlc.narg(loan_id) is nullable: NULL means "all loans".
	ListLoanPayments(ctx context.Context, arg ListLoanPaymentsParams) ([]LoanPayment, error)
	// sqlc.narg(branch_id)/sqlc.narg(origin) are nullable: NULL means "no
	// filter", matching ListBranchExpenses' admin-filter convention.
	ListLoans(ctx context.Context, arg ListLoansParams) ([]Loan, error)
	ListPendingBranchCommands(ctx context.Context, branchID int64) ([]BranchCommand, error)
	ListPriceListItems(ctx context.Context, priceListID int64) ([]PriceListItem, error)
	ListPriceLists(ctx context.Context, arg ListPriceListsParams) ([]PriceList, error)
	ListProductAttributes(ctx context.Context, arg ListProductAttributesParams) ([]ProductsAttribute, error)
	ListProductVariants(ctx context.Context, arg ListProductVariantsParams) ([]ListProductVariantsRow, error)
	ListProductVariantsByProduct(ctx context.Context, productID int64) ([]ProductVariant, error)
	// Flattened for kashi-pos, which has no separate "product" row -- each
	// variant carries everything a branch needs to create or update its own
	// flat product row. Colors/sizes/attributes are resolved to their name
	// here (not sent as ids) since kashi-pos matches everything by name, not
	// by kashi's internal ids.
	//
	// Attribute ids (2=brand, 1=sub-category, 3=kind, 7=season, 6=year) match
	// the fixed seed in 000005_create_products_attributes_table.up.sql.
	// Editing a product's attributes doesn't currently bump
	// product_variants.updated_at (no endpoint does that edit yet -- see
	// api/product.go), so an attribute-only change wouldn't be picked up by
	// this filter if one ever existed; today attributes are only ever set at
	// creation time, in the same moment the variant's own updated_at is set,
	// so this doesn't miss anything in practice yet.
	ListProductVariantsForSync(ctx context.Context, updatedAt time.Time) ([]ListProductVariantsForSyncRow, error)
	ListProductVariantsUpdatedSince(ctx context.Context, updatedAt time.Time) ([]ProductVariant, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListPurchases(ctx context.Context, arg ListPurchasesParams) ([]Purchase, error)
	ListRecurringExpenses(ctx context.Context) ([]RecurringExpense, error)
	ListSalespersons(ctx context.Context, arg ListSalespersonsParams) ([]Salesperson, error)
	ListSalespersonsByCashbox(ctx context.Context, cashboxID sql.NullInt64) ([]Salesperson, error)
	ListSalespersonsForBranch(ctx context.Context, branchID sql.NullInt64) ([]Salesperson, error)
	ListSalespersonsUpdatedSince(ctx context.Context, arg ListSalespersonsUpdatedSinceParams) ([]Salesperson, error)
	ListShifts(ctx context.Context, arg ListShiftsParams) ([]Shift, error)
	ListSizes(ctx context.Context) ([]Size, error)
	// TOOD: add UpdateSupplier
	ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error)
	// TODO maybe this is not so clean
	ListTransferItems(ctx context.Context, transferID int64) ([]ListTransferItemsRow, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SetBranchActive(ctx context.Context, arg SetBranchActiveParams) error
	// The sync-facing "delete" -- see 000046_branch_target_soft_delete.up.sql
	// for why this flips a flag instead of removing the row.
	SetBranchTargetActive(ctx context.Context, arg SetBranchTargetActiveParams) (BranchTarget, error)
	SetBranchTargetSeriesActive(ctx context.Context, arg SetBranchTargetSeriesActiveParams) (BranchTargetSeries, error)
	SetRecurringExpenseActive(ctx context.Context, arg SetRecurringExpenseActiveParams) (RecurringExpense, error)
	SetSalespersonActive(ctx context.Context, arg SetSalespersonActiveParams) (Salesperson, error)
	// Net sales revenue: same grand_total-sum convention as ListDailyIncome in
	// branch_invoice.sql (returns already net out via their signed grand_total).
	SumBranchRevenueForRange(ctx context.Context, arg SumBranchRevenueForRangeParams) (int64, error)
	// The redemption-time query: every branch's contribution to this client's
	// loyalty balance, added up. Each branch is decisive for what it reports
	// (loyalty_points_delta on branch_invoices) -- this never recomputes that
	// number, only sums what's already been reported.
	SumClientLoyaltyPoints(ctx context.Context, clientID int64) (int64, error)
	UnsetDefaultDiscountList(ctx context.Context, id int64) error
	UnsetDefaultPriceList(ctx context.Context, id int64) error
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) error
	UpdateAttributeValue(ctx context.Context, arg UpdateAttributeValueParams) (AttributesValue, error)
	UpdateBranchAPIKeyHash(ctx context.Context, arg UpdateBranchAPIKeyHashParams) error
	UpdateBranchLastSeenAt(ctx context.Context, id int64) error
	UpdateBranchSalespersonName(ctx context.Context, arg UpdateBranchSalespersonNameParams) (Salesperson, error)
	UpdateBranchTarget(ctx context.Context, arg UpdateBranchTargetParams) (BranchTarget, error)
	// Only affects future periods -- see CreateGeneratedBranchTarget's note on
	// generation snapshotting a series' fields, never joining them live.
	UpdateBranchTargetSeries(ctx context.Context, arg UpdateBranchTargetSeriesParams) (BranchTargetSeries, error)
	UpdateCashbox(ctx context.Context, arg UpdateCashboxParams) (Cashbox, error)
	UpdateCashboxAccount(ctx context.Context, arg UpdateCashboxAccountParams) (CashboxAccount, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateCurrency(ctx context.Context, arg UpdateCurrencyParams) (Currency, error)
	UpdateDiscountList(ctx context.Context, arg UpdateDiscountListParams) error
	UpdateDiscountListItem(ctx context.Context, arg UpdateDiscountListItemParams) error
	UpdateExpenseCategory(ctx context.Context, arg UpdateExpenseCategoryParams) (ExpenseCategory, error)
	UpdateInventory(ctx context.Context, arg UpdateInventoryParams) error
	UpdateInvoiceType(ctx context.Context, arg UpdateInvoiceTypeParams) (InvoiceType, error)
	UpdateLoanCategory(ctx context.Context, arg UpdateLoanCategoryParams) (LoanCategory, error)
	UpdatePriceList(ctx context.Context, arg UpdatePriceListParams) error
	UpdatePriceListItem(ctx context.Context, arg UpdatePriceListItemParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateProductAttribute(ctx context.Context, arg UpdateProductAttributeParams) error
	UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error)
	UpdateRecurringExpenseNextDue(ctx context.Context, arg UpdateRecurringExpenseNextDueParams) (RecurringExpense, error)
	UpdateSalesperson(ctx context.Context, arg UpdateSalespersonParams) (Salesperson, error)
	UpdateTransfer(ctx context.Context, arg UpdateTransferParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpsertAttributeValue(ctx context.Context, arg UpsertAttributeValueParams) (AttributesValue, error)
	UpsertBranchSettings(ctx context.Context, arg UpsertBranchSettingsParams) (BranchSetting, error)
	UpsertClientLink(ctx context.Context, arg UpsertClientLinkParams) error
}

var _ Querier = (*Queries)(nil)
