// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recurring_expense.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createRecurringExpense = `-- name: CreateRecurringExpense :one
INSERT INTO recurring_expenses (
  description,
  category_id,
  amount,
  currency_code,
  interval_unit,
  interval_count,
  next_due_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, description, amount, currency_code, interval_unit, interval_count, next_due_at, active, created_at, category_id
`

type CreateRecurringExpenseParams struct {
	Description   string        `json:"description"`
	CategoryID    sql.NullInt64 `json:"category_id"`
	Amount        int64         `json:"amount"`
	CurrencyCode  string        `json:"currency_code"`
	IntervalUnit  string        `json:"interval_unit"`
	IntervalCount int32         `json:"interval_count"`
	NextDueAt     time.Time     `json:"next_due_at"`
}

func (q *Queries) CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) (RecurringExpense, error) {
	row := q.db.QueryRowContext(ctx, createRecurringExpense,
		arg.Description,
		arg.CategoryID,
		arg.Amount,
		arg.CurrencyCode,
		arg.IntervalUnit,
		arg.IntervalCount,
		arg.NextDueAt,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.CurrencyCode,
		&i.IntervalUnit,
		&i.IntervalCount,
		&i.NextDueAt,
		&i.Active,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}

const getRecurringExpense = `-- name: GetRecurringExpense :one
SELECT id, description, amount, currency_code, interval_unit, interval_count, next_due_at, active, created_at, category_id FROM recurring_expenses WHERE id = $1
`

func (q *Queries) GetRecurringExpense(ctx context.Context, id int64) (RecurringExpense, error) {
	row := q.db.QueryRowContext(ctx, getRecurringExpense, id)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.CurrencyCode,
		&i.IntervalUnit,
		&i.IntervalCount,
		&i.NextDueAt,
		&i.Active,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}

const listDueRecurringExpenses = `-- name: ListDueRecurringExpenses :many
SELECT id, description, amount, currency_code, interval_unit, interval_count, next_due_at, active, created_at, category_id FROM recurring_expenses
WHERE active AND next_due_at <= $1
ORDER BY id
`

func (q *Queries) ListDueRecurringExpenses(ctx context.Context, nextDueAt time.Time) ([]RecurringExpense, error) {
	rows, err := q.db.QueryContext(ctx, listDueRecurringExpenses, nextDueAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringExpense{}
	for rows.Next() {
		var i RecurringExpense
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.CurrencyCode,
			&i.IntervalUnit,
			&i.IntervalCount,
			&i.NextDueAt,
			&i.Active,
			&i.CreatedAt,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringExpenses = `-- name: ListRecurringExpenses :many
SELECT id, description, amount, currency_code, interval_unit, interval_count, next_due_at, active, created_at, category_id FROM recurring_expenses ORDER BY id DESC
`

func (q *Queries) ListRecurringExpenses(ctx context.Context) ([]RecurringExpense, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringExpense{}
	for rows.Next() {
		var i RecurringExpense
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.CurrencyCode,
			&i.IntervalUnit,
			&i.IntervalCount,
			&i.NextDueAt,
			&i.Active,
			&i.CreatedAt,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRecurringExpenseActive = `-- name: SetRecurringExpenseActive :one
UPDATE recurring_expenses SET active = $2 WHERE id = $1 RETURNING id, description, amount, currency_code, interval_unit, interval_count, next_due_at, active, created_at, category_id
`

type SetRecurringExpenseActiveParams struct {
	ID     int64 `json:"id"`
	Active bool  `json:"active"`
}

func (q *Queries) SetRecurringExpenseActive(ctx context.Context, arg SetRecurringExpenseActiveParams) (RecurringExpense, error) {
	row := q.db.QueryRowContext(ctx, setRecurringExpenseActive, arg.ID, arg.Active)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.CurrencyCode,
		&i.IntervalUnit,
		&i.IntervalCount,
		&i.NextDueAt,
		&i.Active,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}

const updateRecurringExpenseNextDue = `-- name: UpdateRecurringExpenseNextDue :one
UPDATE recurring_expenses SET next_due_at = $2 WHERE id = $1 RETURNING id, description, amount, currency_code, interval_unit, interval_count, next_due_at, active, created_at, category_id
`

type UpdateRecurringExpenseNextDueParams struct {
	ID        int64     `json:"id"`
	NextDueAt time.Time `json:"next_due_at"`
}

func (q *Queries) UpdateRecurringExpenseNextDue(ctx context.Context, arg UpdateRecurringExpenseNextDueParams) (RecurringExpense, error) {
	row := q.db.QueryRowContext(ctx, updateRecurringExpenseNextDue, arg.ID, arg.NextDueAt)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.CurrencyCode,
		&i.IntervalUnit,
		&i.IntervalCount,
		&i.NextDueAt,
		&i.Active,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}
