// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sizes.sql

package db

import (
	"context"
)

const createSize = `-- name: CreateSize :one
INSERT INTO sizes (
  name,
  type,
  "order"
) VALUES (
    $1, $2, $3
) RETURNING id, name, type, "order", version, created_at
`

type CreateSizeParams struct {
	Name  string `json:"name"`
	Type  string `json:"type"`
	Order string `json:"order"`
}

func (q *Queries) CreateSize(ctx context.Context, arg CreateSizeParams) (Size, error) {
	row := q.db.QueryRowContext(ctx, createSize, arg.Name, arg.Type, arg.Order)
	var i Size
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Order,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const listSizes = `-- name: ListSizes :many
SELECT id, name, type, "order", version, created_at FROM sizes
ORDER BY type, "order"
`

func (q *Queries) ListSizes(ctx context.Context) ([]Size, error) {
	rows, err := q.db.QueryContext(ctx, listSizes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Size{}
	for rows.Next() {
		var i Size
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Order,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
