// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfer.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countTransfers = `-- name: CountTransfers :one
SELECT COUNT(*) FROM transfers
`

func (q *Queries) CountTransfers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransfers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
  from_inventory_id,
  to_inventory_id,
  type,
  code,
  note
) VALUES ( $1, $2, $3, $4, $5 )
RETURNING id, from_inventory_id, to_inventory_id, type, created_at, code, status, dispatched_at, received_at, note
`

type CreateTransferParams struct {
	FromInventoryID int64        `json:"from_inventory_id"`
	ToInventoryID   int64        `json:"to_inventory_id"`
	Type            TransferType `json:"type"`
	Code            string       `json:"code"`
	Note            string       `json:"note"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer,
		arg.FromInventoryID,
		arg.ToInventoryID,
		arg.Type,
		arg.Code,
		arg.Note,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromInventoryID,
		&i.ToInventoryID,
		&i.Type,
		&i.CreatedAt,
		&i.Code,
		&i.Status,
		&i.DispatchedAt,
		&i.ReceivedAt,
		&i.Note,
	)
	return i, err
}

const createTransferItem = `-- name: CreateTransferItem :one
INSERT INTO transfer_items (
  transfer_id,
  variant_id,
  asset_id,
  quantity
) VALUES ( $1, $2, $3, $4 )
RETURNING id, transfer_id, asset_id, quantity, variant_id
`

type CreateTransferItemParams struct {
	TransferID int64         `json:"transfer_id"`
	VariantID  sql.NullInt64 `json:"variant_id"`
	AssetID    sql.NullInt64 `json:"asset_id"`
	Quantity   int64         `json:"quantity"`
}

func (q *Queries) CreateTransferItem(ctx context.Context, arg CreateTransferItemParams) (TransferItem, error) {
	row := q.db.QueryRowContext(ctx, createTransferItem,
		arg.TransferID,
		arg.VariantID,
		arg.AssetID,
		arg.Quantity,
	)
	var i TransferItem
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.AssetID,
		&i.Quantity,
		&i.VariantID,
	)
	return i, err
}

const deleteTransferItem = `-- name: DeleteTransferItem :exec
DELETE FROM transfer_items
WHERE transfer_items.id = $1
  AND transfer_items.transfer_id IN (
    SELECT transfers.id FROM transfers
    WHERE transfers.id = $2 AND transfers.status = 'draft'
  )
`

type DeleteTransferItemParams struct {
	ID   int64 `json:"id"`
	ID_2 int64 `json:"id_2"`
}

func (q *Queries) DeleteTransferItem(ctx context.Context, arg DeleteTransferItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteTransferItem, arg.ID, arg.ID_2)
	return err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, from_inventory_id, to_inventory_id, type, created_at, code, status, dispatched_at, received_at, note FROM transfers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransfer(ctx context.Context, id int64) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromInventoryID,
		&i.ToInventoryID,
		&i.Type,
		&i.CreatedAt,
		&i.Code,
		&i.Status,
		&i.DispatchedAt,
		&i.ReceivedAt,
		&i.Note,
	)
	return i, err
}

const listTransferItems = `-- name: ListTransferItems :many
SELECT
  ti.id, ti.transfer_id, ti.asset_id, ti.quantity, ti.variant_id,
  p.name AS product_name,
  p.code AS product_code,
  pv.barcode AS variant_barcode,
  a.name AS asset_name
FROM transfer_items ti
LEFT JOIN product_variants pv ON pv.id = ti.variant_id
LEFT JOIN products p ON p.id = pv.product_id
LEFT JOIN assets a ON a.id = ti.asset_id
WHERE ti.transfer_id = $1
ORDER BY ti.id
`

type ListTransferItemsRow struct {
	ID             int64          `json:"id"`
	TransferID     int64          `json:"transfer_id"`
	AssetID        sql.NullInt64  `json:"asset_id"`
	Quantity       int64          `json:"quantity"`
	VariantID      sql.NullInt64  `json:"variant_id"`
	ProductName    sql.NullString `json:"product_name"`
	ProductCode    sql.NullString `json:"product_code"`
	VariantBarcode sql.NullString `json:"variant_barcode"`
	AssetName      sql.NullString `json:"asset_name"`
}

func (q *Queries) ListTransferItems(ctx context.Context, transferID int64) ([]ListTransferItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransferItems, transferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransferItemsRow{}
	for rows.Next() {
		var i ListTransferItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.AssetID,
			&i.Quantity,
			&i.VariantID,
			&i.ProductName,
			&i.ProductCode,
			&i.VariantBarcode,
			&i.AssetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfers = `-- name: ListTransfers :many
SELECT
  t.id, t.from_inventory_id, t.to_inventory_id, t.type, t.created_at, t.code, t.status, t.dispatched_at, t.received_at, t.note,
  fi.name AS from_inventory_name,
  ti.name AS to_inventory_name,
  (SELECT COUNT(*) FROM transfer_items x WHERE x.transfer_id = t.id) AS item_count
FROM transfers t
JOIN inventories fi ON fi.id = t.from_inventory_id
JOIN inventories ti ON ti.id = t.to_inventory_id
ORDER BY t.id DESC
LIMIT $1
OFFSET $2
`

type ListTransfersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListTransfersRow struct {
	ID                int64          `json:"id"`
	FromInventoryID   int64          `json:"from_inventory_id"`
	ToInventoryID     int64          `json:"to_inventory_id"`
	Type              TransferType   `json:"type"`
	CreatedAt         time.Time      `json:"created_at"`
	Code              string         `json:"code"`
	Status            TransferStatus `json:"status"`
	DispatchedAt      sql.NullTime   `json:"dispatched_at"`
	ReceivedAt        sql.NullTime   `json:"received_at"`
	Note              string         `json:"note"`
	FromInventoryName string         `json:"from_inventory_name"`
	ToInventoryName   string         `json:"to_inventory_name"`
	ItemCount         int64          `json:"item_count"`
}

func (q *Queries) ListTransfers(ctx context.Context, arg ListTransfersParams) ([]ListTransfersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransfers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransfersRow{}
	for rows.Next() {
		var i ListTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.FromInventoryID,
			&i.ToInventoryID,
			&i.Type,
			&i.CreatedAt,
			&i.Code,
			&i.Status,
			&i.DispatchedAt,
			&i.ReceivedAt,
			&i.Note,
			&i.FromInventoryName,
			&i.ToInventoryName,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTransferStatus = `-- name: SetTransferStatus :one
UPDATE transfers
SET status = $1,
    dispatched_at = COALESCE($2, dispatched_at),
    received_at = COALESCE($3, received_at)
WHERE id = $4
RETURNING id, from_inventory_id, to_inventory_id, type, created_at, code, status, dispatched_at, received_at, note
`

type SetTransferStatusParams struct {
	Status       TransferStatus `json:"status"`
	DispatchedAt sql.NullTime   `json:"dispatched_at"`
	ReceivedAt   sql.NullTime   `json:"received_at"`
	ID           int64          `json:"id"`
}

func (q *Queries) SetTransferStatus(ctx context.Context, arg SetTransferStatusParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, setTransferStatus,
		arg.Status,
		arg.DispatchedAt,
		arg.ReceivedAt,
		arg.ID,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromInventoryID,
		&i.ToInventoryID,
		&i.Type,
		&i.CreatedAt,
		&i.Code,
		&i.Status,
		&i.DispatchedAt,
		&i.ReceivedAt,
		&i.Note,
	)
	return i, err
}

const updateTransfer = `-- name: UpdateTransfer :exec
UPDATE transfers
SET from_inventory_id = $2,
    to_inventory_id = $3,
    type = $4,
    note = $5
WHERE id = $1 AND status = 'draft'
`

type UpdateTransferParams struct {
	ID              int64        `json:"id"`
	FromInventoryID int64        `json:"from_inventory_id"`
	ToInventoryID   int64        `json:"to_inventory_id"`
	Type            TransferType `json:"type"`
	Note            string       `json:"note"`
}

func (q *Queries) UpdateTransfer(ctx context.Context, arg UpdateTransferParams) error {
	_, err := q.db.ExecContext(ctx, updateTransfer,
		arg.ID,
		arg.FromInventoryID,
		arg.ToInventoryID,
		arg.Type,
		arg.Note,
	)
	return err
}
