### Create an entry
POST {{baseUrl}}/entries
Content-Type: application/json
Authorization: bearer {{token}}

{
  "cashbox_id": 1,
  "inventory_id": 1,
  "reference_type": "sales_invoice",
  "reference_id": 1,
  "amount": 50000
}

### Get an entry by id
GET {{baseUrl}}/entries/1
Authorization: bearer {{token}}

### List entries by inventory
GET {{baseUrl}}/entries?inventory_id=1&page_size=10&page_id=0
Authorization: bearer {{token}}
