import {
  mdiAccount,
  mdiTranslate,
  mdiAccountCash,
  mdiAccountGroup,
  mdiAccountGroupOutline,
  mdiAccountMultipleCheck,
  mdiAccountOutline,
  mdiArrowLeft,
  mdiArrowLeftThin,
  mdiArrowRight,
  mdiArrowRightThick,
  mdiArrowRightThin,
  mdiArrowUp,
  mdiBagPersonal,
  mdiBarcode,
  mdiBell,
  mdiCalendar,
  mdiCardAccountDetails,
  mdiCart,
  mdiCartCheck,
  mdiChartBar,
  mdiCheckCircle,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiCircle,
  mdiCircleOutline,
  mdiClock,
  mdiClockOutline,
  mdiClose,
  mdiCloseCircle,
  mdiCloseCircleOutline,
  mdiCloud,
  mdiCurrencyUsd,
  mdiCurrencyUsdOff,
  mdiDelete,
  mdiDomain,
  mdiDotsVertical,
  mdiEmailOutline,
  mdiEye,
  mdiEyeOff,
  mdiFilter,
  mdiFolderNetwork,
  mdiFormatListBulleted,
  mdiFormatListBulletedSquare,
  mdiGithub,
  mdiGoogleDrive,
  mdiHammerWrench,
  mdiHanger,
  mdiHeart,
  mdiHome,
  mdiHomeVariant,
  mdiIdentifier,
  mdiInformation,
  mdiInvoice,
  mdiLockOutline,
  mdiLogout,
  mdiMagnify,
  mdiMenu,
  mdiMenuDown,
  mdiNumeric1Box,
  mdiNumeric2Box,
  mdiNumeric3Box,
  mdiNumeric4Box,
  mdiNumeric5Box,
  mdiOpenInNew,
  mdiPackageVariant,
  mdiPageFirst,
  mdiPageLast,
  mdiPalette,
  mdiPencil,
  mdiPlus,
  mdiPlusCircle,
  mdiReceiptTextCheck,
  mdiReddit,
  mdiSale,
  mdiShieldStarOutline,
  mdiShoeSneaker,
  mdiSineWave,
  mdiStar,
  mdiStoreOutline,
  mdiText,
  mdiThemeLightDark,
  mdiTicketPercent,
  mdiTransfer,
  mdiTruckDelivery,
  mdiTshirtCrew,
  mdiViewDashboard,
  mdiViewGallery,
  mdiWarehouse,
  mdiWeatherNight,
  mdiWhiteBalanceSunny,
} from '@mdi/js'
import { h } from 'vue'

const iconPaths = {
  'mdi-translate': mdiTranslate,
  'mdi-account': mdiAccount,
  'mdi-account-outline': mdiAccountOutline,
  'mdi-account-cash': mdiAccountCash,
  'mdi-account-group': mdiAccountGroup,
  'mdi-account-group-outline': mdiAccountGroupOutline,
  'mdi-account-multiple-check-outline': mdiAccountMultipleCheck,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-arrow-left-thin': mdiArrowLeftThin,
  'mdi-arrow-right': mdiArrowRight,
  'mdi-arrow-right-thick': mdiArrowRightThick,
  'mdi-arrow-right-thin': mdiArrowRightThin,
  'mdi-arrow-up': mdiArrowUp,
  'mdi-bag-personal': mdiBagPersonal,
  'mdi-barcode': mdiBarcode,
  'mdi-bell': mdiBell,
  'mdi-calendar': mdiCalendar,
  'mdi-card-account-details': mdiCardAccountDetails,
  'mdi-cart': mdiCart,
  'mdi-cart-check': mdiCartCheck,
  'mdi-chart-bar': mdiChartBar,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-chevron-left': mdiChevronLeft,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-circle': mdiCircle,
  'mdi-circle-outline': mdiCircleOutline,
  'mdi-clock': mdiClock,
  'mdi-close': mdiClose,
  'mdi-close-circle': mdiCloseCircle,
  'mdi-close-circle-outline': mdiCloseCircleOutline,
  'mdi-cloud': mdiCloud,
  'mdi-clock-outline': mdiClockOutline,
  'mdi-currency-usd': mdiCurrencyUsd,
  'mdi-currency-usd-off': mdiCurrencyUsdOff,
  'mdi-delete': mdiDelete,
  'mdi-domain': mdiDomain,
  'mdi-dots-vertical': mdiDotsVertical,
  'mdi-email-outline': mdiEmailOutline,
  'mdi-eye': mdiEye,
  'mdi-eye-off': mdiEyeOff,
  'mdi-filter': mdiFilter,
  'mdi-format-list-bulleted': mdiFormatListBulleted,
  'mdi-format-list-bulleted-square': mdiFormatListBulletedSquare,
  'mdi-github': mdiGithub,
  'mdi-google-drive': mdiGoogleDrive,
  'mdi-hammer-wrench': mdiHammerWrench,
  'mdi-hanger': mdiHanger,
  'mdi-heart': mdiHeart,
  'mdi-home': mdiHome,
  'mdi-home-variant': mdiHomeVariant,
  'mdi-identifier': mdiIdentifier,
  'mdi-information': mdiInformation,
  'mdi-invoice': mdiInvoice,
  'mdi-lock-outline': mdiLockOutline,
  'mdi-logout': mdiLogout,
  'mdi-magnify': mdiMagnify,
  'mdi-menu': mdiMenu,
  'mdi-menu-down': mdiMenuDown,
  'mdi-numeric-1-box': mdiNumeric1Box,
  'mdi-numeric-2-box': mdiNumeric2Box,
  'mdi-numeric-3-box': mdiNumeric3Box,
  'mdi-numeric-4-box': mdiNumeric4Box,
  'mdi-numeric-5-box': mdiNumeric5Box,
  'mdi-open-in-new': mdiOpenInNew,
  'mdi-package-variant': mdiPackageVariant,
  'mdi-page-first': mdiPageFirst,
  'mdi-page-last': mdiPageLast,
  'mdi-palette': mdiPalette,
  'mdi-pencil': mdiPencil,
  'mdi-plus': mdiPlus,
  'mdi-plus-circle': mdiPlusCircle,
  'mdi-receipt-text-check': mdiReceiptTextCheck,
  'mdi-reddit': mdiReddit,
  'mdi-sale': mdiSale,
  'mdi-shield-star-outline': mdiShieldStarOutline,
  'mdi-shoe-sneaker': mdiShoeSneaker,
  'mdi-sine-wave': mdiSineWave,
  'mdi-star': mdiStar,
  'mdi-store-outline': mdiStoreOutline,
  'mdi-text': mdiText,
  'mdi-theme-light-dark': mdiThemeLightDark,
  'mdi-ticket-percent': mdiTicketPercent,
  'mdi-transfer': mdiTransfer,
  'mdi-truck-delivery': mdiTruckDelivery,
  'mdi-tshirt-crew': mdiTshirtCrew,
  'mdi-view-gallery': mdiViewGallery,
  'mdi-view-dashboard': mdiViewDashboard,
  'mdi-warehouse': mdiWarehouse,
  'mdi-weather-night': mdiWeatherNight,
  'mdi-white-balance-sunny': mdiWhiteBalanceSunny,
  'mdi-folder-network': mdiFolderNetwork,
}

const mdi = {
  component: props => {
    const path = iconPaths[props.icon]
    if (!path) {
      console.warn(`Icon "${props.icon}" not found in custom MDI icon set`)
      return h(props.tag, null, props.icon)
    }
    return h(props.tag, null, {
      default: () => [
        h('svg', {
          'xmlns': 'http://www.w3.org/2000/svg',
          'viewBox': '0 0 24 24',
          'role': 'img',
          'aria-hidden': 'true',
          'class': 'v-icon__svg',
        }, [h('path', { d: path })]),
      ],
    })
  },
}

const aliases = {
  translate: 'mdi-translate',
  collapse: 'mdi-chevron-up',
  complete: 'mdi-check',
  cancel: 'mdi-close-circle',
  close: 'mdi-close',
  delete: 'mdi-close-circle',
  clear: 'mdi-close-circle',
  success: 'mdi-check-circle',
  info: 'mdi-information',
  warning: 'mdi-alert-circle',
  prev: 'mdi-chevron-left',
  next: 'mdi-chevron-right',
  checkboxOn: 'mdi-checkbox-marked',
  checkboxOff: 'mdi-checkbox-blank-outline',
  checkboxIndeterminate: 'mdi-minus-box',
  delimiter: 'mdi-circle',
  sortAsc: 'mdi-arrow-up',
  sortDesc: 'mdi-arrow-down',
  expand: 'mdi-chevron-down',
  menu: 'mdi-menu',
  subgroup: 'mdi-menu-down',
  dropdown: 'mdi-menu-down',
  radioOn: 'mdi-radiobox-marked',
  radioOff: 'mdi-radiobox-blank',
  edit: 'mdi-pencil',
  ratingEmpty: 'mdi-star-outline',
  ratingFull: 'mdi-star',
  ratingHalf: 'mdi-star-half-full',
  loading: 'mdi-cached',
  first: 'mdi-page-first',
  last: 'mdi-page-last',
  unfold: 'mdi-unfold-more-horizontal',
  file: 'mdi-paperclip',
  plus: 'mdi-plus',
  minus: 'mdi-minus',
  calendar: 'mdi-calendar',
  treeviewCollapse: 'mdi-menu-down',
  treeviewExpand: 'mdi-menu-right',
  tableGroupCollapse: 'mdi-chevron-down',
  tableGroupExpand: 'mdi-chevron-right',
  eyeDropper: 'mdi-eyedropper',
  upload: 'mdi-cloud-upload',
  cloud: 'mdi-cloud',
  color: 'mdi-palette',
  command: 'mdi-apple-keyboard-command',
  ctrl: 'mdi-apple-keyboard-control',
  space: 'mdi-keyboard-space',
  shift: 'mdi-apple-keyboard-shift',
  alt: 'mdi-apple-keyboard-option',
  enter: 'mdi-keyboard-return',
  arrowup: 'mdi-arrow-up',
  arrowdown: 'mdi-arrow-down',
  arrowleft: 'mdi-arrow-left',
  arrowright: 'mdi-arrow-right',
  backspace: 'mdi-backspace',
  play: 'mdi-play',
  pause: 'mdi-pause',
  fullscreen: 'mdi-fullscreen',
  fullscreenExit: 'mdi-fullscreen-exit',
  volumeHigh: 'mdi-volume-high',
  volumeMedium: 'mdi-volume-medium',
  volumeLow: 'mdi-volume-low',
  volumeOff: 'mdi-volume-variant-off',
  search: 'mdi-magnify',
}

export { aliases, mdi }
