import {
  mdiAccount,
  mdiAccountCash,
  mdiAccountGroup,
  mdiAccountGroupOutline,
  mdiAccountMultipleCheck,
  mdiAccountOutline,
  mdiAccountTieOutline,
  mdiAlertCircle,
  mdiAlertCircleOutline,
  mdiAppleKeyboardCommand,
  mdiAppleKeyboardControl,
  mdiAppleKeyboardOption,
  mdiAppleKeyboardShift,
  mdiArrowDown,
  mdiArrowLeft,
  mdiArrowLeftThin,
  mdiArrowRight,
  mdiArrowRightThick,
  mdiArrowRightThin,
  mdiArrowTopRight,
  mdiArrowULeftTop,
  mdiArrowUp,
  mdiBackspace,
  mdiBagPersonal,
  mdiBank,
  mdiBarcode,
  mdiBell,
  mdiBroom,
  mdiBullhorn,
  mdiCached,
  mdiCalendar,
  mdiCalendarToday,
  mdiCamera,
  mdiCar,
  mdiCardAccountDetails,
  mdiCart,
  mdiCartCheck,
  mdiCash,
  mdiCashEdit,
  mdiCashMinus,
  mdiCashMultiple,
  mdiCashRefund,
  mdiCashRegister,
  mdiChartBar,
  mdiChartBoxOutline,
  mdiChartLine,
  mdiCheck,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarked,
  mdiCheckboxMultipleMarkedOutline,
  mdiCheckCircle,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiCircle,
  mdiCircleOutline,
  mdiClock,
  mdiClockCheckOutline,
  mdiClockEditOutline,
  mdiClockOutline,
  mdiClockRemoveOutline,
  mdiClose,
  mdiCloseCircle,
  mdiCloseCircleOutline,
  mdiCloud,
  mdiCloudUpload,
  mdiCoffee,
  mdiCogOutline,
  mdiContentCopy,
  mdiContentSave,
  mdiCreditCardOutline,
  mdiCurrencyUsd,
  mdiCurrencyUsdOff,
  mdiDelete,
  mdiDomain,
  mdiDotsVertical,
  mdiEmailOutline,
  mdiEye,
  mdiEyedropper,
  mdiEyeOff,
  mdiFilter,
  mdiFilterVariant,
  mdiFingerprint,
  mdiFirework,
  mdiFlagOutline,
  mdiFlash,
  mdiFlowerTulip,
  mdiFolder,
  mdiFolderNetwork,
  mdiFood,
  mdiFormatListBulleted,
  mdiFormatListBulletedSquare,
  mdiFullscreen,
  mdiFullscreenExit,
  mdiGasStation,
  mdiGiftOutline,
  mdiGithub,
  mdiGoogleDrive,
  mdiHalloween,
  mdiHammerWrench,
  mdiHandCoin,
  mdiHanger,
  mdiHeart,
  mdiHeartPulse,
  mdiHistory,
  mdiHome,
  mdiHomeCity,
  mdiHomeVariant,
  mdiIdentifier,
  mdiImage,
  mdiInformation,
  mdiInvoice,
  mdiKey,
  mdiKeyboardReturn,
  mdiKeyboardSpace,
  mdiLaptop,
  mdiLightbulb,
  mdiLockOutline,
  mdiLogout,
  mdiMagnify,
  mdiMedicalBag,
  mdiMenu,
  mdiMenuDown,
  mdiMenuRight,
  mdiMinus,
  mdiMinusBox,
  mdiMonitor,
  mdiMoonWaningCrescent,
  mdiNumeric1Box,
  mdiNumeric2Box,
  mdiNumeric3Box,
  mdiNumeric4Box,
  mdiNumeric5Box,
  mdiOpenInNew,
  mdiPackageVariant,
  mdiPackageVariantClosed,
  mdiPageFirst,
  mdiPageLast,
  mdiPalette,
  mdiPaperclip,
  mdiPause,
  mdiPencil,
  mdiPercentOutline,
  mdiPhone,
  mdiPineTree,
  mdiPlay,
  mdiPlus,
  mdiPlusCircle,
  mdiPrinter,
  mdiPulse,
  mdiRadioboxBlank,
  mdiRadioboxMarked,
  mdiReceiptTextCheck,
  mdiReddit,
  mdiRefresh,
  mdiRepeat,
  mdiSale,
  mdiScaleBalance,
  mdiSchool,
  mdiServerNetworkOff,
  mdiShieldCheck,
  mdiShieldStarOutline,
  mdiShoeSneaker,
  mdiSineWave,
  mdiSnowflake,
  mdiStar,
  mdiStarHalfFull,
  mdiStarOutline,
  mdiStoreCogOutline,
  mdiStoreOutline,
  mdiSwapHorizontal,
  mdiSwapVertical,
  mdiTagMultiple,
  mdiTagOutline,
  mdiTarget,
  mdiText,
  mdiThemeLightDark,
  mdiTicketPercent,
  mdiTransfer,
  mdiTranslate,
  mdiTrendingDown,
  mdiTrendingUp,
  mdiTriangle,
  mdiTriangleDown,
  mdiTrophy,
  mdiTruck,
  mdiTruckDelivery,
  mdiTshirtCrew,
  mdiUnfoldMoreHorizontal,
  mdiViewDashboard,
  mdiViewGallery,
  mdiVolumeHigh,
  mdiVolumeLow,
  mdiVolumeMedium,
  mdiVolumeVariantOff,
  mdiWarehouse,
  mdiWater,
  mdiWeatherNight,
  mdiWhiteBalanceSunny,
  mdiWifi,
  mdiWrench,
} from '@mdi/js'
import { h } from 'vue'

const iconPaths = {
  'mdi-translate': mdiTranslate,
  'mdi-account': mdiAccount,
  'mdi-account-outline': mdiAccountOutline,
  'mdi-account-tie-outline': mdiAccountTieOutline,
  'mdi-account-cash': mdiAccountCash,
  'mdi-account-group': mdiAccountGroup,
  'mdi-account-group-outline': mdiAccountGroupOutline,
  'mdi-account-multiple-check-outline': mdiAccountMultipleCheck,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-arrow-left-thin': mdiArrowLeftThin,
  'mdi-arrow-right': mdiArrowRight,
  'mdi-arrow-right-thick': mdiArrowRightThick,
  'mdi-arrow-right-thin': mdiArrowRightThin,
  'mdi-arrow-top-right': mdiArrowTopRight,
  'mdi-arrow-down': mdiArrowDown,
  'mdi-arrow-u-left-top': mdiArrowULeftTop,
  'mdi-arrow-up': mdiArrowUp,
  'mdi-apple-keyboard-command': mdiAppleKeyboardCommand,
  'mdi-apple-keyboard-control': mdiAppleKeyboardControl,
  'mdi-apple-keyboard-option': mdiAppleKeyboardOption,
  'mdi-apple-keyboard-shift': mdiAppleKeyboardShift,
  'mdi-backspace': mdiBackspace,
  'mdi-bag-personal': mdiBagPersonal,
  'mdi-barcode': mdiBarcode,
  'mdi-bell': mdiBell,
  'mdi-calendar': mdiCalendar,
  'mdi-card-account-details': mdiCardAccountDetails,
  'mdi-cart': mdiCart,
  'mdi-cart-check': mdiCartCheck,
  'mdi-cash-edit': mdiCashEdit,
  'mdi-cash-minus': mdiCashMinus,
  'mdi-cash-multiple': mdiCashMultiple,
  'mdi-cash-refund': mdiCashRefund,
  'mdi-cash-register': mdiCashRegister,
  'mdi-clock-check-outline': mdiClockCheckOutline,
  'mdi-clock-edit-outline': mdiClockEditOutline,
  'mdi-clock-remove-outline': mdiClockRemoveOutline,
  'mdi-fingerprint': mdiFingerprint,
  'mdi-chart-bar': mdiChartBar,
  'mdi-chart-box-outline': mdiChartBoxOutline,
  'mdi-chart-line': mdiChartLine,
  'mdi-check': mdiCheck,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-checkbox-blank-outline': mdiCheckboxBlankOutline,
  'mdi-checkbox-multiple-marked-outline': mdiCheckboxMultipleMarkedOutline,
  'mdi-checkbox-marked': mdiCheckboxMarked,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-chevron-left': mdiChevronLeft,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-chevron-up': mdiChevronUp,
  'mdi-circle': mdiCircle,
  'mdi-circle-outline': mdiCircleOutline,
  'mdi-clock': mdiClock,
  'mdi-cog-outline': mdiCogOutline,
  'mdi-close': mdiClose,
  'mdi-close-circle': mdiCloseCircle,
  'mdi-close-circle-outline': mdiCloseCircleOutline,
  'mdi-cloud': mdiCloud,
  'mdi-cloud-upload': mdiCloudUpload,
  'mdi-clock-outline': mdiClockOutline,
  'mdi-cached': mdiCached,
  'mdi-calendar-today': mdiCalendarToday,
  'mdi-content-copy': mdiContentCopy,
  'mdi-content-save': mdiContentSave,
  'mdi-currency-usd': mdiCurrencyUsd,
  'mdi-currency-usd-off': mdiCurrencyUsdOff,
  'mdi-delete': mdiDelete,
  'mdi-domain': mdiDomain,
  'mdi-dots-vertical': mdiDotsVertical,
  'mdi-email-outline': mdiEmailOutline,
  'mdi-eye': mdiEye,
  'mdi-eye-off': mdiEyeOff,
  'mdi-filter': mdiFilter,
  'mdi-filter-variant': mdiFilterVariant,
  'mdi-firework': mdiFirework,
  'mdi-flag-outline': mdiFlagOutline,
  'mdi-flower-tulip': mdiFlowerTulip,
  'mdi-format-list-bulleted': mdiFormatListBulleted,
  'mdi-format-list-bulleted-square': mdiFormatListBulletedSquare,
  'mdi-gift-outline': mdiGiftOutline,
  'mdi-github': mdiGithub,
  'mdi-google-drive': mdiGoogleDrive,
  'mdi-halloween': mdiHalloween,
  'mdi-hammer-wrench': mdiHammerWrench,
  'mdi-hand-coin': mdiHandCoin,
  'mdi-hanger': mdiHanger,
  'mdi-heart': mdiHeart,
  'mdi-heart-pulse': mdiHeartPulse,
  'mdi-history': mdiHistory,
  'mdi-home': mdiHome,
  'mdi-home-variant': mdiHomeVariant,
  'mdi-identifier': mdiIdentifier,
  'mdi-information': mdiInformation,
  'mdi-invoice': mdiInvoice,
  'mdi-key': mdiKey,
  'mdi-laptop': mdiLaptop,
  'mdi-lock-outline': mdiLockOutline,
  'mdi-logout': mdiLogout,
  'mdi-magnify': mdiMagnify,
  'mdi-menu': mdiMenu,
  'mdi-menu-down': mdiMenuDown,
  'mdi-menu-right': mdiMenuRight,
  'mdi-minus': mdiMinus,
  'mdi-minus-box': mdiMinusBox,
  'mdi-monitor': mdiMonitor,
  'mdi-moon-waning-crescent': mdiMoonWaningCrescent,
  'mdi-numeric-1-box': mdiNumeric1Box,
  'mdi-numeric-2-box': mdiNumeric2Box,
  'mdi-numeric-3-box': mdiNumeric3Box,
  'mdi-numeric-4-box': mdiNumeric4Box,
  'mdi-numeric-5-box': mdiNumeric5Box,
  'mdi-open-in-new': mdiOpenInNew,
  'mdi-package-variant': mdiPackageVariant,
  'mdi-page-first': mdiPageFirst,
  'mdi-page-last': mdiPageLast,
  'mdi-palette': mdiPalette,
  'mdi-paperclip': mdiPaperclip,
  'mdi-pause': mdiPause,
  'mdi-pencil': mdiPencil,
  'mdi-percent-outline': mdiPercentOutline,
  'mdi-pine-tree': mdiPineTree,
  'mdi-play': mdiPlay,
  'mdi-plus': mdiPlus,
  'mdi-plus-circle': mdiPlusCircle,
  'mdi-pulse': mdiPulse,
  'mdi-receipt-text-check': mdiReceiptTextCheck,
  'mdi-radiobox-blank': mdiRadioboxBlank,
  'mdi-radiobox-marked': mdiRadioboxMarked,
  'mdi-reddit': mdiReddit,
  'mdi-refresh': mdiRefresh,
  'mdi-repeat': mdiRepeat,
  'mdi-sale': mdiSale,
  'mdi-school': mdiSchool,
  'mdi-server-network-off': mdiServerNetworkOff,
  'mdi-shield-star-outline': mdiShieldStarOutline,
  'mdi-shoe-sneaker': mdiShoeSneaker,
  'mdi-sine-wave': mdiSineWave,
  'mdi-snowflake': mdiSnowflake,
  'mdi-star': mdiStar,
  'mdi-star-half-full': mdiStarHalfFull,
  'mdi-star-outline': mdiStarOutline,
  'mdi-store-cog-outline': mdiStoreCogOutline,
  'mdi-store-outline': mdiStoreOutline,
  'mdi-swap-horizontal': mdiSwapHorizontal,
  'mdi-text': mdiText,
  'mdi-theme-light-dark': mdiThemeLightDark,
  'mdi-tag-multiple': mdiTagMultiple,
  'mdi-target': mdiTarget,
  'mdi-ticket-percent': mdiTicketPercent,
  'mdi-transfer': mdiTransfer,
  'mdi-swap-vertical': mdiSwapVertical,
  'mdi-trending-down': mdiTrendingDown,
  'mdi-trending-up': mdiTrendingUp,
  'mdi-triangle': mdiTriangle,
  'mdi-triangle-down': mdiTriangleDown,
  'mdi-trophy': mdiTrophy,
  'mdi-truck-delivery': mdiTruckDelivery,
  'mdi-tshirt-crew': mdiTshirtCrew,
  'mdi-view-gallery': mdiViewGallery,
  'mdi-view-dashboard': mdiViewDashboard,
  'mdi-warehouse': mdiWarehouse,
  'mdi-weather-night': mdiWeatherNight,
  'mdi-white-balance-sunny': mdiWhiteBalanceSunny,
  'mdi-folder-network': mdiFolderNetwork,
  'mdi-folder': mdiFolder,
  'mdi-image': mdiImage,
  'mdi-camera': mdiCamera,
  'mdi-alert-circle': mdiAlertCircle,
  'mdi-alert-circle-outline': mdiAlertCircleOutline,
  'mdi-eyedropper': mdiEyedropper,
  'mdi-fullscreen': mdiFullscreen,
  'mdi-fullscreen-exit': mdiFullscreenExit,
  'mdi-keyboard-return': mdiKeyboardReturn,
  'mdi-keyboard-space': mdiKeyboardSpace,
  'mdi-unfold-more-horizontal': mdiUnfoldMoreHorizontal,
  'mdi-volume-high': mdiVolumeHigh,
  'mdi-volume-low': mdiVolumeLow,
  'mdi-volume-medium': mdiVolumeMedium,
  'mdi-volume-variant-off': mdiVolumeVariantOff,
  // Expense-category icons.
  'mdi-bank': mdiBank,
  'mdi-broom': mdiBroom,
  'mdi-bullhorn': mdiBullhorn,
  'mdi-car': mdiCar,
  'mdi-cash': mdiCash,
  'mdi-coffee': mdiCoffee,
  'mdi-credit-card-outline': mdiCreditCardOutline,
  'mdi-flash': mdiFlash,
  'mdi-food': mdiFood,
  'mdi-gas-station': mdiGasStation,
  'mdi-home-city': mdiHomeCity,
  'mdi-lightbulb': mdiLightbulb,
  'mdi-medical-bag': mdiMedicalBag,
  'mdi-package-variant-closed': mdiPackageVariantClosed,
  'mdi-phone': mdiPhone,
  'mdi-printer': mdiPrinter,
  'mdi-scale-balance': mdiScaleBalance,
  'mdi-shield-check': mdiShieldCheck,
  'mdi-tag-outline': mdiTagOutline,
  'mdi-truck': mdiTruck,
  'mdi-water': mdiWater,
  'mdi-wifi': mdiWifi,
  'mdi-wrench': mdiWrench,
}

const mdi = {
  component: props => {
    const path = iconPaths[props.icon]
    if (!path) {
      console.warn(`Icon "${props.icon}" not found in custom MDI icon set`)
      return h(props.tag, null, props.icon)
    }
    return h(props.tag, null, {
      default: () => [
        h('svg', {
          'xmlns': 'http://www.w3.org/2000/svg',
          'viewBox': '0 0 24 24',
          'role': 'img',
          'aria-hidden': 'true',
          'class': 'v-icon__svg',
        }, [h('path', { d: path })]),
      ],
    })
  },
}

const aliases = {
  translate: 'mdi-translate',
  collapse: 'mdi-chevron-up',
  complete: 'mdi-check',
  cancel: 'mdi-close-circle',
  close: 'mdi-close',
  delete: 'mdi-close-circle',
  clear: 'mdi-close-circle',
  success: 'mdi-check-circle',
  info: 'mdi-information',
  warning: 'mdi-alert-circle',
  prev: 'mdi-chevron-left',
  next: 'mdi-chevron-right',
  checkboxOn: 'mdi-checkbox-marked',
  checkboxOff: 'mdi-checkbox-blank-outline',
  checkboxIndeterminate: 'mdi-minus-box',
  delimiter: 'mdi-circle',
  sortAsc: 'mdi-arrow-up',
  sortDesc: 'mdi-arrow-down',
  expand: 'mdi-chevron-down',
  menu: 'mdi-menu',
  subgroup: 'mdi-menu-down',
  dropdown: 'mdi-menu-down',
  radioOn: 'mdi-radiobox-marked',
  radioOff: 'mdi-radiobox-blank',
  edit: 'mdi-pencil',
  ratingEmpty: 'mdi-star-outline',
  ratingFull: 'mdi-star',
  ratingHalf: 'mdi-star-half-full',
  loading: 'mdi-cached',
  first: 'mdi-page-first',
  last: 'mdi-page-last',
  unfold: 'mdi-unfold-more-horizontal',
  file: 'mdi-paperclip',
  plus: 'mdi-plus',
  minus: 'mdi-minus',
  calendar: 'mdi-calendar',
  treeviewCollapse: 'mdi-menu-down',
  treeviewExpand: 'mdi-menu-right',
  tableGroupCollapse: 'mdi-chevron-down',
  tableGroupExpand: 'mdi-chevron-right',
  eyeDropper: 'mdi-eyedropper',
  upload: 'mdi-cloud-upload',
  cloud: 'mdi-cloud',
  color: 'mdi-palette',
  command: 'mdi-apple-keyboard-command',
  ctrl: 'mdi-apple-keyboard-control',
  space: 'mdi-keyboard-space',
  shift: 'mdi-apple-keyboard-shift',
  alt: 'mdi-apple-keyboard-option',
  enter: 'mdi-keyboard-return',
  arrowup: 'mdi-arrow-up',
  arrowdown: 'mdi-arrow-down',
  arrowleft: 'mdi-arrow-left',
  arrowright: 'mdi-arrow-right',
  backspace: 'mdi-backspace',
  play: 'mdi-play',
  pause: 'mdi-pause',
  fullscreen: 'mdi-fullscreen',
  fullscreenExit: 'mdi-fullscreen-exit',
  volumeHigh: 'mdi-volume-high',
  volumeMedium: 'mdi-volume-medium',
  volumeLow: 'mdi-volume-low',
  volumeOff: 'mdi-volume-variant-off',
  search: 'mdi-magnify',
}

export { aliases, mdi }
