// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: rpc_create_inventory.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventoryRequest) Reset() {
	*x = CreateInventoryRequest{}
	mi := &file_rpc_create_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryRequest) ProtoMessage() {}

func (x *CreateInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryRequest.ProtoReflect.Descriptor instead.
func (*CreateInventoryRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInventoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInventoryRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateInventoryRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CreateInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *Inventory             `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventoryResponse) Reset() {
	*x = CreateInventoryResponse{}
	mi := &file_rpc_create_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryResponse) ProtoMessage() {}

func (x *CreateInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryResponse.ProtoReflect.Descriptor instead.
func (*CreateInventoryResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInventoryResponse) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

var File_rpc_create_inventory_proto protoreflect.FileDescriptor

const file_rpc_create_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1arpc_create_inventory.proto\x12\x02pb\x1a\x0finventory.proto\"T\n" +
	"\x16CreateInventoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"F\n" +
	"\x17CreateInventoryResponse\x12+\n" +
	"\tinventory\x18\x01 \x01(\v2\r.pb.InventoryR\tinventoryB\x1bZ\x19github.com/mhdna/kashi/pbb\x06proto3"

var (
	file_rpc_create_inventory_proto_rawDescOnce sync.Once
	file_rpc_create_inventory_proto_rawDescData []byte
)

func file_rpc_create_inventory_proto_rawDescGZIP() []byte {
	file_rpc_create_inventory_proto_rawDescOnce.Do(func() {
		file_rpc_create_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_inventory_proto_rawDesc), len(file_rpc_create_inventory_proto_rawDesc)))
	})
	return file_rpc_create_inventory_proto_rawDescData
}

var file_rpc_create_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_inventory_proto_goTypes = []any{
	(*CreateInventoryRequest)(nil),  // 0: pb.CreateInventoryRequest
	(*CreateInventoryResponse)(nil), // 1: pb.CreateInventoryResponse
	(*Inventory)(nil),               // 2: pb.Inventory
}
var file_rpc_create_inventory_proto_depIdxs = []int32{
	2, // 0: pb.CreateInventoryResponse.inventory:type_name -> pb.Inventory
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_inventory_proto_init() }
func file_rpc_create_inventory_proto_init() {
	if File_rpc_create_inventory_proto != nil {
		return
	}
	file_inventory_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_inventory_proto_rawDesc), len(file_rpc_create_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_inventory_proto_goTypes,
		DependencyIndexes: file_rpc_create_inventory_proto_depIdxs,
		MessageInfos:      file_rpc_create_inventory_proto_msgTypes,
	}.Build()
	File_rpc_create_inventory_proto = out.File
	file_rpc_create_inventory_proto_goTypes = nil
	file_rpc_create_inventory_proto_depIdxs = nil
}
