// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: service_kashi.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_kashi_proto protoreflect.FileDescriptor

const file_service_kashi_proto_rawDesc = "" +
	"\n" +
	"\x13service_kashi.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x15rpc_create_user.proto\x1a\x14rpc_login_user.proto\x1a\x1arpc_create_inventory.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xbe\x02\n" +
	"\x05Kashi\x12=\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"\x00\x12\x8e\x01\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"T\x92A=\x12\n" +
	"Login User\x1a/Login user and get access token & refresh token\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/login\x12e\n" +
	"\x0eCreateInvetory\x12\x1a.pb.CreateInventoryRequest\x1a\x1b.pb.CreateInventoryResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/inventoriesBO\x92A1\x12/\n" +
	"\x05Kashi\"!\n" +
	"\x05mhdna\x12\x18https://github.com/mhdna2\x031.0Z\x19github.com/mhdna/kashi/pbb\x06proto3"

var file_service_kashi_proto_goTypes = []any{
	(*CreateUserRequest)(nil),       // 0: pb.CreateUserRequest
	(*LoginUserRequest)(nil),        // 1: pb.LoginUserRequest
	(*CreateInventoryRequest)(nil),  // 2: pb.CreateInventoryRequest
	(*CreateUserResponse)(nil),      // 3: pb.CreateUserResponse
	(*LoginUserResponse)(nil),       // 4: pb.LoginUserResponse
	(*CreateInventoryResponse)(nil), // 5: pb.CreateInventoryResponse
}
var file_service_kashi_proto_depIdxs = []int32{
	0, // 0: pb.Kashi.CreateUser:input_type -> pb.CreateUserRequest
	1, // 1: pb.Kashi.LoginUser:input_type -> pb.LoginUserRequest
	2, // 2: pb.Kashi.CreateInvetory:input_type -> pb.CreateInventoryRequest
	3, // 3: pb.Kashi.CreateUser:output_type -> pb.CreateUserResponse
	4, // 4: pb.Kashi.LoginUser:output_type -> pb.LoginUserResponse
	5, // 5: pb.Kashi.CreateInvetory:output_type -> pb.CreateInventoryResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_kashi_proto_init() }
func file_service_kashi_proto_init() {
	if File_service_kashi_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_login_user_proto_init()
	file_rpc_create_inventory_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_kashi_proto_rawDesc), len(file_service_kashi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_kashi_proto_goTypes,
		DependencyIndexes: file_service_kashi_proto_depIdxs,
	}.Build()
	File_service_kashi_proto = out.File
	file_service_kashi_proto_goTypes = nil
	file_service_kashi_proto_depIdxs = nil
}
