/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/About': RouteRecordInfo<'/About', '/About', Record<never, never>, Record<never, never>>,
    '/assets': RouteRecordInfo<'/assets', '/assets', Record<never, never>, Record<never, never>>,
    '/Attendance': RouteRecordInfo<'/Attendance', '/Attendance', Record<never, never>, Record<never, never>>,
    '/barcode-printing': RouteRecordInfo<'/barcode-printing', '/barcode-printing', Record<never, never>, Record<never, never>>,
    '/barcodes': RouteRecordInfo<'/barcodes', '/barcodes', Record<never, never>, Record<never, never>>,
    '/branch-invoices': RouteRecordInfo<'/branch-invoices', '/branch-invoices', Record<never, never>, Record<never, never>>,
    '/branches': RouteRecordInfo<'/branches', '/branches', Record<never, never>, Record<never, never>>,
    '/calendar': RouteRecordInfo<'/calendar', '/calendar', Record<never, never>, Record<never, never>>,
    '/client-page': RouteRecordInfo<'/client-page', '/client-page', Record<never, never>, Record<never, never>>,
    '/clients': RouteRecordInfo<'/clients', '/clients', Record<never, never>, Record<never, never>>,
    '/Colors_Sizes': RouteRecordInfo<'/Colors_Sizes', '/Colors_Sizes', Record<never, never>, Record<never, never>>,
    '/coupons': RouteRecordInfo<'/coupons', '/coupons', Record<never, never>, Record<never, never>>,
    '/currencies': RouteRecordInfo<'/currencies', '/currencies', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>, '/dashboard/ChartCard' | '/dashboard/ChartsRow' | '/dashboard/TablesRow' | '/dashboard/dashboard' | '/dashboard/tabs/AlertsTab' | '/dashboard/tabs/DemandTab' | '/dashboard/tabs/HealthTab' | '/dashboard/tabs/IncomeTab' | '/dashboard/tabs/OverviewTab' | '/dashboard/tabs/SalesAnalyticsTab' | '/dashboard/tabs/TargetsTab'>,
    '/dashboard/ChartCard': RouteRecordInfo<'/dashboard/ChartCard', '/dashboard/ChartCard', Record<never, never>, Record<never, never>>,
    '/dashboard/ChartsRow': RouteRecordInfo<'/dashboard/ChartsRow', '/dashboard/ChartsRow', Record<never, never>, Record<never, never>>,
    '/dashboard/dashboard': RouteRecordInfo<'/dashboard/dashboard', '/dashboard/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/TablesRow': RouteRecordInfo<'/dashboard/TablesRow', '/dashboard/TablesRow', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/AlertsTab': RouteRecordInfo<'/dashboard/tabs/AlertsTab', '/dashboard/tabs/AlertsTab', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/DemandTab': RouteRecordInfo<'/dashboard/tabs/DemandTab', '/dashboard/tabs/DemandTab', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/HealthTab': RouteRecordInfo<'/dashboard/tabs/HealthTab', '/dashboard/tabs/HealthTab', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/IncomeTab': RouteRecordInfo<'/dashboard/tabs/IncomeTab', '/dashboard/tabs/IncomeTab', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/OverviewTab': RouteRecordInfo<'/dashboard/tabs/OverviewTab', '/dashboard/tabs/OverviewTab', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/SalesAnalyticsTab': RouteRecordInfo<'/dashboard/tabs/SalesAnalyticsTab', '/dashboard/tabs/SalesAnalyticsTab', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/TargetsTab': RouteRecordInfo<'/dashboard/tabs/TargetsTab', '/dashboard/tabs/TargetsTab', Record<never, never>, Record<never, never>>,
    '/discounts': RouteRecordInfo<'/discounts', '/discounts', Record<never, never>, Record<never, never>>,
    '/employee_page': RouteRecordInfo<'/employee_page', '/employee_page', Record<never, never>, Record<never, never>>,
    '/employees': RouteRecordInfo<'/employees', '/employees', Record<never, never>, Record<never, never>>,
    '/expenses': RouteRecordInfo<'/expenses', '/expenses', Record<never, never>, Record<never, never>>,
    '/FilterBar': RouteRecordInfo<'/FilterBar', '/FilterBar', Record<never, never>, Record<never, never>>,
    '/FilterBtn': RouteRecordInfo<'/FilterBtn', '/FilterBtn', Record<never, never>, Record<never, never>>,
    '/inventory': RouteRecordInfo<'/inventory', '/inventory', Record<never, never>, Record<never, never>>,
    '/inventory-analysis': RouteRecordInfo<'/inventory-analysis', '/inventory-analysis', Record<never, never>, Record<never, never>>,
    '/invoice-types': RouteRecordInfo<'/invoice-types', '/invoice-types', Record<never, never>, Record<never, never>>,
    '/loan-payments': RouteRecordInfo<'/loan-payments', '/loan-payments', Record<never, never>, Record<never, never>>,
    '/loans': RouteRecordInfo<'/loans', '/loans', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/products': RouteRecordInfo<'/products', '/products', Record<never, never>, Record<never, never>>,
    '/purchase-invoice': RouteRecordInfo<'/purchase-invoice', '/purchase-invoice', Record<never, never>, Record<never, never>>,
    '/sales-invoices': RouteRecordInfo<'/sales-invoices', '/sales-invoices', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/shifts': RouteRecordInfo<'/shifts', '/shifts', Record<never, never>, Record<never, never>>,
    '/stats': RouteRecordInfo<'/stats', '/stats', Record<never, never>, Record<never, never>>,
    '/storage': RouteRecordInfo<'/storage', '/storage', Record<never, never>, Record<never, never>>,
    '/suppliers': RouteRecordInfo<'/suppliers', '/suppliers', Record<never, never>, Record<never, never>>,
    '/transfers': RouteRecordInfo<'/transfers', '/transfers', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
    '/users copy': RouteRecordInfo<'/users copy', '/users copy', Record<never, never>, Record<never, never>>,
    '/warehouses': RouteRecordInfo<'/warehouses', '/warehouses', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/About.vue': {
      routes: '/About'
      views: never
    }
    'src/pages/assets.vue': {
      routes: '/assets'
      views: never
    }
    'src/pages/Attendance.vue': {
      routes: '/Attendance'
      views: never
    }
    'src/pages/barcode-printing.vue': {
      routes: '/barcode-printing'
      views: never
    }
    'src/pages/barcodes.vue': {
      routes: '/barcodes'
      views: never
    }
    'src/pages/branch-invoices.vue': {
      routes: '/branch-invoices'
      views: never
    }
    'src/pages/branches.vue': {
      routes: '/branches'
      views: never
    }
    'src/pages/calendar.vue': {
      routes: '/calendar'
      views: never
    }
    'src/pages/client-page.vue': {
      routes: '/client-page'
      views: never
    }
    'src/pages/clients.vue': {
      routes: '/clients'
      views: never
    }
    'src/pages/Colors_Sizes.vue': {
      routes: '/Colors_Sizes'
      views: never
    }
    'src/pages/coupons.vue': {
      routes: '/coupons'
      views: never
    }
    'src/pages/currencies.vue': {
      routes: '/currencies'
      views: never
    }
    'src/pages/dashboard.vue': {
      routes: '/dashboard' | '/dashboard/tabs/AlertsTab' | '/dashboard/ChartCard' | '/dashboard/ChartsRow' | '/dashboard/dashboard' | '/dashboard/tabs/DemandTab' | '/dashboard/tabs/HealthTab' | '/dashboard/tabs/IncomeTab' | '/dashboard/tabs/OverviewTab' | '/dashboard/tabs/SalesAnalyticsTab' | '/dashboard/TablesRow' | '/dashboard/tabs' | '/dashboard/tabs/TargetsTab'
      views: 'default'
    }
    'src/pages/dashboard/ChartCard.vue': {
      routes: '/dashboard/ChartCard'
      views: never
    }
    'src/pages/dashboard/ChartsRow.vue': {
      routes: '/dashboard/ChartsRow'
      views: never
    }
    'src/pages/dashboard/dashboard.vue': {
      routes: '/dashboard/dashboard'
      views: never
    }
    'src/pages/dashboard/TablesRow.vue': {
      routes: '/dashboard/TablesRow'
      views: never
    }
    'src/pages/dashboard/tabs/AlertsTab.vue': {
      routes: '/dashboard/tabs/AlertsTab'
      views: never
    }
    'src/pages/dashboard/tabs/DemandTab.vue': {
      routes: '/dashboard/tabs/DemandTab'
      views: never
    }
    'src/pages/dashboard/tabs/HealthTab.vue': {
      routes: '/dashboard/tabs/HealthTab'
      views: never
    }
    'src/pages/dashboard/tabs/IncomeTab.vue': {
      routes: '/dashboard/tabs/IncomeTab'
      views: never
    }
    'src/pages/dashboard/tabs/OverviewTab.vue': {
      routes: '/dashboard/tabs/OverviewTab'
      views: never
    }
    'src/pages/dashboard/tabs/SalesAnalyticsTab.vue': {
      routes: '/dashboard/tabs/SalesAnalyticsTab'
      views: never
    }
    'src/pages/dashboard/tabs/TargetsTab.vue': {
      routes: '/dashboard/tabs/TargetsTab'
      views: never
    }
    'src/pages/discounts.vue': {
      routes: '/discounts'
      views: never
    }
    'src/pages/employee_page.vue': {
      routes: '/employee_page'
      views: never
    }
    'src/pages/employees.vue': {
      routes: '/employees'
      views: never
    }
    'src/pages/expenses.vue': {
      routes: '/expenses'
      views: never
    }
    'src/pages/FilterBar.vue': {
      routes: '/FilterBar'
      views: never
    }
    'src/pages/FilterBtn.vue': {
      routes: '/FilterBtn'
      views: never
    }
    'src/pages/inventory.vue': {
      routes: '/inventory'
      views: never
    }
    'src/pages/inventory-analysis.vue': {
      routes: '/inventory-analysis'
      views: never
    }
    'src/pages/invoice-types.vue': {
      routes: '/invoice-types'
      views: never
    }
    'src/pages/loan-payments.vue': {
      routes: '/loan-payments'
      views: never
    }
    'src/pages/loans.vue': {
      routes: '/loans'
      views: never
    }
    'src/pages/Login.vue': {
      routes: '/Login'
      views: never
    }
    'src/pages/products.vue': {
      routes: '/products'
      views: never
    }
    'src/pages/purchase-invoice.vue': {
      routes: '/purchase-invoice'
      views: never
    }
    'src/pages/sales-invoices.vue': {
      routes: '/sales-invoices'
      views: never
    }
    'src/pages/settings.vue': {
      routes: '/settings'
      views: never
    }
    'src/pages/shifts.vue': {
      routes: '/shifts'
      views: never
    }
    'src/pages/stats.vue': {
      routes: '/stats'
      views: never
    }
    'src/pages/storage.vue': {
      routes: '/storage'
      views: never
    }
    'src/pages/suppliers.vue': {
      routes: '/suppliers'
      views: never
    }
    'src/pages/transfers.vue': {
      routes: '/transfers'
      views: never
    }
    'src/pages/users.vue': {
      routes: '/users'
      views: never
    }
    'src/pages/users copy.vue': {
      routes: '/users copy'
      views: never
    }
    'src/pages/warehouses.vue': {
      routes: '/warehouses'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
