/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/About': RouteRecordInfo<'/About', '/About', Record<never, never>, Record<never, never>>,
    '/alerts': RouteRecordInfo<'/alerts', '/alerts', Record<never, never>, Record<never, never>>,
    '/assets': RouteRecordInfo<'/assets', '/assets', Record<never, never>, Record<never, never>>,
    '/Attendance': RouteRecordInfo<'/Attendance', '/Attendance', Record<never, never>, Record<never, never>>,
    '/attributes': RouteRecordInfo<'/attributes', '/attributes', Record<never, never>, Record<never, never>>,
    '/barcode-printing': RouteRecordInfo<'/barcode-printing', '/barcode-printing', Record<never, never>, Record<never, never>>,
    '/barcodes': RouteRecordInfo<'/barcodes', '/barcodes', Record<never, never>, Record<never, never>>,
    '/branch-invoices': RouteRecordInfo<'/branch-invoices', '/branch-invoices', Record<never, never>, Record<never, never>>,
    '/branch-settings': RouteRecordInfo<'/branch-settings', '/branch-settings', Record<never, never>, Record<never, never>>,
    '/branches': RouteRecordInfo<'/branches', '/branches', Record<never, never>, Record<never, never>>,
    '/calendar': RouteRecordInfo<'/calendar', '/calendar', Record<never, never>, Record<never, never>>,
    '/client-page': RouteRecordInfo<'/client-page', '/client-page', Record<never, never>, Record<never, never>>,
    '/clients': RouteRecordInfo<'/clients', '/clients', Record<never, never>, Record<never, never>>,
    '/Colors_Sizes': RouteRecordInfo<'/Colors_Sizes', '/Colors_Sizes', Record<never, never>, Record<never, never>>,
    '/coupons': RouteRecordInfo<'/coupons', '/coupons', Record<never, never>, Record<never, never>>,
    '/currencies': RouteRecordInfo<'/currencies', '/currencies', Record<never, never>, Record<never, never>>,
    '/daily-income': RouteRecordInfo<'/daily-income', '/daily-income', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>, '/dashboard/ChartCard' | '/dashboard/ChartsRow' | '/dashboard/DashboardList' | '/dashboard/DetailList' | '/dashboard/ExpenseReceiptThumb' | '/dashboard/FinancialPositionCard' | '/dashboard/InitialsAvatar' | '/dashboard/TablesRow' | '/dashboard/TargetCard' | '/dashboard/TargetsLoansRow' | '/dashboard/dashboard' | '/dashboard/dashboard.backup' | '/dashboard/tabs/AlertsTab' | '/dashboard/tabs/DemandTab' | '/dashboard/tabs/FinancialChartCard' | '/dashboard/tabs/FinancialsTab' | '/dashboard/tabs/HealthTab' | '/dashboard/tabs/IncomeTab' | '/dashboard/tabs/OverviewTab' | '/dashboard/tabs/RecentActivitiesTab' | '/dashboard/tabs/SalesAnalyticsTab' | '/dashboard/tabs/SalesTab' | '/dashboard/tabs/TargetsTab'>,
    '/dashboard/ChartCard': RouteRecordInfo<'/dashboard/ChartCard', '/dashboard/ChartCard', Record<never, never>, Record<never, never>>,
    '/dashboard/ChartsRow': RouteRecordInfo<'/dashboard/ChartsRow', '/dashboard/ChartsRow', Record<never, never>, Record<never, never>>,
    '/dashboard/dashboard': RouteRecordInfo<'/dashboard/dashboard', '/dashboard/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/dashboard.backup': RouteRecordInfo<'/dashboard/dashboard.backup', '/dashboard/dashboard/backup', Record<never, never>, Record<never, never>>,
    '/dashboard/DashboardList': RouteRecordInfo<'/dashboard/DashboardList', '/dashboard/DashboardList', Record<never, never>, Record<never, never>>,
    '/dashboard/DetailList': RouteRecordInfo<'/dashboard/DetailList', '/dashboard/DetailList', Record<never, never>, Record<never, never>>,
    '/dashboard/ExpenseReceiptThumb': RouteRecordInfo<'/dashboard/ExpenseReceiptThumb', '/dashboard/ExpenseReceiptThumb', Record<never, never>, Record<never, never>>,
    '/dashboard/FinancialPositionCard': RouteRecordInfo<'/dashboard/FinancialPositionCard', '/dashboard/FinancialPositionCard', Record<never, never>, Record<never, never>>,
    '/dashboard/InitialsAvatar': RouteRecordInfo<'/dashboard/InitialsAvatar', '/dashboard/InitialsAvatar', Record<never, never>, Record<never, never>>,
    '/dashboard/TablesRow': RouteRecordInfo<'/dashboard/TablesRow', '/dashboard/TablesRow', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/AlertsTab': RouteRecordInfo<'/dashboard/tabs/AlertsTab', '/dashboard/tabs/AlertsTab', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/DemandTab': RouteRecordInfo<'/dashboard/tabs/DemandTab', '/dashboard/tabs/DemandTab', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/FinancialChartCard': RouteRecordInfo<'/dashboard/tabs/FinancialChartCard', '/dashboard/tabs/FinancialChartCard', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/FinancialsTab': RouteRecordInfo<'/dashboard/tabs/FinancialsTab', '/dashboard/tabs/FinancialsTab', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/HealthTab': RouteRecordInfo<'/dashboard/tabs/HealthTab', '/dashboard/tabs/HealthTab', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/IncomeTab': RouteRecordInfo<'/dashboard/tabs/IncomeTab', '/dashboard/tabs/IncomeTab', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/OverviewTab': RouteRecordInfo<'/dashboard/tabs/OverviewTab', '/dashboard/tabs/OverviewTab', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/RecentActivitiesTab': RouteRecordInfo<'/dashboard/tabs/RecentActivitiesTab', '/dashboard/tabs/RecentActivitiesTab', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/SalesAnalyticsTab': RouteRecordInfo<'/dashboard/tabs/SalesAnalyticsTab', '/dashboard/tabs/SalesAnalyticsTab', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/SalesTab': RouteRecordInfo<'/dashboard/tabs/SalesTab', '/dashboard/tabs/SalesTab', Record<never, never>, Record<never, never>>,
    '/dashboard/tabs/TargetsTab': RouteRecordInfo<'/dashboard/tabs/TargetsTab', '/dashboard/tabs/TargetsTab', Record<never, never>, Record<never, never>>,
    '/dashboard/TargetCard': RouteRecordInfo<'/dashboard/TargetCard', '/dashboard/TargetCard', Record<never, never>, Record<never, never>>,
    '/dashboard/TargetsLoansRow': RouteRecordInfo<'/dashboard/TargetsLoansRow', '/dashboard/TargetsLoansRow', Record<never, never>, Record<never, never>>,
    '/discount-lists': RouteRecordInfo<'/discount-lists', '/discount-lists', Record<never, never>, Record<never, never>>,
    '/employee_page': RouteRecordInfo<'/employee_page', '/employee_page', Record<never, never>, Record<never, never>>,
    '/employees': RouteRecordInfo<'/employees', '/employees', Record<never, never>, Record<never, never>>,
    '/expenses': RouteRecordInfo<'/expenses', '/expenses', Record<never, never>, Record<never, never>>,
    '/FilterBar': RouteRecordInfo<'/FilterBar', '/FilterBar', Record<never, never>, Record<never, never>>,
    '/FilterBtn': RouteRecordInfo<'/FilterBtn', '/FilterBtn', Record<never, never>, Record<never, never>>,
    '/financials': RouteRecordInfo<'/financials', '/financials', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/inventory': RouteRecordInfo<'/inventory', '/inventory', Record<never, never>, Record<never, never>>,
    '/inventory-analysis': RouteRecordInfo<'/inventory-analysis', '/inventory-analysis', Record<never, never>, Record<never, never>>,
    '/loans': RouteRecordInfo<'/loans', '/loans', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/logs': RouteRecordInfo<'/logs', '/logs', Record<never, never>, Record<never, never>>,
    '/price-lists': RouteRecordInfo<'/price-lists', '/price-lists', Record<never, never>, Record<never, never>>,
    '/pricing': RouteRecordInfo<'/pricing', '/pricing', Record<never, never>, Record<never, never>>,
    '/products': RouteRecordInfo<'/products', '/products', Record<never, never>, Record<never, never>>,
    '/purchase-invoice': RouteRecordInfo<'/purchase-invoice', '/purchase-invoice', Record<never, never>, Record<never, never>>,
    '/sales-analysis': RouteRecordInfo<'/sales-analysis', '/sales-analysis', Record<never, never>, Record<never, never>>,
    '/sales-analytics': RouteRecordInfo<'/sales-analytics', '/sales-analytics', Record<never, never>, Record<never, never>>,
    '/sales-dashboard': RouteRecordInfo<'/sales-dashboard', '/sales-dashboard', Record<never, never>, Record<never, never>>,
    '/sales-invoices': RouteRecordInfo<'/sales-invoices', '/sales-invoices', Record<never, never>, Record<never, never>>,
    '/salesperson-performance': RouteRecordInfo<'/salesperson-performance', '/salesperson-performance', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/shifts': RouteRecordInfo<'/shifts', '/shifts', Record<never, never>, Record<never, never>>,
    '/stats': RouteRecordInfo<'/stats', '/stats', Record<never, never>, Record<never, never>>,
    '/stock-health': RouteRecordInfo<'/stock-health', '/stock-health', Record<never, never>, Record<never, never>>,
    '/stock-movements': RouteRecordInfo<'/stock-movements', '/stock-movements', Record<never, never>, Record<never, never>>,
    '/storage': RouteRecordInfo<'/storage', '/storage', Record<never, never>, Record<never, never>>,
    '/suppliers': RouteRecordInfo<'/suppliers', '/suppliers', Record<never, never>, Record<never, never>>,
    '/targets': RouteRecordInfo<'/targets', '/targets', Record<never, never>, Record<never, never>>,
    '/transfers': RouteRecordInfo<'/transfers', '/transfers', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
    '/users copy': RouteRecordInfo<'/users copy', '/users copy', Record<never, never>, Record<never, never>>,
    '/warehouses': RouteRecordInfo<'/warehouses', '/warehouses', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/About.vue': {
      routes: '/About'
      views: never
    }
    'src/pages/alerts.vue': {
      routes: '/alerts'
      views: never
    }
    'src/pages/assets.vue': {
      routes: '/assets'
      views: never
    }
    'src/pages/Attendance.vue': {
      routes: '/Attendance'
      views: never
    }
    'src/pages/attributes.vue': {
      routes: '/attributes'
      views: never
    }
    'src/pages/barcode-printing.vue': {
      routes: '/barcode-printing'
      views: never
    }
    'src/pages/barcodes.vue': {
      routes: '/barcodes'
      views: never
    }
    'src/pages/branch-invoices.vue': {
      routes: '/branch-invoices'
      views: never
    }
    'src/pages/branch-settings.vue': {
      routes: '/branch-settings'
      views: never
    }
    'src/pages/branches.vue': {
      routes: '/branches'
      views: never
    }
    'src/pages/calendar.vue': {
      routes: '/calendar'
      views: never
    }
    'src/pages/client-page.vue': {
      routes: '/client-page'
      views: never
    }
    'src/pages/clients.vue': {
      routes: '/clients'
      views: never
    }
    'src/pages/Colors_Sizes.vue': {
      routes: '/Colors_Sizes'
      views: never
    }
    'src/pages/coupons.vue': {
      routes: '/coupons'
      views: never
    }
    'src/pages/currencies.vue': {
      routes: '/currencies'
      views: never
    }
    'src/pages/daily-income.vue': {
      routes: '/daily-income'
      views: never
    }
    'src/pages/dashboard.vue': {
      routes: '/dashboard' | '/dashboard/tabs/AlertsTab' | '/dashboard/ChartCard' | '/dashboard/ChartsRow' | '/dashboard/dashboard' | '/dashboard/dashboard.backup' | '/dashboard/DashboardList' | '/dashboard/tabs/DemandTab' | '/dashboard/DetailList' | '/dashboard/ExpenseReceiptThumb' | '/dashboard/tabs/FinancialChartCard' | '/dashboard/FinancialPositionCard' | '/dashboard/tabs/FinancialsTab' | '/dashboard/tabs/HealthTab' | '/dashboard/tabs/IncomeTab' | '/dashboard/InitialsAvatar' | '/dashboard/tabs/OverviewTab' | '/dashboard/tabs/RecentActivitiesTab' | '/dashboard/tabs/SalesAnalyticsTab' | '/dashboard/tabs/SalesTab' | '/dashboard/TablesRow' | '/dashboard/tabs' | '/dashboard/TargetCard' | '/dashboard/TargetsLoansRow' | '/dashboard/tabs/TargetsTab'
      views: 'default'
    }
    'src/pages/dashboard/ChartCard.vue': {
      routes: '/dashboard/ChartCard'
      views: never
    }
    'src/pages/dashboard/ChartsRow.vue': {
      routes: '/dashboard/ChartsRow'
      views: never
    }
    'src/pages/dashboard/dashboard.vue': {
      routes: '/dashboard/dashboard'
      views: never
    }
    'src/pages/dashboard/dashboard.backup.vue': {
      routes: '/dashboard/dashboard.backup'
      views: never
    }
    'src/pages/dashboard/DashboardList.vue': {
      routes: '/dashboard/DashboardList'
      views: never
    }
    'src/pages/dashboard/DetailList.vue': {
      routes: '/dashboard/DetailList'
      views: never
    }
    'src/pages/dashboard/ExpenseReceiptThumb.vue': {
      routes: '/dashboard/ExpenseReceiptThumb'
      views: never
    }
    'src/pages/dashboard/FinancialPositionCard.vue': {
      routes: '/dashboard/FinancialPositionCard'
      views: never
    }
    'src/pages/dashboard/InitialsAvatar.vue': {
      routes: '/dashboard/InitialsAvatar'
      views: never
    }
    'src/pages/dashboard/TablesRow.vue': {
      routes: '/dashboard/TablesRow'
      views: never
    }
    'src/pages/dashboard/tabs/AlertsTab.vue': {
      routes: '/dashboard/tabs/AlertsTab'
      views: never
    }
    'src/pages/dashboard/tabs/DemandTab.vue': {
      routes: '/dashboard/tabs/DemandTab'
      views: never
    }
    'src/pages/dashboard/tabs/FinancialChartCard.vue': {
      routes: '/dashboard/tabs/FinancialChartCard'
      views: never
    }
    'src/pages/dashboard/tabs/FinancialsTab.vue': {
      routes: '/dashboard/tabs/FinancialsTab'
      views: never
    }
    'src/pages/dashboard/tabs/HealthTab.vue': {
      routes: '/dashboard/tabs/HealthTab'
      views: never
    }
    'src/pages/dashboard/tabs/IncomeTab.vue': {
      routes: '/dashboard/tabs/IncomeTab'
      views: never
    }
    'src/pages/dashboard/tabs/OverviewTab.vue': {
      routes: '/dashboard/tabs/OverviewTab'
      views: never
    }
    'src/pages/dashboard/tabs/RecentActivitiesTab.vue': {
      routes: '/dashboard/tabs/RecentActivitiesTab'
      views: never
    }
    'src/pages/dashboard/tabs/SalesAnalyticsTab.vue': {
      routes: '/dashboard/tabs/SalesAnalyticsTab'
      views: never
    }
    'src/pages/dashboard/tabs/SalesTab.vue': {
      routes: '/dashboard/tabs/SalesTab'
      views: never
    }
    'src/pages/dashboard/tabs/TargetsTab.vue': {
      routes: '/dashboard/tabs/TargetsTab'
      views: never
    }
    'src/pages/dashboard/TargetCard.vue': {
      routes: '/dashboard/TargetCard'
      views: never
    }
    'src/pages/dashboard/TargetsLoansRow.vue': {
      routes: '/dashboard/TargetsLoansRow'
      views: never
    }
    'src/pages/discount-lists.vue': {
      routes: '/discount-lists'
      views: never
    }
    'src/pages/employee_page.vue': {
      routes: '/employee_page'
      views: never
    }
    'src/pages/employees.vue': {
      routes: '/employees'
      views: never
    }
    'src/pages/expenses.vue': {
      routes: '/expenses'
      views: never
    }
    'src/pages/FilterBar.vue': {
      routes: '/FilterBar'
      views: never
    }
    'src/pages/FilterBtn.vue': {
      routes: '/FilterBtn'
      views: never
    }
    'src/pages/financials.vue': {
      routes: '/financials'
      views: never
    }
    'src/pages/home.vue': {
      routes: '/home'
      views: never
    }
    'src/pages/inventory.vue': {
      routes: '/inventory'
      views: never
    }
    'src/pages/inventory-analysis.vue': {
      routes: '/inventory-analysis'
      views: never
    }
    'src/pages/loans.vue': {
      routes: '/loans'
      views: never
    }
    'src/pages/Login.vue': {
      routes: '/Login'
      views: never
    }
    'src/pages/logs.vue': {
      routes: '/logs'
      views: never
    }
    'src/pages/price-lists.vue': {
      routes: '/price-lists'
      views: never
    }
    'src/pages/pricing.vue': {
      routes: '/pricing'
      views: never
    }
    'src/pages/products.vue': {
      routes: '/products'
      views: never
    }
    'src/pages/purchase-invoice.vue': {
      routes: '/purchase-invoice'
      views: never
    }
    'src/pages/sales-analysis.vue': {
      routes: '/sales-analysis'
      views: never
    }
    'src/pages/sales-analytics.vue': {
      routes: '/sales-analytics'
      views: never
    }
    'src/pages/sales-dashboard.vue': {
      routes: '/sales-dashboard'
      views: never
    }
    'src/pages/sales-invoices.vue': {
      routes: '/sales-invoices'
      views: never
    }
    'src/pages/salesperson-performance.vue': {
      routes: '/salesperson-performance'
      views: never
    }
    'src/pages/settings.vue': {
      routes: '/settings'
      views: never
    }
    'src/pages/shifts.vue': {
      routes: '/shifts'
      views: never
    }
    'src/pages/stats.vue': {
      routes: '/stats'
      views: never
    }
    'src/pages/stock-health.vue': {
      routes: '/stock-health'
      views: never
    }
    'src/pages/stock-movements.vue': {
      routes: '/stock-movements'
      views: never
    }
    'src/pages/storage.vue': {
      routes: '/storage'
      views: never
    }
    'src/pages/suppliers.vue': {
      routes: '/suppliers'
      views: never
    }
    'src/pages/targets.vue': {
      routes: '/targets'
      views: never
    }
    'src/pages/transfers.vue': {
      routes: '/transfers'
      views: never
    }
    'src/pages/users.vue': {
      routes: '/users'
      views: never
    }
    'src/pages/users copy.vue': {
      routes: '/users copy'
      views: never
    }
    'src/pages/warehouses.vue': {
      routes: '/warehouses'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
