package api

import (
	"bytes"
	"fmt"
	"strings"
)

// --- EAN-13 encoding -------------------------------------------------------

var eanL = [10]string{"0001101", "0011001", "0010011", "0111101", "0100011", "0110001", "0101111", "0111011", "0110111", "0001011"}
var eanG = [10]string{"0100111", "0110011", "0011011", "0100001", "0011101", "0111001", "0000101", "0010001", "0001001", "0010111"}
var eanR = [10]string{"1110010", "1100110", "1101100", "1000010", "1011100", "1001110", "1010000", "1000100", "1001000", "1110100"}
var eanParity = [10]string{"LLLLLL", "LLGLGG", "LLGGLG", "LLGGGL", "LGLLGG", "LGGLLG", "LGGGLL", "LGLGLG", "LGLGGL", "LGGLGL"}

func ean13CheckDigit(digits string) (int, bool) {
	if len(digits) != 12 {
		return 0, false
	}
	sum := 0
	for i, r := range digits {
		if r < '0' || r > '9' {
			return 0, false
		}
		v := int(r - '0')
		if i%2 == 1 {
			sum += v * 3
		} else {
			sum += v
		}
	}
	return (10 - sum%10) % 10, true
}

// ean13Bars returns the black/white module string for a 13-digit EAN-13 code.
func ean13Bars(code string) (string, bool) {
	if len(code) != 13 {
		return "", false
	}
	first := int(code[0] - '0')
	if first < 0 || first > 9 {
		return "", false
	}
	var bars strings.Builder
	bars.WriteString("101")
	for i, r := range code[1:7] {
		d := int(r - '0')
		if d < 0 || d > 9 {
			return "", false
		}
		if eanParity[first][i] == 'L' {
			bars.WriteString(eanL[d])
		} else {
			bars.WriteString(eanG[d])
		}
	}
	bars.WriteString("01010")
	for _, r := range code[7:] {
		d := int(r - '0')
		if d < 0 || d > 9 {
			return "", false
		}
		bars.WriteString(eanR[d])
	}
	bars.WriteString("101")
	return bars.String(), true
}

// isEAN13 reports whether s is exactly 13 digits. The check digit isn't
// re-validated here: barcodes are generated by db.generateEAN13, whose
// weighting the rest of the system trusts, and we only need to know a real
// code has been assigned (vs. a legacy/empty/non-numeric value).
func isEAN13(s string) bool {
	if len(s) != 13 {
		return false
	}
	for i := 0; i < 13; i++ {
		if s[i] < '0' || s[i] > '9' {
			return false
		}
	}
	return true
}

// --- text metrics --------------------------------------------------------

var helveticaWidths = map[rune]float64{
	' ': 278, '!': 278, '"': 355, '#': 556, '$': 556, '%': 889, '&': 667, '\'': 191,
	'(': 333, ')': 333, '*': 389, '+': 584, ',': 278, '-': 333, '.': 278, '/': 278,
	'0': 556, '1': 556, '2': 556, '3': 556, '4': 556, '5': 556, '6': 556, '7': 556, '8': 556, '9': 556,
	':': 278, ';': 278, '<': 584, '=': 584, '>': 584, '?': 556, '@': 1015,
	'A': 667, 'B': 667, 'C': 722, 'D': 722, 'E': 667, 'F': 611, 'G': 778, 'H': 722, 'I': 278, 'J': 500,
	'K': 667, 'L': 556, 'M': 833, 'N': 722, 'O': 778, 'P': 667, 'Q': 778, 'R': 722, 'S': 667, 'T': 611,
	'U': 722, 'V': 667, 'W': 944, 'X': 667, 'Y': 667, 'Z': 611,
	'[': 278, '\\': 278, ']': 278, '^': 469, '_': 556, '`': 333,
	'a': 556, 'b': 556, 'c': 500, 'd': 556, 'e': 556, 'f': 278, 'g': 556, 'h': 556, 'i': 222, 'j': 222,
	'k': 500, 'l': 222, 'm': 833, 'n': 556, 'o': 556, 'p': 556, 'q': 556, 'r': 333, 's': 500, 't': 278,
	'u': 556, 'v': 500, 'w': 722, 'x': 500, 'y': 500, 'z': 500,
	'{': 334, '|': 260, '}': 334, '~': 584,
}

func pdfTextWidth(s string, size float64) float64 {
	var units float64
	for _, r := range s {
		if w, ok := helveticaWidths[r]; ok {
			units += w
		} else {
			units += 556
		}
	}
	return units * size / 1000
}

func pdfEscape(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, "(", `\(`)
	return strings.ReplaceAll(s, ")", `\)`)
}

// --- label document ----------------------------------------------------

// labelItem is one product-variant's worth of labels to print.
type labelItem struct {
	Name    string
	Code    string
	Barcode string
	Price   string // pre-formatted, e.g. "39.00"
	Brand   string
	Color   string
	Size    string
	Qty     int
}

type labelOptions struct {
	Width     float64 // page width in points
	Height    float64 // page height in points
	Separator bool    // prepend a header page before each item + draw side borders
	Fields    map[string]bool
}

// pdfDoc accumulates PDF objects and pages.
type pdfDoc struct {
	buf     bytes.Buffer
	offsets []int
	pageRefs []int // object numbers of page objects
	nextObj int
}

func newPDFDoc() *pdfDoc {
	d := &pdfDoc{nextObj: 1}
	d.buf.WriteString("%PDF-1.4\n")
	return d
}

func (d *pdfDoc) obj(body string) int {
	n := d.nextObj
	d.nextObj++
	for len(d.offsets) < n {
		d.offsets = append(d.offsets, 0)
	}
	d.offsets[n-1] = d.buf.Len()
	fmt.Fprintf(&d.buf, "%d 0 obj\n%s\nendobj\n", n, body)
	return n
}

// reserve grabs an object number to be filled in later (forward reference).
func (d *pdfDoc) reserve() int {
	n := d.nextObj
	d.nextObj++
	for len(d.offsets) < n {
		d.offsets = append(d.offsets, 0)
	}
	return n
}

func (d *pdfDoc) fill(n int, body string) {
	d.offsets[n-1] = d.buf.Len()
	fmt.Fprintf(&d.buf, "%d 0 obj\n%s\nendobj\n", n, body)
}

func (d *pdfDoc) addPage(w, h float64, fontReg, fontBold int, content string) {
	contentObj := d.obj(fmt.Sprintf("<< /Length %d >>\nstream\n%s\nendstream", len(content), content))
	pageObj := d.obj(fmt.Sprintf(
		"<< /Type /Page /Parent %%PAGES%% /MediaBox [0 0 %.2f %.2f] /Resources << /Font << /F1 %d 0 R /FB %d 0 R >> >> /Contents %d 0 R >>",
		w, h, fontReg, fontBold, contentObj))
	d.pageRefs = append(d.pageRefs, pageObj)
}

func (d *pdfDoc) finish() []byte {
	// Catalog + Pages tree are the last objects; page objects were written
	// with a %PAGES% placeholder for the Pages object number.
	pagesObj := d.reserve()
	catalogObj := d.obj(fmt.Sprintf("<< /Type /Catalog /Pages %d 0 R >>", pagesObj))
	kids := make([]string, len(d.pageRefs))
	for i, ref := range d.pageRefs {
		kids[i] = fmt.Sprintf("%d 0 R", ref)
	}
	d.fill(pagesObj, fmt.Sprintf("<< /Type /Pages /Kids [%s] /Count %d >>", strings.Join(kids, " "), len(d.pageRefs)))

	body := strings.ReplaceAll(d.buf.String(), "%PAGES%", fmt.Sprintf("%d 0 R", pagesObj))
	// Offsets shifted because %PAGES% (7 bytes) -> "N 0 R". Rebuild cleanly.
	return rebuildXref(body, catalogObj)
}

// rebuildXref re-scans a PDF body for "N 0 obj" markers and writes a fresh
// xref table + trailer. Simpler and safer than tracking byte offsets through
// the %PAGES% substitution.
func rebuildXref(body string, rootObj int) []byte {
	var out bytes.Buffer
	out.WriteString(body)

	// Find object offsets.
	type off struct{ n, pos int }
	var offs []off
	for i := 0; i < len(body); i++ {
		if body[i] == '\n' && i+1 < len(body) {
			// look for "<num> 0 obj" at start of a line
			j := i + 1
			k := j
			for k < len(body) && body[k] >= '0' && body[k] <= '9' {
				k++
			}
			if k > j && strings.HasPrefix(body[k:], " 0 obj\n") {
				num := 0
				for _, c := range body[j:k] {
					num = num*10 + int(c-'0')
				}
				offs = append(offs, off{num, j})
			}
		}
	}
	maxN := 0
	for _, o := range offs {
		if o.n > maxN {
			maxN = o.n
		}
	}
	table := make([]int, maxN+1)
	for _, o := range offs {
		table[o.n] = o.pos
	}

	xrefStart := out.Len()
	fmt.Fprintf(&out, "xref\n0 %d\n", maxN+1)
	out.WriteString("0000000000 65535 f \n")
	for n := 1; n <= maxN; n++ {
		fmt.Fprintf(&out, "%010d 00000 n \n", table[n])
	}
	fmt.Fprintf(&out, "trailer\n<< /Size %d /Root %d 0 R >>\nstartxref\n%d\n%%%%EOF\n", maxN+1, rootObj, xrefStart)
	return out.Bytes()
}

// buildLabelsPDF renders every item's labels (plus optional separator pages)
// into a single PDF. Layout mirrors kashi-pos' design2 label.
func buildLabelsPDF(items []labelItem, opts labelOptions) ([]byte, error) {
	if opts.Width <= 0 {
		opts.Width = 288
	}
	if opts.Height <= 0 {
		opts.Height = 144
	}
	const designW, designH = 288.0, 144.0
	scale := opts.Width / designW
	if hs := opts.Height / designH; hs < scale {
		scale = hs
	}
	yOffset := (opts.Height - designH*scale) / 2

	doc := newPDFDoc()
	fontReg := doc.obj("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
	fontBold := doc.obj("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>")

	sideBarW := 14.0 // border strip width on the design canvas

	for _, it := range items {
		bars, ok := ean13Bars(it.Barcode)
		if !ok {
			return nil, fmt.Errorf("variant barcode %q is not a valid EAN-13", it.Barcode)
		}
		qty := it.Qty
		if qty < 1 {
			qty = 1
		}

		if opts.Separator {
			doc.addPage(opts.Width, opts.Height, fontReg, fontBold,
				separatorContent(it, qty, opts, scale, yOffset, designW, designH, sideBarW))
		}

		label := labelContent(it, bars, opts.Separator, scale, yOffset, designW, sideBarW)
		for i := 0; i < qty; i++ {
			doc.addPage(opts.Width, opts.Height, fontReg, fontBold, label)
		}
	}

	return doc.finish(), nil
}

func separatorContent(it labelItem, qty int, opts labelOptions, scale, yOffset, designW, designH, sideBarW float64) string {
	var c bytes.Buffer
	fmt.Fprintf(&c, "q\n%.4f 0 0 %.4f 0 %.2f cm\n0 0 0 rg\n", scale, scale, yOffset)

	// Left / right border strips.
	fmt.Fprintf(&c, "%.2f %.2f %.2f %.2f re f\n", 0.0, 0.0, sideBarW, designH)
	fmt.Fprintf(&c, "%.2f %.2f %.2f %.2f re f\n", designW-sideBarW, 0.0, sideBarW, designH)

	lines := make([]string, 0, 5)
	if opts.Fields["name"] && it.Name != "" {
		lines = append(lines, it.Name)
	}
	if opts.Fields["brand"] && it.Brand != "" {
		lines = append(lines, it.Brand)
	}
	if opts.Fields["color"] && it.Color != "" {
		lines = append(lines, it.Color)
	}
	if opts.Fields["size"] && it.Size != "" {
		lines = append(lines, "Size "+it.Size)
	}
	if opts.Fields["qty"] {
		lines = append(lines, fmt.Sprintf("%d pcs", qty))
	}
	if len(lines) == 0 {
		lines = append(lines, it.Name)
	}

	size := 20.0
	spacing := 26.0
	firstBaseline := designH/2 + float64(len(lines)-1)*spacing/2
	for i, line := range lines {
		fontSize := size
		font := "/F1"
		if i == 0 {
			fontSize = size * 1.25
			font = "/FB"
		}
		x := (designW - pdfTextWidth(line, fontSize)) / 2
		baseline := firstBaseline - float64(i)*spacing
		fmt.Fprintf(&c, "BT %s %.2f Tf %.2f %.2f Td (%s) Tj ET\n", font, fontSize, x, baseline, pdfEscape(line))
	}
	c.WriteString("Q\n")
	return c.String()
}

func labelContent(it labelItem, bars string, borders bool, scale, yOffset, designW, sideBarW float64) string {
	var c bytes.Buffer
	fmt.Fprintf(&c, "q\n%.4f 0 0 %.4f 0 %.2f cm\n0 0 0 rg\n0 0 0 RG\n", scale, scale, yOffset)

	if borders {
		fmt.Fprintf(&c, "%.2f %.2f %.2f %.2f re f\n", 0.0, 0.0, sideBarW, 144.0)
		fmt.Fprintf(&c, "%.2f %.2f %.2f %.2f re f\n", designW-sideBarW, 0.0, sideBarW, 144.0)
	}

	priceText := it.Price
	if priceText != "" {
		priceText += " $"
	}
	priceSize, nameSize, codeSize, digitsSize := 24.0, 17.0, 14.0, 14.0

	if priceText != "" {
		priceW := pdfTextWidth(priceText, priceSize)
		fmt.Fprintf(&c, "BT /FB %.2f Tf %.2f %.2f Td (%s) Tj ET\n", priceSize, (designW-priceW)/2, 118.0, pdfEscape(priceText))
		lineW := priceW * 1.8
		if lineW > designW-2*sideBarW-8 {
			lineW = designW - 2*sideBarW - 8
		}
		fmt.Fprintf(&c, "%.2f w %.2f %.2f m %.2f %.2f l S\n", 1.0, (designW-lineW)/2, 112.0, (designW+lineW)/2, 112.0)
	}

	name := it.Name
	if it.Color != "" {
		name += " / " + it.Color
	}
	if it.Size != "" {
		name += " / " + it.Size
	}
	fmt.Fprintf(&c, "BT /F1 %.2f Tf %.2f %.2f Td (%s) Tj ET\n", nameSize, (designW-pdfTextWidth(name, nameSize))/2, 92.0, pdfEscape(name))
	fmt.Fprintf(&c, "BT /F1 %.2f Tf %.2f %.2f Td (%s) Tj ET\n", codeSize, (designW-pdfTextWidth(it.Code, codeSize))/2, 72.0, pdfEscape(it.Code))

	moduleW := 1.7
	barW := moduleW * 0.82
	barcodeW := float64(len(bars)) * moduleW
	barcodeX := (designW - barcodeW) / 2
	barcodeY, barcodeH := 38.0, 26.0
	guardExtra := 8.0
	guardY, guardH := barcodeY-guardExtra, barcodeH+guardExtra
	const startGuardLen, digitBlockLen, centerGuardLen = 3, 42, 5
	leftDigitsEnd := startGuardLen + digitBlockLen
	centerGuardEnd := leftDigitsEnd + centerGuardLen
	rightDigitsEnd := centerGuardEnd + digitBlockLen
	isGuard := func(i int) bool {
		return i < startGuardLen || (i >= leftDigitsEnd && i < centerGuardEnd) || i >= rightDigitsEnd
	}
	x := barcodeX
	for j, bit := range bars {
		if bit == '1' {
			if isGuard(j) {
				fmt.Fprintf(&c, "%.3f %.2f %.3f %.2f re f\n", x+(moduleW-barW)/2, guardY, barW, guardH)
			} else {
				fmt.Fprintf(&c, "%.3f %.2f %.3f %.2f re f\n", x+(moduleW-barW)/2, barcodeY, barW, barcodeH)
			}
		}
		x += moduleW
	}
	digitsW := pdfTextWidth(it.Barcode, digitsSize)
	fmt.Fprintf(&c, "BT /F1 %.2f Tf %.2f %.2f Td (%s) Tj ET\n", digitsSize, barcodeX+(barcodeW-digitsW)/2, guardY-12.0, pdfEscape(it.Barcode))

	c.WriteString("Q\n")
	return c.String()
}
